quantopian/zipline

- zipline/finance/risk/cumulative.py
Risk calculations are robust to nans, except for
beta which calls numpy with the complete list of
algorithm_returns. If nans are present the result
of covar will be nan.
This is fixed by filtering out nans in
algorithm_returns.
> MAINT: Make beta calculation robust to missing values.

- docs/release-notes/zipline-0.7.1.md
- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
> adding net leverage, long/short exposure, long/short position count

- .travis.yml
So this will test a 2x2 matrix.
py 2.7 pandas 0.12.0
py 2.7 pandas 0.15.2
py 3.3 pandas 0.12.0
py 3.3 pandas 0.15.2
It might be overkill to test all 4. Maybe py 2.7/pandas 0.12.0 and py3.3/pandas 0.15.2 would suffice. 
Either way, if we're supporting 0.12.0 it should be in the test matrix somewhere.
> Update test matrix to test both pandas 0.12.0 and 0.15.2

- zipline/algorithm.py
datetime.datetime objects are immutable.
> PERF: Makes get_datetime not make a copy.

- zipline/finance/performance/tracker.py
The series was being generated as all minutes between two times.
It should be only the trading minutes.
> BUG: Changed benchmark returns to only contain market minutes.

- zipline/finance/performance/period.py
For use in a function that wraps de-serialization, to call instead of
creating the OrderedDicts from a module outside of the object.
So that the other module does not need to the internals of this object,
also to ensure that the cythonized OrderedDict is used, when available.
This need should be superseded with serialization versioning.
> MAINT: Provide a function to create the position calc containers.

- zipline/finance/blotter.py
as it is a backwards compat. Without sorting the orders are filled by
order date. With sorting the orders are moved to back of queue after
partil fills. If all orders are fully filled, there is no
deviation. Also there is no portfolio difference as this is about
assigning fills to equivalent orders.
> BUG: Added sorting back to orders. This isn't a functional bug so much

- tests/test_sources.py
- zipline/sources/data_frame_source.py
Filter nans in DataFrame and Panel sources.
If a SID hasn't started trading yet, pandas' convention is to use nans.
Before this change, zipline would raise an exception if there were nans in the
input data.
We now skip events where the prices contains a nan and has not been traded
before (in which case forward fill).
Fixes #446.
> Ignore SIDs that contain NaNs and have not been traded yet in   DataFrame sources.

- zipline/finance/performance/tracker.py
The returns Series in the perf tracker appears to be vestigial, so
remove.
Discovered while investigating what needs to be updated during 'fast backtest' mode for https://github.com/quantopian/zipline/issues/538
> MAINT: Remove unused returns vector from perf tracker.

- zipline/data/loader.py
- zipline/finance/trading.py
Instead of converting the curves back and forth from dictionaries to
DataFrame and back, use the DataFrame format when passing to
environment.
Ran across this while examining how curves were cached in our internal client. Looking to port over to caching just the DataFrame, and making the type expected by load the same DataFrame type that is cached by the Zipline loader is the most straight forward way to not need to store a large amount of dictionaries.
> MAINT: Change expected type of treasury curves from load to DataFrame.

- zipline/finance/risk/cumulative.py
Instead of using pd.Series calculations, pass the underlying
numpy array which have already been sliced to the exact dt, to prevent
calculation like beta creating some temporary copies of the Series with
an unneeded call to `dropna`.
The creation of the temporary Series was consuming more memory than
needed, with the index being the high penalty.
> PERF: Reduce memory usage during risk metric calculations.

- zipline/utils/security_list.py
The correct thing to look at to figure out where the root of the
zipline tree is, is `zipline.__file__`, not `zipline.__path__`. The
latter could contain multiple directories in it, and is not intended
to be `os.path.join()`ed as the previous code was doing.
> BUG: Correct method for finding security lists directory

- zipline/finance/performance/tracker.py
The intraday_risk_metrics is being removed since the values are not
used; cumulative risk metrics with the last value updated to the latest
close has been used for some time.
Before the removal of intraday_risk_metrics, the position trackers
passing of benchmark returns to the cumulative risk metrics needs to no
longer depend on the calculations done by the intraday stats. So instead
use the all_benchmark_returns stored in the tracker directly.
The memory issues could be further tuned ala https://github.com/quantopian/zipline/commit/00ea7b04d10f095d064256f4dedff29c095466f3, but cutting this off at the root is simpler.
Effect shown by logging RSS and VM highwater mark for a noop algo using minute emissions.
(Over two months the usage is ~200MB vs. ~750MB)
> Reduce memory footprint of minute emission algorithms.

- tests/test_perf_tracking.py
- zipline/finance/performance/tracker.py
event_count is not referenced anywhere, so remove extra bit of state
tracking.
> MAINT: Remove unused event_count from tracker.

- tests/test_finance.py
- tests/test_perf_tracking.py
- zipline/finance/blotter.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
By having both the trade simulation main loop route events to "process"
methods based on event type and the process methods also checking event
type, there was some duplicated effort in doing that comparison many
times.
A particular case where this was noted in profiling was for the
`process_event` function which was checking if the type was not a trade
and returning early, when in a larger universe of stocks the value
returned False 99% of the time.
Instead provide separate process functions specific to each type,
e.g. e.g. `process_trade` and `process_transaction` and route traffic to
those functions in tradesimulation.
For a universe of 160 stocks on both no-op algo and an algo that rebuys
its universe every day, saw about a 10% increase locally.
> PERF: Use specific methods for processing events.

- tests/test_algorithm.py
- tests/test_algorithm_gen.py
- tests/test_finance.py
- tests/test_transforms.py
- zipline/sources/test_source.py
- zipline/utils/factory.py
- zipline/utils/simfactory.py
Test sources are now defined by the sim_params period_start and period_end, rather than by the period_start and a defined 'count' of bars. This allows us to consider the sim_params.period_end as the canonical definition of the end of a simulation.
> DEP: Removes use of 'count'-defined test sources

- zipline/algorithm.py
np.allclose creates a vector of size 1 if passed a scalar, which showed
up as a bottleneck in algorithms with a large number of
order_target_percent calls.
> PERF: Use tolerant_equals instead of np.allclose in order types.

- tests/test_perf_tracking.py
- tests/test_sources.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
- zipline/protocol.py
- zipline/sources/data_source.py
- zipline/utils/factory.py
This PR enables signals to be sent from ```DataSource``` which tells zipline to close any open positions for the given sid.
Note: this PR uses code from #592 and borrowed lines from the __futures-trading__ branch.
cc @ehebert @jfkirk
> ENH: Add CLOSE_POSTION as DataSource event type

- zipline/sources/data_source.py
The way ```DataSource``` is currently implemented only ```DATASOURCE_TYPE.TRADE``` is allowed. In this PR I want to allow the type to be passed with the data and if not then ```TRADE``` is used as default.
cc @ehebert @jfkirk @ssanderson
> ENH: allow passing of data type to DataSource

- tests/test_algorithm.py
- tests/test_batchtransform.py
- tests/test_history.py
- zipline/algorithm.py
This commit moves the call to the algo code's initialize method out of TradingAlgorithm.__init__. The algo code's initialize method will be called in _create_generator using args and kwargs that are stored from __init__.
> ENH: Moves calling of TradingAlgorithm.initialize to _create_generator

- tests/test_assets.py
- zipline/assets/assets.py
- zipline/finance/trading.py
- AssetFinder no longer accepts an unused trading_calendar.
- AssetFinder correctly accepts a DataFrame as input.
- Tests for AssetFinder no longer rely on a global trading environment.
> TEST: Clean AssetFinder initialization and tests.

- tests/test_assets.py
- zipline/assets/_assets.pyx
- zipline/assets/assets.py
This branch adds further functionality for futures in zipline.
Asset objects now have a `root_symbol` attribute, and AssetFinder holds an additional cache, `future_cache`, keyed on root_symbol. Also adds the AssetFinder methods `lookup_future_chain` (returns the list of valid contracts for a given root symbol), `lookup_future_in_chain` (finds the ith contract in the chain), and `lookup_future_by_expiration` (finds a contract by its expiration date).
> Futures additions for Asset and AssetFinder

- tests/test_assets.py
- zipline/assets/assets.py
Contracts must have been trading at the as_of_date to be considered valid, and a contract's position in the chain is now zero-indexed.
> BUG: Fixes issues with AssetFinder future lookups

- tests/risk/test_risk_cumulative.py
- tests/risk/test_risk_period.py
- tests/test_events_through_risk.py
- zipline/finance/performance/tracker.py
- zipline/finance/risk/cumulative.py
- zipline/finance/risk/period.py
Instead of using the pandas.Series datetime index for every single
vector, get the index at the beginning of the update loop based on the
dt and then use that index to set the values.
Also, since the dt lookup is no longer needed, store the values as numpy
arrays, which are more lightweight.
Locally, this patch cuts out about 60% of the time spent in the update
method.
> PERF: Reduce time spent indexing in risk cumulative update.

- etc/requirements.txt
- zipline/algorithm.py
- zipline/gens/tradesimulation.py
Move the responsibility of wrapping the main simulation loop in the
ZiplineAPI context from the algorithm modules generator setup to the
main trade simulation loop, so that different methods of invoking loop
do not need to duplicate how the context is set.
To make it easier for internal implementation of handle_data to
transition off of calling the ZiplineAPI every bar, to only invoking the
context once per simulation.
> MAINT: Move ZiplineAPI context so that it always wraps main loop.

- tests/test_algorithm.py
- tests/test_assets.py
- tests/test_history.py
- tests/test_sources.py
- tests/test_transforms.py
- tests/test_transforms_talib.py
- zipline/algorithm.py
- zipline/assets/assets.py
- zipline/errors.py
- zipline/examples/pairtrade.py
- zipline/finance/trading.py
- zipline/sources/data_frame_source.py
- zipline/sources/test_source.py
- zipline/utils/factory.py
The identifier cache's usage was nearly identical to using lookup_generic, so this commit removes identifier-keyed caching and modifies anything that uses it.
> DEP: Removes unnecessary identifier_cache from asset_finder

- tests/test_assets.py
- zipline/assets/assets.py
- zipline/errors.py
Removes unused future lookup methods and consolidates everything into lookup_future_chain. Since the FutureChain object will have to hold a root symbol and dates, it should be responsible for cleaning the user input, so this is removed from the lookup method.
Adds knowledge date to future lookups. This makes our definition of valid contracts more flexible. We know about a contract if it starts trading by the knowledge date, and a contract is expired if it expires by the as_of_date.
Also fixes a bug with computing future chains, where contracts were not included in the chain on their expiration date.
> MAINT: Consolidates and improves future lookup methods

- zipline/algorithm.py
The datetime attribute of TradingAlgorithm was initially None, so calling get_datetime in initialize was causing an unhandled exception. This commit addresses that issue by calling on_dt_changed when initializing the TradingAlgorithm, to force all datetimes to be in line with the period_start.
> BUG: Sets the datetime of TradingAlgorithm initially to the simulation period start

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/test_algorithms.py
Changes two uses of lookup_generic to use the exact lookup in the context of each call.
1) TradingAlgorithm.symbol e.g. `order(symbol('FOO`), 100)`
2) SpecificEquitySource's use of the asset_finder to ensure that sids have been inserted into the asset finder.
The main goal here is to reduce some complexity before a larger wholesale change to the class, and bring usage of lookup_generic back down to just the consumers that require the multiple lookup.
> Remove uses of lookup_generic

- tests/test_assets.py
- zipline/assets/assets.py
Since most brokers will cease accepting trades by the notice date, contracts should not be considered valid after the notice date. This commit adjusts the lookup_future_chain method to consider all contracts with notice dates on or following the current date invalid.
> BUG: Determine valid future contracts with notice date

- tests/test_perf_tracking.py
- zipline/finance/performance/tracker.py
At the end of a call to update_dividends(), the perf tracker now performs a drop_duplicates on itself. Duplicates are identified by the 'sid' and 'pay_date' fields.
> BUG: Prevents duplicate dividends from being added to the perf tracker

- tests/test_algorithm.py
The lookup of future contract by individual symbol is a constraint on
incoming changes of changing how the asset finder stores data.
(i.e. the asset finder is changing so that there are separate tables for
both futures and equities.)
Since this lookup is not yet fully supported, we can add it back in on
top of the new asset finder.
@jfkirk this is the small reduction in features of the asset finder that we discussed in person. It should be possible to add the lookup back in, but since `symbol('AFUTURE')` is not yet used, it was easier to do the port of the underlying engine without supporting the feature, but shouldn't be too much work to add back in once that port is finished.
> TST: Remove test for lookup of future contract by symbol.

- tests/test_algorithm.py
- tests/test_assets.py
- zipline/algorithm.py
- zipline/assets/assets.py
- zipline/assets/futures.py
Implements a user facing futures API for zipline.
Adds the `FutureChain` object, which allows users to access future contracts though underlying queries to the AssetFinder. Adds the API function `future_chain`, which returns `FutureChain` objects.
> ENH: Futures API

- tests/test_algorithm.py
- tests/test_assets.py
- tests/test_perf_tracking.py
- zipline/assets/assets.py
- zipline/finance/trading.py
Attack the startup bottleneck of creating the asset finders caches for a
large universe, which was between 1-2 seconds on development and
production machines.
Instead, allow the AssetFinder to be passed a sqlite3 file that has
already been populated and then hydrate asset objects only when an
equity is referenced for the first time.
To create aforementioned sqlite3, create an AssetFinder with an db_path
and `create_table` set to True. If `create_table` is set to False, the
prepopulated data in the sqlite file found at db_path will be used.
Default behavior is to use an in memory database.
Behavior that changes:
- Fuzzy lookup now only works on one character, that character needs to be
specified at write/metadata consumption time, since the fuzzy lookup key
is created by dropping the …
> PERF: Change asset finder to be backed by sqlite3.

- tests/test_perf_tracking.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
This PR re-aligns the end-of-day logic between 'minute' and 'daily' emission modes in the PerformanceTracker. As part of this, the trade simulation is retooled to handle the perf packets.
> BUG: Aligns performance packet generation between minute and daily modes

- zipline/assets/assets.py
It references a self.cache attribute that no longer exists.
ping @jfkirk
> MAINT: Remove unused `assets` property.

- tests/test_assets.py
- zipline/assets/assets.py
If lookup_future_chain was provided with an as_of_date or knowledge date that was pandas.NaT, the query we were forming wasn't what we want. Instead, as_of_date, if not NaT, is used for knowledge_date, and if both are NaT, no date filtering is done in the query.
> BUG: Improves lookup_future_chain to handle NaT date args

- zipline/utils/cli.py
Remove default print_algo kwarg when called from IPython interface.
> BUG Regression caused by adding print_algo to args parser. 

- zipline/lib/adjusted_array.pyx
MSVC doesn't define NAN in math.h because they only implement C89.
See http://tdistler.com/2011/03/24/how-to-define-nan-not-a-number-on-windows.
> BUG: Use NAN from numpy.

- tests/modelling/test_engine.py
- zipline/assets/assets.py
- zipline/modelling/engine.py
This makes ordering with the returned assets much easier, and there's no
performance degradation for non-broadcasting operations on the Index.
Timings
-------
from random import sample
finder = AssetFinder(create_table=False, assets.db')
assets = load_8000_assets(finder)
AAPL = finder.retrieve_asset(24)
RANDOM_ASSETS = sample(assets, 500)
df = DataFrame(
index=assets,
data=np.random.randn(len(assets), 4),
columns=['a', 'b', 'c', 'd'],
)
df_int = DataFrame(
index=map(int, assets),
data=np.random.randn(len(assets), 4),
columns=['a', 'b', 'c', 'd'],
)
%timeit df.loc[24]
%timeit df_int.loc[24]
10000 loops, best of 3: 45.3 µs per loop
10000 loops, best of 3: 44.7 µs per loop
%timeit df.loc[AAPL]
%timeit df_int.loc[AAPL]
10000 loops, best of 3: 45.1 µs per loop
10000 loops, best of 3: 44.8 µs …
> ENH: Return asset-indexed DataFrame for data.factors.

- setup.py
- tests/modelling/base.py
- tests/modelling/test_factor.py
- tests/modelling/test_filter.py
- tests/modelling/test_term.py
- zipline/lib/rank.pyx
- zipline/modelling/engine.py
- zipline/modelling/factor/factor.py
- zipline/modelling/graph.py
- zipline/utils/test_utils.py
ENH: Improvements to rank()
======================
- Add an `ascending=True` keyword to `rank()`.
- Add `top(N)` and `bottom(N)` methods to Factor.  These return Filters
that pass the top and bottom N elements each day.
- Add a slightly faster path for rank(method='ordinal').  I had
originally thought the fast path was 2-3x faster because I had my
benchmark data axes flipped.  The actual speedup is only 5-10%, which
means it probably wasn't worth the effort to Cythonize...but we have a
slightly faster version now so we might as well use it.
- Refactor test_filter and test_factor to make it easier to implement
and test transformations on factors.  These tests now subclass
BaseFFCTestCase, which provides facilities for passing a dict of terms
and an "initial_workspace", the values for which …
> Top bottom filters

- tests/test_algorithm.py
- zipline/algorithm.py
Resolves https://github.com/quantopian/zipline/issues/632
@ssanderson I whipped this up as an easy example fix, but I'm thinking this is a good argument for moving the set_symbol_lookup method from Quantopian internal to Zipline. What do you think?
> BUG: Symbol look-up dates should not be dynamic

- zipline/utils/tradingcalendar.py
- zipline/utils/tradingcalendar_bmf.py
- zipline/utils/tradingcalendar_tse.py
Updated tradingcalendar_bmf and _tse to use the faster get_open_and_closes from tradingcalendar.
Before:
```
In [1]: %time import zipline.utils.tradingcalendar
CPU times: user 1.48 s, sys: 139 ms, total: 1.61 s
Wall time: 1.73 s
In [2]: %time import zipline.utils.tradingcalendar_bmf
CPU times: user 12.7 s, sys: 108 ms, total: 12.8 s
Wall time: 13.1 s
In [3]: %time import zipline.utils.tradingcalendar_tse
CPU times: user 12.1 s, sys: 108 ms, total: 12.2 s
Wall time: 12.4 s
```
After:
```
In [1]: %time import zipline.utils.tradingcalendar
CPU times: user 1.27 s, sys: 103 ms, total: 1.38 s
Wall time: 1.44 s
In [2]: %time import zipline.utils.tradingcalendar_bmf
CPU times: user 1.31 s, sys: 26.4 ms, total: 1.34 s
Wall time: 1.65 s
In [3]: %time import zipline.utils.tradingcalendar_tse
CPU …
```
> PERF: Re-use the faster get_open_and_closes from tradingcalendar

- tests/test_algorithm.py
- tests/test_assets.py
- zipline/assets/_assets.pyx
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
- zipline/finance/performance/position_tracker.py
This commit adds the auto_close_date property to Future objects, and it is calculated as the earliest of either the notice_date or expiration_date, or None if both of those dates are None.
@yankees714 This PR does not impact the AssetFinder's future chain logic at all. It may be appropriate for us to put in those changes in this PR once we figure out how we want it to look.
> ENH: Adds auto_close_date field to Future objects

- tests/test_assets.py
- zipline/assets/assets.py
Its more graceful for many applications to provide the Finder with a character on look-up, rather than provide a single fixed character on init.
> MAINT: AssetFinder now takes fuzzy characters on look-up, not init

- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
Only access position values once during stat calc.
Instead of calculating the position values for each stat result, e.g.
gross_exposure, net_liquidity etc. get the positions upfront and then
calculate the period and position stats in order, passing each value
explicitly to the ones that follow it in the dependency chain.
On the path for wiring up DataPortal, so that the upkeep of
last_sale_price can be removed in favor accessing those values on demand.
> Remove need for position values from lazy

- tests/test_algorithm.py
- tests/utils/test_utils.py
- zipline/algorithm.py
- zipline/finance/slippage.py
- zipline/gens/tradesimulation.py
- zipline/utils/test_utils.py
@jbredeche these patches enable more of test_algorithm, by using the old trade data to create DataPortal's, up to the point of discovering a bug in when orders are filled in test_volshare_slippage
> Enable test algorithm

- zipline/finance/trading.py
Specifically to allow the use case of creating an in-memory SQLite database and populating it with assets before creating the trading environment.
> ENH: Allow passing an existing engine to TradingEnvironment

- tests/test_algorithm.py
- tests/utils/test_utils.py
- zipline/finance/controls.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/risk/period.py
- zipline/gens/tradesimulation.py
- zipline/protocol.py
- zipline/test_algorithms.py
1) more tests passing
2) temporarily patched some stuff in position_tracker to get more tests passing (read from underlying source of truth instead of from the cache that wasn't being written to correctly)
3) fixed a serious bug in the tradesim loop.  have to handle blotter open orders bookkeeping before calling handle_data, so that the current state of open orders is correct.
4) added a temporary bandaid around beta calculation to make tests not blow up beta calculation.
> evening delivery

- tests/test_perf_tracking.py
- zipline/data/data_portal.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
- Add a 'dt' arg to get_current_price, so that the `current_day` member
does not need to be mutated when using just the perf period and
tracker.
- Change the frequency of the test data to daily from one second(?!)
- Create a data_portal in the test using sim_params which cover just the
range of the test data.
This makes it possible to at least run:
$ nosetests -x tests/test_perf_tracking.py:TestPositionPerformance
Albeit, with a failure in the pnl result.
TODO: Figure out why transactions are generated past the end of the
sim_params.
> Begin unlocking test_perf_tracking tests.

- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
Enable another perf_tracker test by using the period end as the dt on
more perf period calculations.
So that the data_portal 'current_day' does not need to be updated by the
tests that are just touching perf period and tracker.
This may lead the way to no longer maintaining 'current_day/dt' at all
in data_portal.
Enables:
$ nosetests -x tests/test_perf_tracking.py:TestPositionPerformance.test_long_position
test_long_position (tests.test_perf_tracking.TestPositionPerformance) ... ok
> Use period close for perf period calcs.

- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
Instead of calculating the position values for each stat result, e.g.
gross_exposure, net_liquidity etc.; get the positions upfront and then
calculate the period and position stats in order, passing each value
explicitly to the ones that follow it in the dependency chain.
e.g. the gross_value depends on the long_value and the short_value,
which called the position_values property for calculating both the
long_value and the short_value.
Removing the repeated calls to position_values (and
position_exposures) removes the need for the caching the last sale
prices and position amounts in separate vectors, since it is inexpensive
enough to read those values off of the positions dictionary held in the
position tracker.
This patch gives a small gain to ~500 sized portfolios, but the main
intent …
> MAINT: Only calc position values once per packet.

- tests/test_blotter.py
- zipline/algorithm.py
- zipline/finance/blotter.py
- zipline/gens/tradesimulation.py
- moved a lot of the order-related logic in tradesim's inner loop back into blotter
- added ```blotter.process_open_orders``` and removed ```blotter.process_trade``` and ```blotter.process_transactions```
- Blotter now takes slippage and commission in the constructor
- got blotter tests passing
- got rid of transact_partial
- ```algorithm```no longer stores slippage and commission, it passes them through (in ```set_slippage``` and ```set_commission```) to blotter
> move order handling back into blotter

- tests/test_perf_tracking.py
- zipline/utils/factory.py
These changes are spun out of the lazy-mainline branch.
- Remove create_random_simulation_parameters, since the tests on that branch which use a `DataPortal` use a more exactly sized sim_params created by `create_simulation_parameters`. Also, the randomness was causing some debug issues while working on changing the test_perf_tracking suite to use the new style data access.
- Make `calculate_results` take in a sim_params (and other) parameters, since on that branch some test_cases create their own sim_params, and thus can't be shared on the TestCase instance.
> Pre-lazy changes to test_perf_tracking

- zipline/assets/assets.py
surprised this wasn't caught by any of the tests. Should we add an extra one?
> BUG: missing comma in _asset_timestamp_fields

- zipline/finance/performance/tracker.py
Minute performance period is no longer used. The minute risk containers,
which had been removed, were the last usage of the minute performance
period.
> MAINT: Remove unused minute performance period.

- tests/test_assets.py
- zipline/assets/assets.py
PR to address two issues:
1) In the process of an earlier refactoring, the symbol names in `build_lookup_generic_cases()` were changed to be different, meaning we were no longer testing the relevant functionality of `lookup_generic`. The symbol names have been updated to once again be the same.
2) `_convert_asset_str_fields()` is no longer required. `_convert_asset_str_fields()` was added to address the fact that the unicode returned by SQLAlchemy was causing test failures, in particular `test_repr` and `test_root_symbols` failed because of the leading 'u' character in the unicode of python-2.x. Later it was pointed out that this method would behave differently in python 2 and 3, in particular the `str()` method would return bytes in python 2 and unicode in python 3. After investigating …
> Correctly tests for duplicate symbols and remove _convert_asset_str_fields

- zipline/assets/asset_writer.py
- zipline/assets/assets.py
- zipline/finance/trading.py
- zipline/pipeline/loaders/_adjustments.pyx
Speeds up the writing of all the assets to the assets.db, mostly by chunking the inserts in groups of 999 rows and by using vectorized computations for the date parsing.
Went from about 20s locally to about 5s.
> Write faster

- tests/pipeline/test_engine.py
- tests/pipeline/test_pipeline.py
- tests/pipeline/test_pipeline_algo.py
- zipline/algorithm.py
- zipline/pipeline/pipeline.py
`Pipeline()` no longer takes a name.
`attach_pipeline` now takes a name.
This is mainly for uniformity with how `Factors` and `Filters` are
handled.
> MAINT: Don't name pipelines.

- tests/test_perf_tracking.py
- zipline/finance/performance/position.py
- zipline/finance/performance/tracker.py
Call handle_splits in perf_tracker so that the cash adjustment is
applied to the perf period.
Also, provide adjusted prices to the data_portal, this piece will need
to be fixed when data_portal supports adjusted spot prices.
Fixes last remaining test in test_perf_tracking:
```
$ nosetests -x tests/test_perf_tracking.py:TestSplitPerformance
test_split_long_position (tests.test_perf_tracking.TestSplitPerformance) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.262s
OK
```
> Enable split handling in perf tracker.

- tests/test_algorithm.py
- tests/test_assets.py
- zipline/algorithm.py
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
cc @jfkirk @warren-oneill @yankees714 
Opening up this PR to discuss the addition of a `future_symbol()` API method and an internal `lookup_future_symbol()` method. 
I have added an index to the symbol column in the futures SQL table to speed up lookup times, and while I was at it I felt it that an SQL UNIQUE constraint would also be relevant since there should never be a collision of futures symbols. Note that this change initially caused one of the existing tests (which duplicates an entry in this column) to fail, so the test has been changed.
Update: the root symbols coming from our data provider are unique, and hence the symbols of individual contracts are unique. Hence it makes sense to impose the UNQIUE constraint.
Outstanding:
> Add lookup_future_symbol method and future_symbol API method

- tests/test_assets.py
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
Improves the query for futures contract to use the date that comes first in time (between `notice_date` and `expiration_date`) to determine contract validity. If one of these is missing, we'll use the other.
Also modifies the query to order the resulting contracts by their `expiration_date` if available, and to use their `notice_date` if not.
> MAINT: Improves handling of contract date info in lookup_future_chain

- tests/test_algorithm.py
- tests/test_assets.py
- tests/utils/test_preprocess.py
- zipline/algorithm.py
- zipline/assets/assets.py
- zipline/pipeline/pipeline.py
- zipline/utils/input_validation.py
- zipline/utils/preprocess.py
Previously we have capitalized input strings at different levels in
our code: in the user-facing API methods and in the asset finder.
This commit moves input string capitalization exclusively to the API
method to which the string was supplied. Specifically, the string is
capitalized by a preprocess API method decorator. The preprocess
decorator passes the input string to the newly defined
ensure_upper_case() method, which returns a TypeError if the argument
supplied is not of type str.
ensure_upper_case() is defined in a new file, zipline/utils/api_utils.py.
The existing expect_types() method is also moved there.
Various tests in tests/test_assets.py are modified to account for the
fact that the asset finder method lookup_symol() no longer capitalizes
its supplied argument.
> ENH: Coerce user input with API method decorator

- tests/data/test_us_equity_pricing.py
- tests/pipeline/test_pipeline_algo.py
- tests/pipeline/test_us_equity_pricing_loader.py
- zipline/data/us_equity_pricing.py
- zipline/pipeline/loaders/synthetic.py
To prepare for querying for payouts from SQLite, write the dividend
payouts to a new table dividend_payouts.
Change the expected columns of the passed dividend frame to contain the
payout data, and use that data to calculate the ratios (this moves
internal code that was calcualting the ratios into Zipline.)
The end result is that instead of just a dividends table with the
backward looking adjustment ratios, also write a dividend_payouts
table and a stock_dividend_payout table.
Replaces https://github.com/quantopian/zipline/pull/760 The difference is that this patch builds on top of the existing BcolzDailyBarReader.
> Add spot price and write adjustments

- tests/test_assets.py
- zipline/assets/assets.py
- zipline/assets/futures.py
The knowledge_date logic could lead to a situation where a futures are inserted to the middle of the chain unexpectedly, and that could lead to inconsistent behavior in trading. To avoid this, the knowledge_date logic has been removed.
It is not far-fetched to assume that all contracts are known at all points in a simulation, as futures follow regular schedules and there are few, if any, surprises.
> MAINT: Removes unneeded knowledge_date logic from future_chain

- tests/test_benchmark.py
- tests/test_perf_tracking.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/errors.py
- zipline/finance/performance/tracker.py
- zipline/finance/risk/cumulative.py
- zipline/gens/tradesimulation.py
- zipline/utils/test_utils.py
1) moved set_benchmark to Zipline
2) tradesim now pre-calculates the benchmark for the entire simulation,
either via downloaded market data, or via the specified sid
3) when possible, dataportal now uses only daily bars for history
> restore benchmark functionality

- tests/pipeline/test_engine.py
- zipline/pipeline/engine.py
I think restricting this was just paranoia.  This is required for use in live trading (where the start and end dates are the same on day 1).
(Opening PR to get travis to run)
> ENH: Allow pipelines to run with matching start/end dates

- zipline/finance/risk/period.py
In a sample backtest on my machine, this takes the final risk
calculations down from ~10 seconds to ~0.8 seconds.
> ENH: vectorize mean algorithm returns calculation

- .travis.yml
- etc/requirements_dev.txt
- setup.cfg
We already did this on travis.  Make it part of the normal test workflow
instead of a special case for travis.
> TEST: Run nosetests with timings.

- tests/test_algorithm.py
- zipline/finance/performance/tracker.py
- zipline/test_algorithms.py
Previously, when a transaction executed on a new bar, the transaction would adjust the position's last_trade_price field before the trade event would come through to calculate a cash flow. This caused missed cash flows on bars where transactions executed.
This fixes the issue by processing all transactions as trade events before processing them as transactions.
Addresses issue https://github.com/quantopian/zipline/issues/783
Uses commit from https://github.com/quantopian/zipline/pull/802
> Future flip fix

- tests/pipeline/test_frameload.py
- tests/pipeline/test_us_equity_pricing_loader.py
- zipline/pipeline/engine.py
- zipline/pipeline/loaders/blaze.py
- zipline/pipeline/loaders/equity_pricing_loader.py
- zipline/pipeline/loaders/frame.py
- zipline/pipeline/loaders/synthetic.py
Rather than a list that's ordered the same as the received columns.
Most nontrivial loaders were constructing dicts internally and then
converting back to lists, only to have the engine convert **back again**
into a dict.  This cuts out the middleman, and prevents bugs due to
incorrect ordering of the output arrays.
> MAINT: Make load_adjusted_array return a dict.

- zipline/assets/assets.py
Removes an unused arg from AssetFinder __init__
> MAINT: Removes unused allow_sid_assignment arg

- tests/test_algorithm.py
- zipline/algorithm.py
@elmq0022 , Since https://github.com/quantopian/zipline/pull/818 was facing conflicts and such, I rebased and fixed up your branch.  If this looks right to you, and tests pass, we can merge this one in.
> Pass analyze

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze.py
Fixes the case where a delta has an asof_date of the last requested
day and an index error would occur. This guards against this
specifically to make the delta be effective through the end of the
requested window.
Adds a test case for this behavior.
> BUG: Corrects an index error in blaze loader.

- zipline/protocol.py
- zipline/sources/test_source.py
When we cache the two methods on the instance, we need to update the initial_len to account for these untracked attributes in the dict.
Long term goal of removing `__len__` and `__contains__` from this object, it is not a container.
> Siddata caching affects len

- .travis.yml
- docs/source/whatsnew/0.8.4.txt
- setup.py
Instead, use those versions as lower bounds, so zipline
will work with packages that require other versions.
> BLD: Don't pin install requirements to exact versions

- docs/source/dev-doc-message.txt
- docs/source/index.rst
- docs/source/release-process.rst
- docs/source/whatsnew/0.8.4.txt
> DOC: document the release process

- docs/source/whatsnew/0.8.4.txt
- tests/test_history.py
- tests/utils/test_events.py
- zipline/utils/test_utils.py
The test output was so verbose I lost the tests in my terminal history. 
fixes: #832
> Test events too verbose

- docs/source/whatsnew/0.8.4.txt
- tests/test_assets.py
- zipline/assets/__init__.py
- zipline/assets/assets.py
Adding an extension to AssetFinder that caches all equities and overrides lookup_symbol to look up equities in the cache rather than in the database. This is meant to improve performance for anything that needs to lookup symbols for a large quantity of data.
I tested performance by doing a databazaar historical load of a 10k-line csv file. The load took about 2 minutes without caching, and about 3 seconds with caching.
> Equity caching

- .travis.yml
- docs/source/whatsnew/0.8.4.txt
- setup.cfg
The default of all the tests is pretty spammy.
> TST: Limit the timer report to just the 15 longest tests

- setup.cfg
- tests/pipeline/base.py
- tests/pipeline/test_blaze.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_pipeline_algo.py
- tests/test_assets.py
- zipline/algorithm.py
- zipline/assets/assets.py
- zipline/errors.py
- zipline/utils/control_flow.py
- zipline/utils/test_utils.py
Speed up `AssetFinder.retrieve_all` by doing one query instead of N.
- Removes the separate caches for equities and futures in favor of a single asset cache.
- We now cache the results of failed lookups.  This required unfortunate hacks in the `TradingAlgorithm` code that resolves assets from DataFrames.
- Reimplements single-asset lookups as a special case of multiple-asset lookups.
> Speedup retrieve all

- tests/utils/test_events.py
- zipline/pipeline/loaders/synthetic.py
Numpy warns about adding Python integers to uint32s and converting date
objects to datetime64.
> MAINT: Fix type coercion warnings with numpy 1.10.

- tests/pipeline/test_filter.py
- zipline/pipeline/expression.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/filter.py
It's very common to want to filter out NaN, inf, and -inf values from Factors.   This provides those operations as efficient builtins.
> ENH: Add isnan, notnan, and isfinite Factor methods.

- docs/source/appendix.rst
- docs/source/conf.py
- docs/source/releases.rst
- docs/source/whatsnew/0.8.4.txt
- zipline/assets/_assets.pyx
- zipline/assets/assets.py
- zipline/pipeline/pipeline.py
- Generate links to sourcecode via the Sphinx `viewcode` extension.
- Generate reference docs for Asset/Equity/Future, AssetFinder, and
AssetDBWriter.
- Generate reference docs for Pipeline API classes.
- Fix broken links and formatting issues in the 0.8.4 whatsnew.
- Use embedsignature in _assets.pyx so that the signatures of Asset
subclasses are inspectable.
> Docs improvements

- docs/source/whatsnew/0.8.4.txt
- tests/risk/test_risk_period.py
- zipline/finance/risk/period.py
Return NaN beta when missing benchmarks instead of raising LinAlgError
> Better handle missing benchmarks when calculating beta

- zipline/pipeline/factors/factor.py
nan* functions should get passed the actual array.
Also adds code-block directives to the docstring so that they get
highlighted by Sphinx as Python code.
> BUG: Fix typo in CustomFactor docstring.

- docs/source/whatsnew/0.8.4.txt
- tests/utils/test_sentinel.py
- zipline/utils/sentinel.py
> BUG: fix issues with sentinel

- tests/data/test_us_equity_pricing.py
- zipline/data/us_equity_pricing.py
In preparation for changes sketched out in https://github.com/quantopian/zipline/tree/configurable-first-date-lazy-mainline to the data portal.
Fixes a bug discovered with the volume values being off by 0.001. (Uncovered by lazy-mainline tests, and added a direct test in test_us_equity_pricing to check a volume field.)
Also, adds a -1 value, since data portal provides support for forward filling the price when the data is empty. The -1 should be a more stable check than checking for a 0.0-like value.
> Prepare spot_price for use by data portal.

- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
On the path of removing the need to hardcode/or pass around a 'first
trading day' value, use the calendar alreday embedded in the bcolz file
by the daily bar writer by using the daily bar reader's spot_price
method.
Removes one, but not all of the uses of the `FIRST_TRADING_DAY` value.
> REF: Use daily bar reader spot price in portal

- tests/test_benchmark.py
- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
- zipline/sources/benchmark_source.py
Use daily bar reader for daily history values in data portal, which
removes the need maintaining the first trading day in the data portal
class. The daily bar reader reads the calendar and asset starts from the
data written to the daily bar file. Using that data removes the need to
hard code the values in the data portal module, without having to pass
the values down to the data portal as parameters.
Removes daily pricing adjustment from data portal since that value is
handled by the daily bar reader.
Also, update how daily benchmarks (which uses the data_portal) handles
the case where the daily bar reader does not have data for the day
before the start of the backtest. (Since the reader throws an exception
when data is accessed before the calendar start.)
> ENH: Remove hard coding of first day in portal

- .gitignore
- docs/source/appendix.rst
- docs/source/whatsnew/0.8.4.txt
- tests/pipeline/test_factor.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/technical.py
I followed the RSI example in writing the test.  @ssanderson this is ready for you to look at when you get a chance.
> Adding a built in Returns factor to the pipeline API

- tests/test_dataportal.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/gens/sim_engine.pyx
- zipline/utils/test_utils.py
Remove the responsibility of calculating the minute dataset index from
the clock, i.e. the offset that is used for the 'fast' lookup path in
the bcolz data. Instead, the clock calculates all the minutes that the
clock will run through and provides a map of days to the minutes for
each day, and a map of minutes to which day the minute occurs on.
Those two maps are then used by the data_portal to do on demand
calculations of the dataset offset, instead of the clock calculating
the value every minute.
This is on the path to removing all hardcodings of the minute offsets,
by removing the hardcoding from the clock, with the data_portal taking
responsibility for the offsets (work that follows this will remove the
hardcoding from the data_portal.)
We may want to move the `minutes_by_day` and …
> REF: Remove data offset calc from clock.

- tests/finance/test_slippage.py
- tests/test_dataportal.py
- tests/test_finance.py
- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_minutes.py
- zipline/utils/test_utils.py
Instead of using a hardcoded start date for the calculations of the
index into the equity minute data, use a metadata file written by the
equity minute writer to set the first trading day of the equity minute
set.
To allow the data portal to be used with datasets with
different ranges. (i.e. not just the start date of 2002-01-02)
Also includes a change that requires both a futures and a equities path to the data portal, since the dataset start is equities specific.
> Allow different data set starts for minute data portal

- tests/finance/test_slippage.py
- tests/test_algorithm.py
- tests/test_blotter.py
- tests/test_finance.py
- tests/utils/test_events.py
- zipline/finance/commission.py
- zipline/finance/slippage.py
- zipline/test_algorithms.py
VolumeShareSlippage, by default, now lets you take out 2.5% of the bar's volume
(instead of 25%).
PerShare and PerTrade commission models now default to $1 minimum cost per trade.
PerShare defaults to 0.75 cents per share (previously 3 cents).
> DEV: Change some default values in the slippage and commission models.

- tests/finance/test_slippage.py
- tests/test_algorithm.py
- tests/test_dataportal.py
- tests/test_finance.py
- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_minutes.py
- zipline/utils/test_utils.py
Start down path of abstracting out the reader, so that other readers,
e.g. a DataFrame can be implemented. (Those implementations would
require more of the read logic to be moved from the DataPortal to the
reader.)
This is also required for an internal override of the start date on the
bcolz reader, which is why this change is so minimal.
> REF: Pass minute reader instead of path to portal

- zipline/finance/trading.py
Usage of `prev_environment` was removed by a previous commit,
dc964a7e7da7e975b22fabfe962d2210704c1d6b
> REF: Remove unused trading env member.

- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
- zipline/sources/benchmark_source.py
The main fix included fixes a regression on algorithms that only use a few equities:
PERF: Fix runtime regression on daily windows.
Re-using the pipeline infrastructure resulting in a bottleneck when
using a small number of stocks, where the read of the entire numpy
vector when only one stock was used was prohibitive.
Instead, base a solution off of @jbredeche's original solution, but
place the logic (at least the indexing logic into the DailyBcolzReader.)
We have an eye on making this eventually share code with pipeline, but
using the simpler non-shared solution for now.
Also, includes a small fix to a possible memory consumption issue when using spot_value discovered when investigating whether or not a cache of the numpy vector could be used in the bcolz daily bar reader.
> Lazy daily fix

- README.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/install.rst
- docs/source/whatsnew/0.8.4.txt
- etc/requirements_docs.txt
Adds an `Install` section to the Zipline docs where we can provide detailed installation instructions for various platforms and package managers.
> Install docs

- setup.py
- zipline/_protocol.pyx
- zipline/data/data_portal.py
- zipline/finance/performance/position_tracker.py
- zipline/gens/tradesimulation.py
- zipline/protocol.py
Make interface for get_spot_value more more precise by always requiring
the dt parameter, no longer sometimes using a current_dt value if set.
Still relies on a current_dt to be updated on data_portal from
tradesimulation, but that value is now accessed and passed more
explicitly by the bar data views.
> REF: Make dt required for spot value.

- tests/finance/test_slippage.py
- tests/serialization_cases.py
- tests/test_blotter.py
- tests/test_dataportal.py
- tests/test_finance.py
- tests/test_perf_tracking.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/finance/blotter.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/performance/tracker.py
- zipline/sources/benchmark_source.py
- zipline/utils/test_utils.py
So that the data_portal is not tied to solely daily or minute data
frequencies, make the get_spot_value method require a data frequency.
This change required that more classes held a reference to the
simulation's data frequency, e.g. the blotter and performance trackers.
Update serialization to reflect those changes.
> REF: Require data_frequency as spot_value param

- zipline/data/data_portal.py
- zipline/data/future_pricing.py
- zipline/data/us_equity_minutes.py
Moved from the `lazy-mainline` branch,
https://github.com/quantopian/zipline/pull/858
The intent of this patch to provide the basic class and readers
interfaces, developed on that branch, so that the use of creating the
object and opening paths etc. can be tested internally.
Additional changes beyond the lazy-mainline branch, addition of future
minute reader, and daily bar reader.
Also allow an argument of the future_daily_reader, though no such reader
yet exists.
It may be that future and equity readers share an interface, and a
further improvement would be providing an abstract base class.
co-author: @jbredeche <jean@quantopian.com>
Supercedes https://github.com/quantopian/zipline/pull/906
Differences from #906 
- `get_spot_value` interfaces were changed, on @ssanderson recommendation. …
> ENH: Add initial commit for DataPortal and readers

- tests/test_perf_tracking.py
- zipline/finance/performance/tracker.py
Refer to cumulative and todays performance explicitly instead of always
looping through.
The third value (minute) for which this was useful, has been removed.
Also, there are some actions where only cumulative may need application,
e.g. application of dividends. (However, this patch does not remove
dividend processing from todays performance, but opens up later patches
to make that distinction.)
Other Notes:
For compatibility with developments on the Q2.0 branch, https://github.com/quantopian/zipline/pull/858/files
Originally done here, https://github.com/quantopian/zipline/commit/db425553f5f60ce6e5b9a07db2afab7d0e5929bd
> MAINT: Remove perf_periods member.

- tests/serialization_cases.py
- tests/test_blotter.py
- tests/test_perf_tracking.py
- tests/test_versioning.py
- zipline/finance/blotter.py
- zipline/finance/order.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/slippage.py
- zipline/finance/transaction.py
- zipline/utils/test_utils.py
To reduce the edit distance of https://github.com/quantopian/zipline/pull/858 split out transactions and orders as was done on that branch.
The change cleans up the imports in some case, e.g. the position_tracker does not use slippage, but needs the transaction, so `from zipline.finance.transaction import Transaction` seems more semantically correct.
Also, having separate modules was found to have benefits for development iteration on each functionality.
> Move order and transaction classes

- tests/risk/test_risk_cumulative.py
- zipline/finance/performance/tracker.py
- zipline/finance/risk/cumulative.py
The only value used in the account is leverage, so pass the leverage
value directly.
Also, remove account from risk init, since it is not used.
> MAINT: Pass leverage instead of account to risk.

- tests/serialization_cases.py
- tests/test_perf_tracking.py
- zipline/algorithm.py
- zipline/finance/performance/period.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
Go back to current style of perf calculations, include the use of the
needs_update_flag.
We may still want to refactor, but the change is not needed for lazy
mode, so that refactoring can be done separately, if at all.
> MAINT: Undo change to perf calc interface.

- zipline/finance/performance/period.py
- zipline/finance/performance/position.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/performance/tracker.py
Change the method signatures for split and commission handling so that the sid and corresponding values are accepted instead of an event from which those values are accessed.
In preparation of lazy-mainline branch which removes the event and passes the coarse values down.
Based on 2b02aab120acf6429dae419bc12620ad1923b9ec and fc60804ff15865c772461fc847182ef8d5b31d4c from lazy-mainline branch.
> Make commission and split handling compatible with event removal

- setup.py
No functional change.
Done to improve diff with Q2.0 which adds more modules, and re-aligned the two modules changed here.
> STY: Align all build_ext definitions the same way.

- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
Instead of calling a function, where the only parameter is the tracker
object, make it a method, so that the snapshot of position tracker stats
can be more easily called as `pt.stats()`.
> MAINT: Make tracker stats a method.

- zipline/algorithm.py
- zipline/errors.py
These called the functions 'update_(commission|slippage) leading to
confusing messages when you called them post init.
> MAINT: fix error messages for set_(commission|slippage)

- tests/test_dataportal.py
- tests/test_history.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/data/us_equity_minutes.py
- zipline/gens/sim_engine.pyx
- zipline/gens/tradesimulation.py
ENH: Provide method for last trade dt.
Add a data_portal method `get_last_traded_dt` which the dt passed to the
method if there is a trade on that bar, or the previous dt with a trade
if there is no trade on the current dt.
This method will be used to proved a `.dt` lookup on SidView, but the
connection to the SidView is not made with this patch.
To implement the get_last_traded_dt a corresponding method
was added to the minute bar reader, with a supporting DatetimeIndex
which matches the data sets indices. Also, change
`_find_position_of_minute` to use the index, since the lookup is faster
than calculating a Timestamp and doing the offset calculation every
time. (As seen by the improvement in the ffill tests in test_dataportal.)
Also, change history tests to use a shared data_portal to …
> Lazy latest dt

- tests/test_algorithm.py
- tests/test_dataportal.py
- zipline/_protocol.pyx
- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
Build upon recently added `get_last_traded_dt` so that following algocode works again.
```
def handle_data(context, data):
data[sid(24)].dt
data[sid(24)].datetime
```
> Lazy wire up datetime

- docs/source/whatsnew/0.8.4.txt
- tests/pipeline/test_blaze.py
- tests/pipeline/test_term.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/loaders/blaze/earnings.py
- zipline/pipeline/loaders/earnings.py
Needed for the EarningsCalendar work we are doing
> ENH: Make datasets have subclass relationships

- tests/test_perf_tracking.py
- zipline/finance/slippage.py
- zipline/finance/transaction.py
Make the interface to the slippage `create_transaction` and
`process_order` as it is on master, so that there is less of a chance
for breaking existing algorithms that override slippage.
Create a TradeBar instance in slippage simulate, which holds the `price`
and `volume` for use by both process_order and create_transaction.
Other notes:
- This patch is in service of reducing the edit distance between master and lazy-mainline both in code and functionality.
- `trade_bar` is used in place of where `event` is on master. This aligns with the documentation of the function on https://www.quantopian.com/help.
- We may need to make TradeBar a dynamic object which can also access `open` and `close`, to support different models implemented by `process_order`. But that may not be in scope, since …
> Use master-alike create_transaction interface.

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_minutes.py
The value for latest_dt would search back until getting an index error
when there were no previous values.
Add test case in history with no previous values, and prevent forward
filling when the answer to latest dt is 'NaT'.
> BUG: Handle no previous values when ffilling.

- zipline/data/us_equity_minutes.py
Instead of iterating through the dt index and assigning each item
individually, use the array for assignment.
> MAINT: Use vector for minute price assignment.

- docs/source/whatsnew/0.8.4.txt
- zipline/utils/cli.py
When using the cli, assets would be added twice from yahoo because the items of the data panel are strings. By not passing them in the constructor, the run will put them into the asset finder.
> BUG: fix bug that caused symbols to be added to the asset finder twice

- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/performance/tracker.py
In preparation for the incoming changes which no longer push every bar
through the tradesimulation, remove the adjustment of the period's cash on
every pricing change of a held futures asset.
Instead hold the last sale price for each held future either:
- At the end of each peformance period update the last sale prices of
all held futures, so that the pnl for the next period uses values
derived from the cash difference between the end of the two periods.
- When a transaction is processed for the Future, so that the correct
amount is applied to each cash adjustment. (i.e. the cash adjustment
is reset on every change of amount of the Future being held, so that
multiple size and prices do not need to be tracked for the same asset.)
Also, remove now unused dict of payout calculation modifier, …
> MAINT: Futures cash adjustment on change and calc.

- tests/finance/test_slippage.py
- tests/test_blotter.py
- tests/test_finance.py
- tests/test_perf_tracking.py
- zipline/_protocol.pxd
- zipline/_protocol.pyx
- zipline/finance/blotter.py
- zipline/finance/slippage.py
- zipline/gens/tradesimulation.py
Fix bug where the SidView's asset was an integer.
Change BarData to take a simulation dt func instead of simulation
instance, since testing with new interface required creating a BarData
object to pass to slippage. (And it is easier to create a lambda that
provides a dt instead of instantiating or mocking out the
TradeSimulation object.)
> Allow OHLCV in slippage models.

- tests/pipeline/test_earnings.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/blaze/earnings.py
- zipline/pipeline/loaders/earnings.py
- zipline/pipeline/loaders/utils.py
- zipline/utils/memoize.py
- zipline/utils/test_utils.py
Lots of code in the earnings_calendar loader and tests can be shared with related loaders and datasets.
> MAINT: Move code to shared modules

- docs/source/whatsnew/0.8.4.txt
- tests/pipeline/test_blaze.py
- tests/utils/test_preprocess.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/blaze/earnings.py
- zipline/pipeline/loaders/utils.py
- zipline/utils/input_validation.py
This allows people to set their cutoff time to the time they will
actually execute 'before_trading_start'. Currently this is just passed
to the constructor of the loader; however, I would like to make this
managed by the algorithm simulation runner. This would help keep all of
the loaders in sync and lock 'before_trading_start's execution to the
time the data is queried for.
> allows users to specify the cutoff time for data query in blaze loaders

- tests/test_fetcher.py
- tests/test_history.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
- zipline/utils/test_utils.py
When getting a daily history window, we were using the asset's start date to figure out the first valid day for the history window. The problem is that the asset's start date can be before the first day in the daily bcolz file.
This PR makes it so that we use the max(asset start date, first trading day in bcolz file) to size history windows.  It also adds the property to the daily bcolz writer and reader.
> Use earliest trading day from bcolz readers to calculate valid history windows

- conda/README.md
- conda/cyordereddict/bld.bat
- conda/cyordereddict/build.sh
- conda/cyordereddict/meta.yaml
- conda/zipline/meta.yaml
- docs/source/whatsnew/0.8.4.txt
- setup.py
Allows us to build conda packages for the latest zipline and its dependencies.  Builds from local source instead of pypi, pulling in requirements from our requirements.txt.
Requires this change to conda-build: https://github.com/conda/conda-build/pull/717
> Conda source build

- tests/test_algorithm.py
- tests/test_events_through_risk.py
- tests/test_sources.py
- zipline/assets/assets.py
- zipline/gens/tradesimulation.py
- zipline/sources/data_frame_source.py
- zipline/test_algorithms.py
Currently it seems as though the data for expired futures is not removed from the info that gets sent to ```handle_data```. Over longer backtests this can result in the ```data``` variable becoming quite large and gives in a large reduction in performance esp when ```history``` is used.
cc @jfkirk @dhexus
> TST: tests removing of expired data and removes ffill in DataPanelSource

- docs/source/whatsnew/0.8.4.txt
- tests/test_perf_tracking.py
- zipline/finance/performance/period.py
Mea culpa. There was a typo that incorrectly assigned the 'total_positions_exposure' value to the 'total_positions_value' field.
This PR fixes that bug and adds tests to prevent a regression.
> BUG: Account object's total_position_value is incorrect

- docs/source/whatsnew/0.8.4.txt
- tests/test_assets.py
- zipline/algorithm.py
- zipline/assets/_assets.pyx
Enable comparison of an Asset to an int64 on 32-bit python
by supporting any Integral. We use a number of mappings keyed by
int64, which otherwise raise KeyErrors for Assets.
Also ensures `algo.current_sids()` returns a list of Assets, instead of identifiers.
For #650 and #926
> Asset KeyError

- etc/requirements_blaze.txt
- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
The blaze loader was not looking back far enough to forward fill values correctly.
We now run 1 query per column to make this happen.
Further work is to make ffill an optional feature for performance so that we don't need to do this and we can just slice out some time range.
Even more work (but probably better in the long run) is to bake the 'most recently known value' into a dense table. This would allow us to make a single query for the most recently known value on a single day and then concat that with the sparse data where we can ffill in memory or not. This would probably require us writing some helper that takes a sparse dataset and constructs this new table. I would not want to block this fix on that work though.
> Blaze loader forward fill fix

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
Fix a bug where creating a sid bcolz file when the containing directory
was already occupied by a sid caused an OSError on attempt of creating
the directory because it already existed.
e.g. if there were two sids, `1` and `2`. The paths would be
`00/00/000001.bcolz` and `00/00/000002.bcolz` which share the same
directory `00/00`.
Fixed by checking for directory existence before calling `makedirs`.
Add test coverage which exercises writing of sids that are siblings in
the sid directory structure.
> BUG: Fix OSError when creating sids that share dir

- zipline/data/minute_bars.py
Use the preexisting metadata method when instantiating the minute bar
reader.
An internal sublcass uses the `_get_metadata` method to setup data for
directories that have not used the new writer/reader interface.
(i.e. allows for reader creation when the metadata.json file does not
exist.)
> MAINT: Use metadata method for reader init.

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
So that consumers can write empty days worth of data, without needing
to construct a DataFrame with zero data force a write.
The internal loader uses `last_date_in_output_for_sid` to signify that
data has been attempted to be retrieved for all dates up until that, so
that when resuming a job those retrieval of data for those dates are not
re-attempted.
Also, used to make the write logic cleaneer, by making it only
necessary to create an array large enough for the given df.
> ENH: Add padding method to minute bars writer.

- tests/test_finance.py
- tests/test_perf_tracking.py
- zipline/finance/performance/position_tracker.py
We properly remove empty positions before the user calls `context.portfolio.positions`.
But until the user does that, the empty positions sit around.  And if other internal code needs a list of the positions, they get empty positions.
> BUG: Don't accumulate 0-sized positions.

- zipline/assets/assets.py
- zipline/data/us_equity_pricing.py
- zipline/utils/sqlite_utils.py
Chunk queries into groups of 998, because of a SQLite limitation on
query size.
Also, point assets module at factored out value and function.
> BUG: Allow more than 998 equities for dividends.

- tests/finance/test_slippage.py
- tests/test_perf_tracking.py
With the changes to create_transaction using the current_dt, the `test_perf_tracking` suite became incompatible, because of the change to using the `SidView` `current_dt` instead of the `Event`, the tests now need `BarData`.
Also, add test to `test_slippage` which checks for the case where a transaction would have been created on a bar with no trades (which was also fixed in a previous patch.)
> Tests for create_transaction using current_dt

- docs/source/whatsnew/0.8.4.txt
- tests/pipeline/test_numerical_expression.py
- zipline/pipeline/filters/filter.py
Fixes a bug where doing a boolean comparison between a non-numexpr
Filter and a NumExprFilter would fail because we don't implement
`__rand__` and `__ror__`.
> BUG: Add right-binding operators to NumExprFilter.

- docs/source/whatsnew/0.8.4.txt
- tests/pipeline/test_adjusted_array.py
- tests/pipeline/test_blaze.py
- tests/pipeline/test_column.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_term.py
- tests/test_test_utils.py
- zipline/errors.py
- zipline/lib/adjusted_array.py
- zipline/lib/rank.pyx
- zipline/pipeline/data/dataset.py
- zipline/pipeline/data/testing.py
- zipline/pipeline/engine.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/__init__.py
- zipline/pipeline/filters/filter.py
- zipline/pipeline/filters/latest.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/equity_pricing_loader.py
- zipline/pipeline/loaders/frame.py
- zipline/pipeline/loaders/synthetic.py
- zipline/pipeline/loaders/testing.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
- zipline/utils/numpy_utils.py
- zipline/utils/test_utils.py
Adds support for specifying `missing_values` to pipeline `Term`s, and makes `BoundColumn.latest` return a Filter instead of a Factor for expressions of dtype `bool`.
This also removes all implicit coercion behavior from `AdjustedArray`.  PipelineLoaders are now responsible for ensuring that loaded values match the dtypes of requested columns.
@llllllllll tagging you on this since most of the changes here are actually in the `BlazeLoader` and its tests.
> Pipeline missing values

- conda/logbook/meta.yaml
- etc/requirements.txt
- zipline/examples/olmar.py
Upgrade Logbook to 0.12.5. This required changing a usage of
`logbook.NullHandler()` which passed `bubble=True`, since
`NullHandler` no longer supports the `bubble` argument.
> MAINT: Upgrade Logbook version

- .travis.yml
Round 1: np 1.9 and np 1.10 jobs will all run with empty caches, each will populate a subdirectory and update the travis cache, last one wins - let's say 1.9.
Round 2: All jobs will run, but the cache will only have 1.9, which will speed up only those jobs. 1.10 will be slower, but will now add its data to the cache and become the last to upload it, now with both 1.9 and 1.10.
Round 3: All jobs can use the cache for a performance gain during installation.
> BLD: Use separate travis pip cache subdirs per numpy version

- .gitignore
- etc/requirements_blaze.txt
- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
Make less calls to compute to reduce IO bottlenecks when the expression is bound to a remote data source.
The update to blaze makes `least` work correctly on `pd.Timestamp`: https://github.com/blaze/blaze/pull/1409
> condense the blaze query

- zipline/data/data_portal.py
Noticed in the case where the window function is used to fetch the
minutes for the current day to update the last slot in a '1d' history
window.
Further improvement can be made on this by prefetching the day's data
into a Float64Window instead and then iteratively getting the latest
value.
On local machine this cuts the time per day for an algo which does 3
bars of '1d' history for 6 algos by about 33%. (0.5 seconds -> 0.35 seconds)
> PERF: If the window is one day, no adjustments.

- docs/source/whatsnew/0.8.4.txt
- zipline/transforms/batch_transform.py
- zipline/utils/deprecate.py
Deprecating for now, before we rewrite the sample pairtrade algo to use history and then kill batch altogether.
> Deprecate batch transform

- tests/pipeline/base.py
- tests/pipeline/test_buyback_auth.py
- tests/pipeline/test_earnings.py
- tests/pipeline/test_events.py
importing from `test` only works if the cwd is the zipline root. This makes this relative and moves the mixin into pipeline/base.py so we are not importing from a test.
> TST: use rel imports from tests

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_loader.py
Fix a bug when history is called in a backtest with a start date near
the first trading day of the daily bars file, where load_raw_arrays
would hit a key error because data was requested which preceded dates
stored in the daily bar reader's calendar.
In the case where the first day is before the daily bar start, truncate
the query to days in the daily bar readers range, and then prepend nans.
> BUG: Fix history crash at data start.

- docs/source/whatsnew/0.8.5.txt
- tests/pipeline/test_buyback_auth.py
- zipline/pipeline/data/buyback_auth.py
- zipline/pipeline/factors/events.py
- zipline/pipeline/loaders/buyback_auth.py
Some of the variables related to buyback auth are unnecessarily long; this PR simplifies them.
> MAINT: rename variables to simplify.

- tests/pipeline/test_term.py
- zipline/errors.py
- zipline/pipeline/classifier.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/engine.py
- zipline/pipeline/expression.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/filter.py
- zipline/pipeline/graph.py
- zipline/pipeline/loaders/blaze/buyback_auth.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/blaze/earnings.py
- zipline/pipeline/loaders/blaze/events.py
- zipline/pipeline/term.py
- zipline/pipeline/visualize.py
Replace it by distinguishing between "Loadable" and "Computable".
This is useful because it's now  possible to write computable terms that
don't require  any inputs  (e.g. an `Always`  filter or  an `Everything`
classifier).
> MAINT: Remove notion of "atomic" pipeline terms.

- tests/test_finance.py
- zipline/finance/trading.py
Allow creation of TradingEnvironment to specify a minimum date, so that
trading days, market opens, etc. can trimmed to a range more relevant to
the backtest.
This changes is with an eye towards storing all market minutes in the
trading environment, where storing values for much more than the
simulation range starts to become more costly.
> ENH: Add min date to TradingEnvironment.

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/utils/test_utils.py
This branch addresses an [issue](https://github.com/quantopian/qexec/issues/9196) in which running Pipeline for certain premium datasets for certain date ranges results in a KeyError because there are sids that exist in the databazaar deltas table but that are not returned by the pipeline engine. This fix filters out those sids and logs a message that keeps track of which sids are not found.
> Ignore missing deltas in pipeline

- tests/utils/test_events.py
- zipline/utils/events.py
Fixes schedule_function's handling of after_open and before_close dates. 
We now look at *this* period start and period end, instead of the next period start and period end. The next period start and period end are implicitly creating state(when we call a rule for the first time, when its `_next_period_start` is None, and then again when its `_next_period_start `has a value). 
As a result we were seeing the following impure behaviour:
```python
In [33]: bc.should_trigger(test_close_time2, env)
Out[33]: True
In [34]: bc.should_trigger(test_close_time2, env)
Out[34]: False
In [35]: bc.should_trigger(test_close_time2, env)
Out[35]: False
```
because of the messed up state, we weren't correctly keeping track of where we were, which led to messed up behaviour with `schedule_function`. We avoid …
> BUG: Fixes incorrect behaviour in market open and close

- tests/test_algorithm.py
- zipline/_protocol.pyx
- zipline/test_algorithms.py
Cython returns unhelpful errors when you pass unexpected keywords.
Wrap relevant BarData methods with a decorator that checks the
keywords and returns a better error if needed.
> FIX: Make unexpected keyword arguments return meaningful errors

- tests/test_perf_tracking.py
- zipline/finance/performance/position_tracker.py
If there were multiple splits that affected our holdings at the same
time, the leftover cash wasn’t properly being summed.
for https://github.com/quantopian/qexec/issues/9353
> BUG: proper accounting of leftover_cash for multiple concurrent splits

- tests/resources/fetcher_inputs/fetcher_test_data.py
- tests/test_algorithm.py
- tests/test_api_shim.py
- tests/test_fetcher.py
- zipline/_protocol.pyx
- zipline/finance/controls.py
- zipline/test_algorithms.py
Updated the tests that were using the old data API. After discussion with @jbredeche a couple of the tests that have use cases we don't really support anymore(`test_get_sid`, for example), have been killed. 
The PR itself is still WIP because I'm adding another commit that tests that the old and new data APIs return identical results for OHLCVP, but this commit itself is ready to be looked at.
UPDATE: Added a test that verifies old and new data APIs both hit the same code path.
> TST: Update tests to use new data API

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/errors.py
- zipline/finance/trading.py
Also, limit history to dates in trading enviroment.
The main goal of this patch is to speed up repeated history calls by
indexing into a pre-calculated market minute window for all minutes in
the TradingEnvironment's range, instead of calculating the market minute
window every minute.
However after that change, history windows which went before the 'first
trading day' known to the environment would attempt to reach back into
'unknown' territory/dates (i.e. the market minutes for the prepending of
pre-data set days would not be calculated when the TradingEnvironment's
date range is limited to trading days.)
Instead of handling that case, and to simplify the behavior of history
windows, (and not report a window with 'nans', when there were real
world trades.), when the history window goes …
> PERF: Use precalc market minutes.

- tests/test_blotter.py
- zipline/finance/blotter.py
In execute_cancel_policy, make a copy of the orders list, so it
doesn't get mutated as we cancel orders
> BUG: Don't mutate open orders list as we cancel

- tests/test_perf_tracking.py
- zipline/finance/performance/position.py
To calculate our position values / exposures, we multiply together the corresponding `amounts`, `last_sale_prices` and `multipliers`. This assumes that these three iterables are in the same order. In fact this is not necessarily the case, because while `multipliers` are stored as an `OrderedDict`, the `amounts` and `last_sale_prices` are lists which are populated by iterating over a regular `dict` (actually a subclass, called `positiondict`), and we cannot be sure of the order in which keys/values are stored within in this `dict`. In particular, the order of this `dict` may change in arbitrary ways when we call `.update()` on it, whereas the ordering of existing elements in the `OrderedDict`s will not change.
We have not previously seen this issue because in the case equities-only …
> BUG: Ensure consistent ordering of amounts, prices & multipliers

- tests/pipeline/base.py
- tests/pipeline/test_buyback_auth.py
- tests/pipeline/test_earnings.py
- zipline/pipeline/loaders/events.py
- zipline/pipeline/loaders/utils.py
This PR fixes the way buyback auth previous dates/values are computed and the way it is tested. Previously, the computations and tests were the same as for earnings calendar, but it doesn't make sense for them to be the same because while earnings calendar announcement dates are for the future, buyback auth announcement dates are always for some number ( > 0) of days before the current day. This means that for calculating previously known dates/values, the timestamp (knowledge date) should be used, rather than the event date, because we won't actually know about the event on the same day that it happens. This also means that most of the test cases for earnings calendar don't apply to buyback auth.
> Fix buyback auth tests in pipeline

- tests/test_algorithm.py
- tests/test_bar_data.py
- tests/test_history.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/finance/trading.py
- zipline/gens/tradesimulation.py
Give responsibility of altering datetimes on the fly to `BarData`, so that `DataPortal` is unsullied.
> DEV: Make all the data.* methods work for non-market-minutes by using the last market close

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
Add a method to minute bar reader which returns the OHLCV for all
requested fields for a list assets over the specified start and end
minutes.
Initial usage is intended for use by a loader which consumes minute bar
data to resample into daily bars, but may also be used when aggregating
minute data during '1d' history calls in Q2.0.
This iteration does not include including of early closes.
> ENH: Unadjusted window data for minute bars.

- setup.py
- zipline/data/_minute_bar_internal.pyx
- zipline/data/minute_bars.py
Moving a bunch of arithmetic-heavy work to Cython takes this algorithm, on my machine (in qprof) from ~46 seconds to ~29 seconds:
```
def initialize(context):
pass
def before_trading_start(context, data):
data.current(sid(24), "high")
def handle_data(context, data):
data.current(sid(24), "price")
```
(2012-01-04 to 2014-01-03, 1M, minutely)
the difference is much more pronounced with even more illiquid securities.  I'll have more data tomorrow.
> ENH: Speedups by moving computation-heavy things to Cython

- tests/resources/fetcher_inputs/fetcher_test_data.py
- tests/test_fetcher.py
- zipline/_protocol.pyx
- zipline/data/data_portal.py
For every fetcher source, take the last signal on a given day for
a given asset or data source as the signal for the entire day
> FIX: Rollback granularity on fetcher sources to daily

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/errors.py
- zipline/finance/trading.py
Unreverts #1040 
Also, make env.market_minutes lazy so that the memory and CPU cost is not hit in contexts that do not use the minutes.
> Lazy prevent history before trading start

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
Fix the following behavior for the last slot in history with a '1d'
freq.
- open 
- old
Always used the open on the first minute, (9:31)
- fix
Uses first non-nan open.
- high
- old
The existence of any nan from market open to dt would propagate and
make the result nan.
- fix
nans no longer affect high, unless there are only nans between
market open and given dt
- low
- old
The existence of any nan from market open to dt would propagate and
make the result nan.
- fix
nans no longer affect low, unless there are only nans between
market open and given dt
- close
- old
The close at the given dt was always used. If the close was a nan at
that dt, a nan would be returned.
- fix
The close at the given dt, unless that a value is a nan; in that
case the most recent non-nan value is returned.
This …
> BUG: Fix '1d' history for last day in slot.

- tests/finance/test_slippage.py
- zipline/finance/order.py
- zipline/finance/slippage.py
- zipline/finance/transaction.py
`process_order` now takes BarData and the Order object and
returns a tuple of (execution_price, execution_volume).  Our
internal code is now responsible for creating the transaction.
Also, enforce that Orders and Transactions use Assets, not ints.
> DEV: Clean up slippage API.

- .github/ISSUE_TEMPLATE.md
due to rounding error the bitness function gave the correct result on 64b but not on 32b
> MAINT: fix bug in issue template

- tests/test_algorithm.py
- tests/test_bar_data.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/testing/core.py
There was an off-by-one bug that was erroneously preventing you from
ordering an asset on its last trading day.
There’s a bunch we still need to do to solidy this - these date checks
don’t apply to the simple `order` method, etc.  I wanted to get this fix in first.
> FIX: Allow order_target_percent, order_target_value, etc on an asset's last day

- tests/test_fetcher.py
So we don't have the issues with `nose_gevented_multiprocess`.
> TST: Fix fetcher tests to stop and reset responses in teardown

- docs/source/whatsnew/0.8.5.txt
- tests/pipeline/test_numerical_expression.py
- zipline/pipeline/expression.py
NumericalExpressions fail to merge if one of them has >10 inputs.
> run_pipeline failing given too many factors

- tests/test_history.py
- zipline/data/data_portal.py
The recursion on finding the last close was incorrectly using the array
returned by the close method instead of demoting it to scalar. When this
value was appended to the full close results return arrays with bizarre
shapes, e.g. `(2, 1, 1, 1, 1, 1)`, because a list built of scalars and
lists was passed to the array constructor.
Change daily aggregrator test suite to test the DailyHistoryAggregator
directly instead of routing through data portal, since the assignment of
the values when using a bar count of 1 was papering over the unexpected
shape.
Add a check on returned values in tests that the return is a `Real` to
prevent regression on the assignment of an array when a
Credit to @aliang for identifying root cause.
> BUG: Fix accidental array during recursion.

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
Write arrays representing corresponding market opens and market closes,
which will eventually replace the `minute_index` field.
The market closes are being added for incoming work on another branch
which will use the market closes to generate a list of non-market
minutes to filter out when returning data from `unadjusted_window`.
> MAINT: Write open and closes for minute bar format

- etc/requirements.txt
- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
Use market closes in minute reader to filter out non-market minutes, by
creating a 'blacklist' of minutes between the early close and would be
market close if the day were regular.
Added because the incoming minute history loader needs an interface to
query for the exact market minutes in a range from the reader.
> ENH: Filter unadjusted window to market minutes.

- tests/test_algorithm.py
- tests/test_api_shim.py
- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/minute_bars.py
- zipline/data/us_equity_loader.py
- zipline/data/us_equity_pricing.py
Factor out USEquityHistoryLoader into a base class which can be
overridden to support daily or minute history.
Use the minute version of the history loader in data portal minute
equity window history calls, in the same manner that the daily history
loader is used to pre-fetch history windows and apply adjustments as the
window is rolled.
Change some test case sim params so that the tests are started far
enough from the dataset start so that history calls can be made.
> MAINT: Provide prefetch history loader for 1m.

- docs/source/whatsnew/0.8.5.txt
- zipline/pipeline/data/__init__.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/events.py
- zipline/pipeline/loaders/__init__.py
- zipline/pipeline/loaders/blaze/__init__.py
- zipline/pipeline/loaders/blaze/buyback_auth.py
- zipline/pipeline/loaders/blaze/dividends.py
- zipline/pipeline/loaders/blaze/earnings.py
- zipline/pipeline/loaders/buyback_auth.py
- zipline/pipeline/loaders/dividends.py
- zipline/pipeline/loaders/earnings.py
Adds dividends data/loaders to inits.
> MAINT: add dividends datasets to inits

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
np.array.astype can not be relied upon to convert nan's reliably to 0
Fix by calling nan_to_num on the float arrays before converting to
uint32.
> BUG: Prevent writing int max instead of nan.

- tests/utils/test_events.py
- zipline/utils/events.py
Small bugfix for when we tried to call week_start.should_trigger(trading_days[0]). 
@jbredeche mind taking a look?
> BUG: Stop blowing up when trying to do week_start with trading day zero

- tests/data/test_minute_bars.py
- tests/test_algorithm.py
- zipline/data/_minute_bar_internal.pyx
- zipline/data/minute_bars.py
- non trading minutes get adjusted to the last trading minute in the minute bar reader
- tests for this new minute bar reader indexing
- tests that calls to portfolio and account in BTS (non trading minute), are getting the right values
> BUG: Make minute bar reader adjust for non trading minutes

- .travis.yml
- setup.cfg
Add --with-coverage flag to Travis, so that reports are generated during
continuous integration, but not during every invocation when running
tests locally.
> TST: Remove coverage from default nose config.

- zipline/testing/fixtures.py
Makes it harder to call the wrong enter_context or add_callback function. We do not need checks going the other way because it will be calling an unbound method which will fail with a type error.
> TST: adds guards for calling class methods in instance setup

- tests/utils/test_events.py
- zipline/utils/events.py
Previously, in Q1, a `time_rule` triggered when the dt specified has passed. This was to accommodate the possibility that `handle_data` would not run if there was no new event or data for a particular bar. In Q2, we necessarily check every bar to see if `time_rule` triggers. Thus, we should check that the current dt equals the rule dt.
As a result, in the case of a live algo starting mid-day, any function scheduled for earlier that day will not run. For example:
- live algo starts at 2 pm and has a function with a time rule of 1 hr after open --> function will not run on first day
- live algo starts at 2 pm and has a function with a date rule of every day (no time rule means it runs at market open) --> function will not run on first day
> FIX: time_rules should trigger only at dt specified

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
When the dts and length of cols are mismatched the writer behaves in
unintended ways. e.g. in a case where a consumer passed dts which had
minutes with no trades removed, but regular (market minute for day)
sized arrays for the data with `0`'s on minutes without trades, the non
trade minutes from cols are written to slots in the output where a trade
is intended.
Protect against this misuse by checking that all lengths are equal when
using the `write_cols` method.
Make a separate `_write_cols` method for use by both `write_cols` and
`write`, since the `write` method which takes a DataFrame has the
matched input length enforced by the DataFrame.
> BUG: Ensure matched input length to minute writer.

- tests/pipeline/test_engine.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/engine.py
- zipline/pipeline/graph.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
When a custom factor is passed a mask, it computes only over the assets for which the mask returns `True`. This allows computationally expensive factors to not have to compute over an entire universe of stocks.
> Pass a mask (filter) to custom factors

- tests/test_history.py
- zipline/data/data_portal.py
In before_trading_start, history needs to call `DataPortal.get_adjustments`, and that method wasn’t correctly checking for iterables.
> BUG: bar_data.history too limiting on iterable types

- tests/test_algorithm.py
- zipline/finance/blotter.py
We were logging partially filled sells as completely unfilled, which is incorrect.
> BUG: Properly log partially filled sell orders.

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
The intervals are returned as a set, so order is not guaranteed,
which becomes exposed when reading windows which span multiple years.
The deletion of values from the regular sized minute array assumes that
intervals can be reversed to delete the array from the back.
> BUG: Enforce sorted order on minutes to delete.

- zipline/data/data_portal.py
The minute history loader caching was incorrectly mimicking the daily
history loader caching.
Where caching the adjusted array on the last dt helps an access pattern
of repeated calling history windows on the same day (which has an end_dt
of the previous day), with minute windows the end dt is always moving
forward, so the cached values are seldom used. (Would only be used if
`history` was called with same parameters twice on the same simulation time.)
> BUG/PERF: Remove extra minute bar loader cache.

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/test_algorithms.py
`handle_data` is no longer strictly needed, as one can use `schedule_function` to define trading logic that doesn't need to happen every minute.
> ENH: make handle_data optional

- tests/test_algorithm.py
- zipline/_protocol.pyx
- zipline/data/data_portal.py
- zipline/test_algorithms.py
Ensures that for methods `current`, `history`, `can_trade` and `is_stale`:
- assets must be an Asset object or str (or iterable of either) for `current` and `history` but only Asset (or iterable of Asset) for the other two
- fields must be str or iterable or str
- bar_count must be int
- frequency must be str
This solution is not particularly elegant, but we have a new decorator `assert_types` that takes the expected types, and checks that the args passed to the function are of the correct type
> FIX: Check types of args passed to api methods on data

- zipline/data/_minute_bar_internal.pyx
- zipline/data/minute_bars.py
The main change in this PR is:
PERF: Remove memoization from minute bar position.
Instead of using the `remember_last` memoization on all calls to
`_find_position_of_minute`, add an instance local cache which is only
used by the `get_value` call. The `get_value` call is very hot, so any
extra overhead (e.g. creating the WeakArgs on every invocation) becomes
costly. The current usage `get_value` also has the property that it is
called with monotonically increasing, but with a high repeat count on
each value. (A further improvement could making a `get_value` which
supports being used by many sids, for use by the update portfolio
positions.)
The caching is not done at the `_find_position_of_minute_level` because
`unadjusted_window` always uses two positions on the tape (start and end
of …
> Fix regression on retrieval of minute positions.

- docs/source/whatsnew/0.9.1.txt
- tests/utils/test_cache.py
- zipline/utils/cache.py
Add a cache interface which supports expirable entries with a changeable
backend for the cache into which they are entered.
The default cache is a `dict` but could swapped for
`cachetools.LRUCache` or any other cache which supports `__get__`,
`__set__`, and `__del__`.
So that consumers can change the use of `CachedObjects` stored in a
cache from:
```
self._cache = {}
...
try:
obj = self._cache[key]
try:
return obj.unwrap(dt)
except Expired:
pass
except KeyError:
pass
...
self._cache[key] = CachedObject(value, new_expiration)
```
to:
```
self._cache = ExpiringCache(LRUCache(maxsize=6))
...
try:
return self._cache.get(key, dt)
except KeyError:
...
self._cache.set(key, value, new_expiration)
```
> ENH: Add expiring cache.

- conda/cachetools/bld.bat
- conda/cachetools/build.sh
- conda/cachetools/meta.yaml
- etc/requirements.txt
- zipline/data/us_equity_loader.py
BUG: Add limit to memory growth on sliding windows
Add a cap of 5 sliding windows (one per OHCLV column) to the history
loader's cache of sliding windos.
This prevents unbounded growth on algorithms that call history with a
highly varied list of equities.
To follow is splitting the cache up by column and by sid, so that the
loader does not re-prefetch sids which have already been read with
sufficient data; however this patch is enough to fix the issue where an
algo with high rotation can add up a megabyte per day of memory on
algorithms which rotate on a 5% dollar volume pipeline. With this cap
those algorithms have more plateaus with regard to memory consumption.
This patch requires new dependency of `cachetools` library.
Also, add cachetools recipe (via @richafrank )
> Limit leak in us equity loader on stock rotation

- tests/test_history.py
- zipline/data/us_equity_loader.py
- zipline/data/us_equity_pricing.py
Fix a bug where if history were called with assets `[1, 2]` and then
subsequently, `[2, 1]`, the loader would return the cached array in
order for `[1, 2]`.
Instead cache an AdjustedArray for each asset, then when a history
window is requested, check if each asset has a sufficient cache, and if
not then read values for the assets which are missing or need to be
refreshed.
An added benefit of this change is that if a subsequent call to history
has a smaller number of assets than the previous, no new data needs to
be read from disk. e.g. a call with assets `[1, 2, 3]` and then `[1, 2]`
would use the cached values for `1` and `2` from the first call.
Conversely, if the second call has more assets, then only the data for
the new assets needs to be retrieved. e.g. a history with `[1, 2]`, then …
> BUG: Prevent out of order history arrays.

- zipline/data/data_portal.py
in an algo that calls `get_spot_value` 808k times over 2 years (where zero times are for fetcher values), decreases total time spent in that method by 94%.
> PERF: do work later, when needed.

- tests/utils/test_events.py
- zipline/utils/events.py
A previous commit (1ee3c5f04968ab2b1ab4ff334c1cdefe487e7927), changed the schedule function week rules so that every time it triggers, we recalculate the next trigger. As a result, the rule only triggers once a week (on the first bar of the day it's supposed to trigger). This works if we only have a week rule, but it won't work if we combine a week and time rule, and the time rule triggers after the first bar of the day, because the week rule keeps getting recalculated before the time rule triggers.
So, we revert back to having the week rule trigger for the entire day, but recalculate based on the last triggered date, as opposed to the date after the last trigger
> BUG: Week rule plus time rule doesn't work

- zipline/finance/order.py
for a 2year backtest that places an order every minute (= ~205k orders), this takes max memory usage from 250MB to 163MB.
> Use __slots__ in Order object to save memory

- docs/source/whatsnew/1.0.0.txt
- tests/pipeline/test_engine.py
- tests/pipeline/test_term.py
- zipline/errors.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
Add an optional `outputs` parameter to CustomFactor allowing multiple outputs to be computed and returned from a single CustomFactor, each output of which is itself a Factor.
> Support multiple outputs for custom factors

- tests/resources/fetcher_inputs/fetcher_test_data.py
- tests/test_fetcher.py
- zipline/data/data_portal.py
- zipline/testing/core.py
We were trying to use the previous day in before_trading_start because
we were looking for the previous market minute, then normalizing it.  That's
no longer the case, as we want to use today's date for fetcher lookups
in before_trading_start.
Also refactored a bit how dataportal determines if a query should be
routed to the fetcher data structures.
> BUG: Fetcher wasn't working properly in `before_trading_start`.

- tests/data/test_us_equity_pricing.py
- zipline/data/_equities.pyx
- zipline/data/us_equity_pricing.py
- zipline/testing/fixtures.py
The BcolzDailyBarReader was optimized for the pipeline case of reading
all assets at once.
Now that the reader is also used to support daily history the case of
reading a data for a small number of assets is more common, particularly
in algorithms that use the history API which have a high rotation of
assets (e.g. an algorithm which pipeline uses to set the active
universe)
Remove the bottleneck in reading a small number of assets by
conditionally reading the slice for each asset from the carray, instead
of reading the data for all equities and then indexing into that full
array. On a certain number of assets, it is still better to read all the
data at once. On the Quantopian dataset, which holds data for 20000
about for the last 10 years of equity data (where not all equities trade
over …
> PERF: Improve read time for smaller num of assets.

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/test_algorithms.py
- zipline/utils/input_validation.py
Let the user to know to use asset= instead
> DEV: Better error message for sid= in get_open_orders

- tests/test_algorithm.py
- zipline/finance/performance/position_tracker.py
- zipline/protocol.py
- zipline/test_algorithms.py
Previously, whenever we try to access a missing value on the Positions
dict, we return a default Position and save it to the dict. Instead,
just return the Position
> BUG: Don't save empty positions when user access non-existent position

- tests/test_algorithm.py
- zipline/sources/benchmark_source.py
- zipline/test_algorithms.py
When we run a simulation that starts and ends on the same weekend,
return an empty series for the benchmark so as to not crash
> FIX: Crashing on calculating benchmarking when no trading days

- tests/test_benchmark.py
- zipline/sources/benchmark_source.py
Should be '...does not exist on self.trading_days[-1]...' not
self.trading_days[0]
> FIX: Error message for BenchmarkAssetNotAvailableTooLate is wrong

- tests/test_algorithm.py
- tests/test_perf_tracking.py
- zipline/finance/performance/tracker.py
- zipline/gens/sim_engine.pyx
- zipline/gens/tradesimulation.py
Refactor AlgorithmSimulator so that DAY_END is emitted for both
minute and daily emission, and that handling of end-of-minute
and end-of-day is separated
> BUG: DAY_END action not emitted during minute emission

- tests/test_panel_daily_bar_reader.py
- zipline/data/us_equity_pricing.py
- zipline/utils/input_validation.py
- Return a value from `verify_all_indices_unique` so that `panel` isn't
unconditionally `None` in `PanelDailyBarReader`.
- Fix a bug where we always set the volume of every asset to `1e9`.
- Add minimal suite of tests for get_spot_value, which catch both of the
above.
NOTE: There are still several issues with `PanelDailyBarReader`.  The
docstring for `get_spot_value` claims that it will return -1 on days
where an asset didn't trade, which isn't the case.  It also claims that
it will raise `NoDataOnDate` when a request is made outside the panel
range, but it just raises a KeyError.  We also still have no coverage
for `load_raw_arrays`, so it's likely that there are more bugs lurking.
> BUG: Fix multiple bugs in PanelDailyBarReader.

- docs/source/beginner-tutorial.rst
- docs/source/bundles.rst
- docs/source/whatsnew/1.0.0.txt
- setup.py
- tests/data/bundles/test_core.py
- tests/test_examples.py
- zipline/__main__.py
- zipline/assets/assets.py
- zipline/data/bundles/__init__.py
- zipline/data/bundles/core.py
- zipline/data/bundles/quandl.py
- zipline/data/bundles/yahoo.py
- zipline/utils/cache.py
- zipline/utils/run_algo.py
This data bundle will use the quantopian mirror of the quandl WIKI data
instead of downloading from quandl directly. This dramatically improves
the speed because we do not pay the rate limiting for quandl and we can
send the data in the format zipline expects.
NOTE: I need to rebuild the quandl set in s3. To test locally you can change the path to point to `s3://.../test/` which is a smaller sample of data which works. I will run the load overnight tonight.
> ENH: Adds quantopian-quandl bundle as new default.

- zipline/algorithm.py
- zipline/gens/sim_engine.pyx
on my machine, ~350ms -> ~300ms
also, clarifies the public API for MinuteSimulationClock (now, only `__iter__` is exposed)
> PERF: takes ~14% off the time it takes to initialize a MinuteSimulationClock

- tests/pipeline/test_classifier.py
- tests/pipeline/test_factor.py
- tests/pipeline/test_term.py
- zipline/lib/labelarray.py
- zipline/pipeline/classifiers/classifier.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/term.py
Fixes a few latent bugs in string classifiers:
- Fixes groupby on Factor being broken with string classifiers.
- Adds validation of term missing_values and fixes several locations where we were constructing invalid terms.
- Fixes a broken error message for Classifier.element_of.
> String Classifier Cleanup

- zipline/__main__.py
- zipline/data/bundles/quandl.py
Adds a progress bar to quantopian-quandl downloads and fixes a bug where `zipline bundles` would print tuples in Python 2.
> Cli improvements

- docs/source/appendix.rst
- docs/source/release-process.rst
- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/api.py
- zipline/finance/cancel_policy.py
- zipline/finance/commission.py
- zipline/finance/controls.py
- zipline/finance/slippage.py
- zipline/sources/requests_csv.py
- zipline/utils/events.py
Update the documentation for the `zipline.api` namespace as well as some supporting objects.
> api documentation

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
Remove filtering for float columns in the blaze core loader - allow any supported dtypes.
> Remove type restrictions for generic loader

- tests/test_algorithm.py
- tests/test_perf_tracking.py
- zipline/algorithm.py
- zipline/finance/performance/period.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
When we introduce a capital change (inflow or outflow of cash), make the appropriate adjustments to all the relevant performance fields on the `PerformancePeriod`.
Two types of capital changes:
- Capital Change between periods (daily periods)
- When a capital change is specified outside of the algorithm's market hours
- Because the capital change comes between daily periods, when a change is specified, just add that to the starting cash of that period (daily performance period starts with a greater portfolio value)
- Capital change within periods (daily periods or cumulative period)
- if the capital change comes within the period (during market hours for daily periods, and anytime for the cumulative period), we need to segment this period by the datetime on which the changes come
- …
> DEV: Adjust performance calculations for capital changes

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
If minutes already exist for the last existing day, adjust the number of minutes padded to account for them. Previously we would always pad 390, leading to a mismatch in the number of rows.
> BUG: Fixes bcolz padding to not always pad 390 minutes

- tests/test_history.py
- zipline/testing/fixtures.py
Allow `WithBcolzDailyBarData` to opt-in to reading data defined by
`WithBcolzMinuteBarData`, so that the daily and minute test for the same
asset and dts correlate between the two readers.
The correlation is relevant for history tests which blend daily and
minute data.
Also, make the test data for the split and mergers assets in the minute
suite align at the thousands place if the adjustmets are applied
correctly, by starting the prices with a base of 4000 and then halving
the start value each day.
> TST:  Enable sourcing daily data from minute data.

- tests/finance/test_slippage.py
- tests/test_algorithm.py
- tests/test_benchmark.py
- tests/test_data_portal.py
- tests/test_finance.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
- zipline/utils/run_algo.py
Instead of inferring it from the minute/daily writer, we now require the first trading day to be passed explicitly, so the creator of the `DataPortal` controls what is used as the first trading day.
> MAINT: Adds first_trading_day arg to DataPortal

- tests/data/test_us_equity_pricing.py
- zipline/data/us_equity_pricing.py
When writing `'first_trading_day'`, it is already in the correct frame of reference (seconds since epoch) and does not need to be transformed further. Adjusts the reader to expect this value.
> BUG: Fixes reading and writing of daily bars first_trading_day attr

- zipline/dispatch.py
datashape should be optional, this ensures it is actually optional.
> BUG: Don't delete namespace if import fails.

- zipline/__main__.py
- zipline/data/bundles/core.py
```
18:55  $ zipline ingest quantopian-quandl                                                                                           (zipline_conda)
Usage: zipline ingest [OPTIONS]
Error: Got unexpected extra argument (quantopian-quandl)
```
Need to add `-b` flag.
> Correct typo

- etc/requirements_blaze.txt
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/utils.py
- zipline/utils/pandas_utils.py
Breaking out what I have now so I don't build up a very large diff.
1. Only do the lower bound query for the base expression, not the deltas. This was extra work that is not needed.
1. `DatetimeIndex.time >= time` is _really_ slow. Implements a `mask_time_between` which will do the time comparison against the datetime index much more quickly.
1. Upgrade blaze ecosystem. One important change is to drop an unneeded copy in the blaze server/client.
This shaves about 1.5s off the tests which is nice.
> ENH: improve performance of blaze core loader

- tests/test_examples.py
- zipline/gens/tradesimulation.py
when simulation finishes, so that resources are cleaned up
deterministically.
See #1235.
> MAINT: Break reference cycle between algorithm and simulator

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/utils/events.py
When the user calls schedule_function(func, a_time_rule), assume that the user meant to specify a time rule but no date rule, instead of a date rule and no time rule as the signature suggests
> Support the passing of a time rule positionally on the date_rule arg

- tests/pipeline/test_technical.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/technical.py
This pull request is for adding the Aroon indicator and includes a minimal set of unit tests.
@llllllllll
> ENH: Add Aroon indicator.

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/testing/fixtures.py
Since the first trading day is now passed directly to the `DataPortal` on init, there's no need for a method that does this. Moves all the additional logic/assignments into the init. Also corrects an issue where we would never create certain attributes if `self._first_trading_day` was `None`.
Adds the ability to specify the first trading day for a data portal in a test case when using the `WithDataPortal` fixture.
> MAINT: Removes the set_first_trading_day method of DataPortal

- tests/test_history.py
- zipline/data/data_portal.py
- zipline/data/us_equity_loader.py
Fix behavior in minute mode history with frequency `1d`, where on the
day immediately following an adjustment action, the overnight adjustment
would not apply. (However the adjustment would be applied after a 1 day
lag.)
The root cause of the bug was that the history data for minute mode when
using `1d` stitches together a sliding window of the daily data for
previous  and the current minute. That daily data sliding window and
corresponding adjustments was being read as if the data was being viewed
from on the last day of the window; however in this case the data is
being viewed from the day after the window has completed. The difference
in view points requires the adjustments to popped and applied by the
adjusted array one index earlier. The fix uses the `extra_slot` value as
signifier …
> BUG: Apply latest adjustment for minute `1d`

- tests/utils/test_events.py
- zipline/utils/events.py
Make the rules resilient to env.previous_trading_day or
env.next_trading_day being None
> MAINT: Make schedule function rules resilient for no trading day

- zipline/finance/performance/tracker.py
- zipline/utils/calendars/calendar_helpers.py
- zipline/utils/events.py
- refactor the week rules to eliminate unnecessary type coercion of dates
- `next_scheduled_day` and `previous_scheduled_day` will raise `NoFurtherDataError` if there is no such day available in the calendar, instead of returning None. This is what `add_scheduled_days` does when `|n| > 1`, and make the behavior of the function consistent across all values of `n`
> Schedule function rules refactoring

- zipline/utils/tradingcalendar.py
The `tradingcalendar` module was been replaced by the new exchange calendars and trading schedules. Sets up an import hook in `algorithm.py` to issue a ZiplineDeprecationWarning on `tradingcalendar` imports.
> MAINT: Creates deprecation warning for tradingcalendar imports

- zipline/data/data_portal.py
Querying for the price field of an equity actually looks at the close field, so we should do the same for futures. Otherwise `data.can_trade` and `data.current` of 'price' fail for futures.
> MAINT: Fixes DataPortal.get_spot_value to correctly handle 'price' field

- zipline/utils/calendars/exchange_calendar_cme.py
Since the CME calendar was based off of the NYSE calendar, closings for Hurricane Sandy were included, but shouldn't have been for CME.
This is the explanation we had included prior to the new exchange calendars:
http://en.wikipedia.org/wiki/Hurricane_sandy
We *do not* add any non-trading days for Hurricane Sandy. Although trading on CME Group exchanges was disrupted, trading still occurred at some point on each day. Importantly, the disruptions do not appear to have affected the expiration dates stipulated in the futures contracts expiring during this period.
Trading of CME US equity index futures & NYMEX futures was disrupted due to the hurricane's impact on New York. CME US equity index futures markets were disrupted on October 29th 2012, but reopened at 5:00pm CT.
The US equity index …
> BUG: Removes Hurricane Sandy closings from CME exchange calendar

- tests/utils/test_events.py
- zipline/utils/events.py
Was previously returning a non-normalized dt when the first day of the month is a trading day. As a result, comparing the return value to the normalized value of the current dt is always False
> BUG: get_first_trading_day_of_month needs to return normalized dt

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/__init__.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/testing/predicates.py
Adds an optional argument to `from_blaze` for users to provide a ffill checkpoint table.
> ENH: add ffill checkpointing to blaze core loader

- tests/pipeline/test_pipeline.py
- zipline/pipeline/pipeline.py
If you try to run a pipeline with a column of `USEquityPricing.close` (or something similar) and you meant to use `USEquityPricing.close.latest`, it errors in a non-helpful/obvious way.
> BUG: Fail fast on invalid pipeline columns

- tests/pipeline/test_events.py
- zipline/pipeline/loaders/utils.py
Adds a workaround and a test for the pandas bug that results in an incorrect timestamp, described here: https://github.com/quantopian/qexec/issues/10456
> Pandas tz normalize bug workaround

- docs/source/bundles.rst
-b flag is required:
```
Usage: zipline ingest [OPTIONS]
Error: Got unexpected extra argument (quandl)
```
As help suggests:
```
Usage: zipline ingest [OPTIONS]
Ingest the data for the given bundle.
Options:
-b, --bundle BUNDLE-NAME        The data bundle to ingest.  [default:
quantopian-quandl]
<...>
```
> DOC: Fix typo in command line to ingest quandl

- zipline/utils/tradingcalendar.py
The new calendar API is currently in flux, so disabling the deprecation warning for `tradingcalendar`. To be re-enabled once the new API is stabilized.
> MAINT: Disable deprecation warning for tradingcalendar

- tests/pipeline/test_pipeline_algo.py
- zipline/pipeline/loaders/equity_pricing_loader.py
This calendar only has up to the last trading day, use `default_nyse_schedule` instead.
> BUG: Don't use calendar from daily bars in USEquityPricingLoader

- tests/data/bundles/test_core.py
- tests/data/bundles/test_quandl.py
- tests/data/bundles/test_yahoo.py
- tests/data/test_us_equity_pricing.py
- tests/finance/test_slippage.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_pipeline_algo.py
- tests/pipeline/test_us_equity_pricing_loader.py
- tests/test_algorithm.py
- tests/test_api_shim.py
- tests/test_bar_data.py
- tests/test_benchmark.py
- tests/test_blotter.py
- tests/test_commissions.py
- tests/test_history.py
- zipline/data/bundles/core.py
- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
- zipline/testing/__init__.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
- zipline/utils/run_algo.py
In preparation of adding futures, add equity to the names of both the
classes and methods for writing bcolz data. Futures data will use a
different minutes per day with a separate reader. This change will allow
both equity and futures fixtures to be side by side.
Also, break out the method which generates the dataframes and trading
days member into fixtures (`EquityMinuteBarData` and
`EquityDailyBarData`) on which the `*BarReader` fixture depends.  This
fixture is separated out to enable reader/writers in different formats
to use the same data setup. (There is internal code which needs to write
minute and daily bar data in a database format.)
> MAINT:  Add equity to naming of bar data classes.

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_engine.py
- zipline/pipeline/factors/technical.py
`AverageDollarVolume` used `nanmean`, which discards NaNs before
averaging, giving an ADV which is too high for any equities that have
any NaNs.
Changing the method to `nansum` divided by window length so that the
denominator is the same no matter whether there are NaNs or not.
> BUG: Correct AverageDollarVolume NaN handling

- tests/test_algorithm.py
Limit the date range to one day, instead of a year.
On my local machine the following goes from taking 12 seconds to 0.6 seconds.
`$ nosetests -x tests/test_algorithm.py:TestMiscellaneousAPI`
> TST: Speed up TestMiscellaneousAPI

- tests/data/test_us_equity_pricing.py
- tests/test_algorithm.py
- tests/test_finance.py
- zipline/data/bundles/core.py
- zipline/data/us_equity_loader.py
- zipline/data/us_equity_pricing.py
- zipline/pipeline/loaders/equity_pricing_loader.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
Make daily bar readers take advantage of the `TradingCalendar`.
Make `USEquityPricingLoader` use the same calendar.
Both the reader and writer were updated, but the reader maintains backwards compatibility.  The test examples have *not* had their data updated, to ensure that we can read old data.
> Fix daily bar writer

- zipline/utils/calendars/trading_calendar.py
Offsetting days in the local timezone can cause issues when there are discontinuities, such as at the start of DST. So we instead do this offset in UTC, then localize to the local timezone once dealing with times.
> BUG: Fixes issue with offsetting days in days_at_time calendar helper

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_engine.py
- tests/pipeline/test_statistical.py
- zipline/errors.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/factors/statistical.py
Opening in favor of https://github.com/quantopian/zipline/pull/1300
- Allow correlations/regressions to be computed between two 2D factors by doing computations asset-wise
- Moves all correlation/regression related tests from `test_engine.py` to `test_statistical.py`
> Factor-to-factor correlations and regressions

- tests/test_trading_calendar.py
- zipline/utils/calendars/trading_calendar.py
- Revert to using DateOffset, as Timedelta doesn't handle offsetting by one day over a tz change properly:
```
In [12]: pd.Timestamp('2004-04-05', tz='America/Chicago') + pd.Timedelta(days=-1)
Out[12]: Timestamp('2004-04-03 23:00:00-0600', tz='America/Chicago')
In [13]: pd.Timestamp('2004-04-05', tz='America/Chicago') + pd.DateOffset(days=-1)
Out[13]: Timestamp('2004-04-04 00:00:00-0600', tz='America/Chicago')
```
By creating a DateOffset using the `days` kwarg, the issue previously fixed in bcc867b is addressed.
- To preempt any other pandas issues around day offsets, changes to performing these with no timezone, then localizing to the local timezone when shifting the time.
- Adds unit test for `days_at_time`
> BUG: Further corrections for days_at_time

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_filter.py
- zipline/pipeline/filters/filter.py
> ENH: made filters window safe

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/finance/performance/period.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
- zipline/protocol.py
- Allow capital changes to be defined by a target value, in addition to the currently support input of deltas. The delta will be calculated on the portfolio value at the dt of the capital change
- Refactor the checking, calculating and processing of capital changes to better support upstream processes
> Capital Changes Refactoring

- tests/pipeline/test_technical.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/technical.py
rebased version of: https://github.com/quantopian/zipline/pull/1251
I just rebased the pr and added the default inputs to the docstring. Thanks for the factor @ChrisPappalardo
> TrueRange Factor

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_factor.py
- tests/pipeline/test_filter.py
- tests/pipeline/test_term.py
- zipline/lib/normalize.py
- zipline/lib/rank.pyx
- zipline/pipeline/factors/factor.py
Adds support for `groupby` to `top`, `bottom`, and `rank`.  Based on @andportnoy's work in https://github.com/quantopian/zipline/pull/1260, with a few small fixes for datetime dtypes and some more test coverage.
> Groupby rank top

- tests/pipeline/test_pipeline_algo.py
- tests/test_algorithm.py
- tests/test_fetcher.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/gens/sim_engine.pyx
Before this change, when a simulation runs with `data_frequency="daily"`, the algorithm's clock would emit session labels (midnight utc).  In other words, if the algorithm ever used `TradingAlgorithm.get_datetime()`, it would be midnight UTC.
This is misleading because at midnight UTC, the algorithm can get the daily bar for an asset that represents (on a NYSE calendar) data that hasn't technically happened yet (since the trading hours haven't started for that day yet).
As we're moving towards supporting various trading calendars, this problem has become trickier.  For example, `data.can_trade` is going to be extended to check if the asset's exchange is open at the moment of the order.  This is a lot easier to answer and reason about if the order's `dt` is a trading minute, not a trading …
> ENH: Change daily mode to use last minute of session instead of session label

- tests/test_perf_tracking.py
- zipline/algorithm.py
- zipline/finance/performance/period.py
- zipline/finance/performance/tracker.py
- zipline/gens/tradesimulation.py
Previously, on the dt of a capital change, we use the un-updated
prices to find the ending performance of the previous subperiod and
then got the new prices to determine the portfolio value used to
calculate the delta, without actually updating the performance
before applying the capital change. This logic is confusing and
unintuitive. Instead, save the ending performance as we do previously,
but have temp values for the starting current subperiod value.
Update those temp values after processing the capital change
> MAINT: Refactor application of capital changes

- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_filter.py
- zipline/pipeline/filters/__init__.py
- zipline/pipeline/filters/filter.py
smoothing filter added to zipline
> ENH: added smoothing to zipline

- tests/data/test_us_equity_pricing.py
- tests/pipeline/test_us_equity_pricing_loader.py
- tests/test_algorithm.py
- tests/test_assets.py
- tests/test_benchmark.py
- zipline/__main__.py
- zipline/assets/__init__.py
- zipline/assets/_assets.pyx
- zipline/assets/asset_db_migrations.py
- zipline/assets/asset_db_schema.py
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
- zipline/data/bundles/yahoo.py
- zipline/errors.py
- zipline/testing/predicates.py
- zipline/utils/functional.py
- zipline/utils/paths.py
- zipline/utils/range.py
We are doing it this time!
There are 2 commits after the revert that should be reviewed now.
> Point in time assets db again

- tests/test_tradesimulation.py
- zipline/gens/tradesimulation.py
so that log lines in b_t_s have the proper dt.
Ideally we would get rid of the `simulation_dt` variable entirely in `tradesimulation`, but that can be done another day.
> BUG: Need to set simulation_dt in before_trading_start

- tests/data/test_minute_bars.py
- tests/pipeline/base.py
- tests/pipeline/test_events.py
- tests/test_algorithm.py
- tests/test_assets.py
- tests/test_benchmark.py
- tests/test_perf_tracking.py
- tests/test_security_list.py
- zipline/testing/fixtures.py
When adding fixtures for futures data, there will be a need for multiple
calendars in the fixture ecosystem. e.g. a test that includes both
equities and futures would need an overall calendar which encompasses
both equities and futures; however, the test data for equities should
still still be limited to the bounds set by the NYSE calendar.
Make the fixtures that setup trading calendars and values dervied from
the trading calendar (e.g. trading sessions) accept an iterable of
calendars which need to be created, then populate those values into a
dict keyed by the calendar name.
Change `WithNYSETradingDays` to include sessions in the name,
since we are moving to session as the name for the 'day' unit.
Provide `trading_days` which is really "NYSE trading sessions` on
`WithTradingSessions` …
> TST: Make room for multiple calendars in tests.

- tests/test_history.py
- zipline/data/resample.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
Change the mock minute data to no longer use an increasing arange, so
that a days worth of minute data can be summed and fit inside of a
uint32.
This change was required because of working on new test data that looked
like [0, 100, 200, 0, ] which was resulting in a daily rollup of 0 data,
when the coverage needed a non-0 value.
> TST: Use sum for volume on daily data resample.

- zipline/utils/calendars/calendar_utils.py
Encapsulate the shared global calendar map in an object.
This allows consumers that don't want to participate in custom
registration to pass around a calendar dispatcher, and would make it
easier to support contextual management of the global calendar map if we
want to do that in the future.
As a bonus, we now only create one instance of each calendar, instead of
one per alias.
> MAINT: Isolate global calendar state.

- zipline/testing/fixtures.py
Instead of using strings of 'equities' and 'futures', use the Asset
subclasses to key the trading calendar fixtures.
> TST: Key trading calendar fixture with Asset types

- tests/test_data_portal.py
- zipline/data/data_portal.py
Add direct coverage of `get_last_traded_dt` in `test_data_portal` for `Equity` asset types, to be followed by a test case for `Future` assets.
In support of routing between `Equity` and `Future` asset types, add and use a `_pricing_readers` dict keyed by asset type and data frequency.
> Prepare data portal tests for covering Futures assets types.

- tests/test_data_portal.py
- zipline/data/data_portal.py
- zipline/testing/fixtures.py
Add support and coverage for getting the last traded dt for Future assets from the data portal.
Add test coverage for `get_spot_value` for Equities and Futures.
Add new implementation of `get_spot_value` for Futures, by changing the existing `_get_spot_value_minute` to select the appropriate reader based on `Asset` type.
This patch adds `WithFutureMinuteData` and `WithFutureBcolzMinuteData` fixtures to generate the temporary data tested by the `test_data_portal` suite.
> Support last sale dt and spot value for Future assets.

- tests/test_assets.py
- zipline/assets/asset_writer.py
When constructing the asset_info dataframe, we were previously taking the first symbol/sid pair to include, when we should be taking the most recent.
> BUG: Fixes asset writer to the select the latest asset to hold a sid

- zipline/data/session_bars.py
In preparation for making a resampling session bar reader, make an
abstract base class with the methods currently used by consumers of the
reader; which should assist in making a drop-in replacement of the daily
bar reader.
While pulling out the interface, it does appear that `spot_price` and
the minute bar reader's `get_value` are the same method but by different
names, showing that there may be room for having both `MinuteBarReader`
and `SessionBarReader` sharing a common `BarReader` interface.
> MAINT: Factor out session bar reader interface.

- docs/source/appendix.rst
- docs/source/bundles.rst
- tests/data/bundles/test_core.py
- tests/data/bundles/test_quandl.py
- tests/data/bundles/test_yahoo.py
- zipline/data/bundles/core.py
- zipline/data/bundles/quandl.py
- zipline/data/bundles/yahoo.py
Instead of trading days, opens, and closes, register now takes a TradingCalendar object, along with a start_session and end_session. The ingest function is now passed these values instead as well.
> MAINT: Use TradingCalendar objects for bundles

- zipline/data/session_bars.py
- zipline/data/us_equity_pricing.py
Replace `DailyBarReader` with `SessionBarReader`.
This was intended to go with the patch that added the `SessionBarReader`
abstract base class.
Also, added `trading_calendar` property decorator.
> MAINT: Use session bar reader interface.

- tests/data/test_resample.py
- zipline/data/resample.py
- zipline/testing/fixtures.py
Implement a `SessionBarReader` which uses a minute bar reader as a
backing source, resampling the minute bars into the box around the
corresponding session data.
Also, add future/CME test cases to resample suite.
This PR also includes https://github.com/quantopian/zipline/pull/1404
This PR is a step towards providing history windows for Future pricing data via the data portal, where the next step will be using the resampled reader in a `SessionHistoryLoader` (which will be a refactored version of `USEquityLoader`.
Resampling is used instead of the `BcolzDailyBarReader` for the following reasons.
1) Provide more flexibility on the boundaries of the window, e.g. using `CME` on all futures, or using Future specific calendars.
2) Remove need for also generating the bcolz daily/session bars …
> ENH: Session bar reader resampled from minute data

- tests/data/test_minute_bars.py
- tests/test_algorithm.py
- zipline/data/bundles/core.py
- zipline/data/minute_bars.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
Updates `BcolzMinuteBarWriter` to take a `TradingCalendar`, start session, and end session. Previously used "first trading day" and `DatetimeIndex` objects of market opens and closes.
> ENH: Pass calendar instance to BcolzMinuteBarWriter

- zipline/utils/calendars/calendar_utils.py
- zipline/utils/calendars/us_futures_calendar.py
For trading US futures across the exchanges supported by Zipline.
> ENH: Adds QuantopianUSFuturesCalendar

- tests/calendars/test_trading_calendar.py
- zipline/utils/calendars/_calendar_helpers.pyx
- zipline/utils/calendars/trading_calendar.py
~~*Incomplete; "vectorized" `minute_to_session_label` is done so far*~~
The new TradingCalendar method is called `minute_index_to_session_labels`.
It takes a DatetimeIndex of in-order market minutes and returns a
DatetimeIndex of the corresponding sessions.
The new method is approximately 100x faster than mapping
`minute_to_session_label` over a large DatetimeIndex.
> ENH: Add fast "vectorized" `minute_to_session_label` for DatetimeIndex

- zipline/pipeline/factors/technical.py
When using the `from_x`-like constructors for EWMA, no mask can be passed to the EWMA constructor. Added a kwargs variable so that these don't break if/when the factor base class is updated
> BUG: Add kwargs to ewma constructors

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
We were mistakenly using the `minute_per_day field`.
We now expose from the metadata object the version from which the metadata was read. This allows a new test that verifies the version is read correctly.
> BUG: Fixes BcolzMinuteBarMetadata to read the version correctly

- zipline/data/minute_bars.py
Instead of using a single ratio to scale up pricing for each sid before writing for bcolz, the writer now accepts a dict mapping each sid to the ratio to use. This arg is still optional, and we use the existing
`OHLC_RATIO` (1000) for every sid if no dict is passed.
This allows better handling of futures pricing data, where the required precision across root symbols is not consistent.
> MAINT: Modifies minute bars to use a dict of OHLC ratios

- tests/data/test_resample.py
- tests/data/test_us_equity_pricing.py
- tests/pipeline/test_pipeline_algo.py
- tests/test_bar_data.py
- tests/test_panel_bar_reader.py
- zipline/data/data_portal.py
- zipline/data/resample.py
- zipline/data/session_bars.py
- zipline/data/us_equity_pricing.py
- zipline/testing/core.py
The daily/session bar reader's `spot_price` took the same parameters and
returned the same kind of output as the minute bar reader's `get_value`.
Standardize on one method to make a common interface, which may be
formally factored out in a later patch; to help enable writing reader
implementations or mixins which can be agnostic to the bar frequency.
> MAINT: Standardize reader get value methods.

- tests/data/test_dispatch_bar_reader.py
- tests/data/test_resample.py
- zipline/data/dispatch_bar_reader.py
- zipline/data/minute_bars.py
- zipline/data/resample.py
Add `AssetDispatchSessionBarReader` and corresponding minute and session
bar version of that reader.
This reader routes requests to the appropriate reader based on the asset
type of the requested sids.
`load_raw_array` in the dispatch reader batches the sid by asset type
and then interleaves the results in the out arrays, so that the arrays
data corresponds with sids in the order that sids are passed to the
method, to meet the expected behavior of `load_raw_arrays`.
The dispatch redaer is intended for use by the data portal when using
both future and equities. The dispatch reader will also be passed to the
to the `HistoryLoader`s contained within the data portal, where the
batched `load_raw_arrays` will be used.
Also, BUG:
- Fix the return of …
> MAINT: Add a reader which dispatches on asset type

- tests/test_algorithm.py
- zipline/data/data_portal.py
- zipline/data/dispatch_bar_reader.py
- zipline/data/minute_bars.py
- zipline/data/resample.py
- zipline/data/session_bars.py
Combine the equity and future readers into asset dispatch readers, so
that simulations that use both asset types can access data for each.
This patch enables `history` for future assets in algorithms; however,
it does not add extra coverage in the `test_data_portal` or `test_history`
to cover future assets. Those tests will follow, however putting this in
separately since it shows that the wrapping of the readers in the asset
dispatch reader does not break existing equity strategies.
> ENH: Add asset dispatch to data portal.

- zipline/data/data_portal.py
- zipline/data/resample.py
`1d` history calls were failing on key errors when using the
`us_futures` calendar, because of timestamps occuring before a midnight
would present the wrong midnight (i.e. the midnight before the session,
instead of the following midnight, which is the label for the current
session.)
Tests will follow when bringing up coverage on resample and data portal
modules.
> BUG: Use session label instead of date for 1d.

- zipline/data/minute_bars.py
To get the length of the underlying table for a given sid.
> ENH: Adds table_len method to BcolzMinuteBarReader

- tests/data/test_resample.py
Add a test to directly cover the first_trading_day method via the
`test_resample` suite. (The lack of coverage was exposed when testing
against real data.)
Also, refactor resample bar tests so that session bar reader is set up
in instance fixture.
> TST: Cover resample bar first_trading_day method.

- conda/empyrical/meta.yaml
- etc/requirements.txt
- zipline/finance/risk/cumulative.py
- zipline/finance/risk/period.py
Principally by ...
1. Passing things already computed (e.g. `beta`) into methods that require them (e.g. `alpha`) so they don't re-compute them.
2. Risk-adjust the return stream only once so that empyrical doesn't have to do it separately in each method.
(Opening PR to validate Travis; we need to release a new empyrical to pypi after https://github.com/quantopian/empyrical/pull/27 is merged)
> PERF: Reduce calculations performed by empyrical

- tests/data/test_resample.py
Instead of CME, use the futures cal, which should now be the standard
calendar throughout; though some tests remain to be ported.
> TST: Use futures cal in resample suite.

- tests/events/test_events.py
- tests/events/test_events_cme.py
- tests/events/test_events_nyse.py
- zipline/utils/events.py
We used to cap at 6.5 hours, but that's not enough for longer trading sessions like the CME.
> ENH: Let event offsets be up to 12 hours.

- conda/empyrical/meta.yaml
- etc/requirements.txt
Previous version of empyrical calculates beta incorrectly. Update the conda recipe, as well as the example data used in testing.
> Empyrical v update

- tests/data/test_resample.py
Add direct coverage on last_available_dt.
Also move reader creation into the instance fixture.
This patch attempted to add coverage on `get_last_traded_dt`, but in doing
so, revealed a bug in `BcolzDailyBarReader.get_last_traded_dt` when
requesting the last trading session of an asset.
When that is fixed, the skip can be removed.
> TST: Increase coverage for  reindex reader methods

- zipline/assets/assets.py
Cache the last 100 rootsymbol/session pairs, since future chains never
change inside a session.
> ENH: Put a cache in front of future chain lookups

- tests/test_algorithm.py
- tests/test_assets.py
- zipline/algorithm.py
- zipline/assets/futures.py
No longer auto-updates its internal as-of date, instead requires an explicit
as-of date from the consumer.
Take a static list of contracts (instead of needing an assetfinder).
Instead of the as_of method, the user-facing API now lets you pass in an
offset, which is defined as an integral number of sessions.
> ENH: Simplified implementation of FutureChain object (not user-facing API)

- tests/data/test_resample.py
- tests/data/test_us_equity_pricing.py
- tests/test_bar_data.py
- zipline/data/us_equity_pricing.py
Remove special handling for the last session of an asset, which was
moving the last traded back a session.
If the asset has data on a session, `get_last_traded_dt` should always
return that session if it is the parameter to the method.
> TST: Fix get_last_traded_dt on bcolz daily reader.

- tests/finance/test_slippage.py
- tests/test_api_shim.py
- tests/test_bar_data.py
- tests/test_blotter.py
- tests/test_finance.py
- tests/test_history.py
- zipline/_protocol.pyx
- zipline/gens/tradesimulation.py
BarData now takes the trading calendar as a parameter.
`can_trade` now checks if the asset’s exchange is open at the current or
next market minute (defined by the given trading calendar).
> ENH: Update can_trade to check exchange time

- .coveragerc
- tests/data/test_resample.py
- zipline/data/resample.py
- zipline/data/session_bars.py
- zipline/data/us_equity_pricing.py
Increase coverage on `ReindexSessionBarReader` so that all methods which
are considered part of the interface are covered by `test_resample`.
Fix bug in `get_value`, exposed by increased coverage, where the
`NoDataOnDate` exception was bubbling from the bcolz reader all the way
up when a session which was a holidy on the underlying reader was passed
to the reindex reader. (The reindex reader should return nan/0 in that
case.)
Also, move location of data index exceptions so that they are agnostic
to bcolz/us_equity_pricing; since the exception is now used by the
resample module to fix aforementioned bug.
> TST/BUG: Cover all reindex session public methods.

- tests/test_algorithm.py
- zipline/algorithm.py
The calculation of the "delta" from a given "target" value for a capital change was doing `delta = target - portfolio_value`. That's not right - the value of any portfolio holdings is irrelevant when adding or removing real cash from the algorithm. I corrected it to `delta = target - cash`; this broke a number of tests. I modified the 'target' input values so that it matched the behavior of the corresponding 'delta' test.
Also adds a new parameter that can be passed to `calculate_capital_changes` to remove additional value from the cash value pulled from the current cumulative performance period. (In case there are additional influences on the cash value that need to be removed to get an accurate calculation)
> BUG/ENH: Fix behavior of 'target' capital changes

- tests/data/test_resample.py
- zipline/data/resample.py
test_resample now fully covers the resample module.
Fix a bug exposed by increased coverage, where daily aggregation on
`high` would return `nan` for an asset instead of 1) during the
course of day `1d` history was called on non-consecutive minutes and 2)
either, a) the value for the previously inspected dt was `nan` or b)
there were only `nan`s between the previous and current dt.
`low` had a similar bug which was only triggered if the value for the
previously inspected dt was `nan`.
> TST/BUG: Full coverage on resample module.

- zipline/finance/risk/cumulative.py
- zipline/finance/risk/period.py
Remove variable `risk_adj_returns`. Neither sharpe nor sortino require risk adjusted returns. Information ratio can create adjusted returns as necessary.
> BUG: Do not adjust returns for sharpe and sortino

- tests/test_data_portal.py
Check that both an equity and future can return expected values for
`get_last_traded_dt`.
> TST: Add direct coverage for get last traded dt

- tests/pipeline/test_statistical.py
- zipline/pipeline/factors/statistical.py
- zipline/utils/input_validation.py
They're not meaningful, and they cause warnings from numpy.
Implemented in terms of a new preprocessor, `expect_bounded`, which
takes a tuple of `upper_bound` and `lower_bound`.
> ENH: Dont allow length=1 regressions/correlations.

- tests/test_algorithm.py
- zipline/algorithm.py
This reverts commit 5b1aa5ec55c70660103206e99e5f13fa6ed8f332.
The paradigm is: we're calculating a new capital base for the
performance period. We are therefore using the total
portfolio_value, not just the cash, to calculate the
difference from the specified target as the algorithm
has meaningful holdings.
> Revert "BUG: Capital change deltas rely on cash, not portfolio_value"

- tests/test_assets.py
- zipline/assets/assets.py
- Correctly raises SymbolNotFound in fuzzy symbol lookup.
- Adds checking against NoneType (useful in case someone vectorizes across a series, one of which is a None)
- If asset file has two symbols which map to the same sid (SYM_B, and SYMB), should not raise a MultipleSymbolError, should just return the correct equity object for the sid.
> Symbol lookup raises

- tests/calendars/test_calendar_dispatcher.py
- tests/calendars/test_trading_calendar.py
- tests/data/bundles/test_core.py
- tests/data/bundles/test_quandl.py
- tests/data/bundles/test_yahoo.py
- zipline/__init__.py
- zipline/data/bundles/core.py
- zipline/data/bundles/quandl.py
- zipline/data/bundles/yahoo.py
- zipline/data/loader.py
- zipline/errors.py
- zipline/utils/calendars/__init__.py
- zipline/utils/calendars/calendar_utils.py
Remove module scope invocations of `get_calendar('NYSE')`, which cuts
zipline import time in half on my machine. This make the zipline CLI
noticeably more responsive, and it reduces memory consumed at import
time from 130MB to 90MB.
All of the module-scope `get_calendar` invocations were in the bundle registration code.  There are two major changes required to make this work:
1. Added a `register_calendar_alias` method and reworked the way calendars are stored internally in `TradingCalendarDispatcher`.  There's now always one canonical name under which a calendar is stored, but possibly many "aliases" to that calendar.  This is now used for the QUANDL and YAHOO loaders to alias NYSE.
2. Removed the creation of a calendar during bundle registration.  The calendar associated with a bundle …
> PERF: Remove import-time calendar creations.

- tests/test_algorithm.py
- zipline/_protocol.pyx
BUG: Change str to string_types to avoid errors
When in python2.7, and unicode_literals is imported
type check will raise error because 'type' is not str but unicode
Fixes up https://github.com/quantopian/zipline/pull/1315
> Check param string types

- zipline/utils/run_algo.py
to 'quantopian-quandl' bundle
For https://github.com/quantopian/zipline/issues/1374
I considered adding a unit test.  Because of its dependence on the global `load` of a bundle, it would depend on ingesting the real quantopian-quandl bundle first, or we'd need to register a replacement bundle globally for the span of the test.  So I haven't included a unit test here.
> BUG: run_algorithm with no data source should default

- zipline/protocol.py
CC: @llllllllll 
These were previously available like the other deprecated attributes here. Not sure where the discrepancy from the list you had here vs. the list in the API docs came from - might be something else we need to update?
> MAINT: Add additional fields to __getitem__ for Order

- tests/data/test_resample.py
- zipline/data/bar_reader.py
- zipline/data/minute_bars.py
- zipline/data/resample.py
- zipline/data/session_bars.py
- zipline/data/us_equity_pricing.py
> MAINT: Add BarReader base class for both minute and session readers

- zipline/pipeline/engine.py
- zipline/pipeline/graph.py
Refcount pipeline terms during execution and release terms once they're
no longer needed.
This dramatically reduces memory usage on large pipelines.
> PERF: Release unneeded pipeline terms.

- tests/data/test_minute_bars.py
- tests/data/test_resample.py
- tests/test_bar_data.py
- zipline/data/_minute_bar_internal.pyx
- zipline/data/bar_reader.py
- zipline/data/data_portal.py
- zipline/data/minute_bars.py
- zipline/data/resample.py
Previously, at least the minute bar reader was forward filling (using the previous market minute).
DataPortal now catches the NoDataOnDate exception and returns nan for OHLC and 0 for V.
Price is still forward filled, unchanged.
> ENH: Make reader.get_value raise NoDataOnDate if the date is not in the calendar.

- zipline/data/_adjustments.pyx
- zipline/data/history_loader.py
- zipline/data/us_equity_pricing.py
Instead of `HistoryLoader` containing separate adjustment calculation
logic, use `SQLiteAdjustmentReader.load_adjustments`.
This change required the addition of two offset parameters to
`load_adjustments` since the perspective on the data from within
`schedule_function` is skewed from how Pipeline looks at historical
data.
This is working towards creating an `AdjustmentReader` abc which
`SQLiteAdjustmentReader` and a upcoming continuous future adjustment
reader will share.
> MAiNT: Use load_adjustments for history.

- zipline/utils/calendars/trading_calendar.py
One year NYSE test that buys a lot triggers 492,963 calls to
minute_to_session_label.  Only 98924 (~= (390 * 252)) make it past the
cache and trigger the heavier computation.
> PERF: Save up to 80% of the calls to minute_to_session_label

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
> ENH: Adds truncate method to BcolzMinuteBarWriter

- zipline/data/data_portal.py
- zipline/utils/calendars/trading_calendar.py
Much, much, much faster this way.
> PERF: Be smarter about counting the number of minutes across a contiguous bunch of sessions.

- zipline/pipeline/loaders/blaze/estimates.py
- zipline/pipeline/loaders/earnings_estimates.py
- zipline/pipeline/loaders/utils.py
big performance improvement on larger data sets. This also fixes what I think is a bug where the data is not sorted on event_date in `get_requested_quarter_data` but I haven't written a test for that yet.
> PERF: vectorize earnings estimates

- zipline/data/data_portal.py
- zipline/utils/calendars/trading_calendar.py
- zipline/utils/calendars/us_futures_calendar.py
Mitigation for https://github.com/quantopian/zipline/issues/1503.
This was debugged primarily by adding the following lines to `zipline/tests/__init__.py`:
```python
+import os
+from unittest import TestCase
+
+import psutil
+import humanize
+import __builtin__
+
+pid = os.getpid()
+proc = psutil.Process(pid)
+
+def get_mem_usage():
+    return humanize.naturalsize(proc.memory_full_info().uss)
+__builtin__.gmem = get_mem_usage
+
+
+real_doCleanups = TestCase.doCleanups
+
+OUTPUT_FILE = open('/home/ssanderson/pandas18_memory_usage.txt', 'w')
+
+
+def patched_doCleanups(self, *args, **kwargs):
+    OUTPUT_FILE.write("{} {}\n".format(get_mem_usage(), self))
+    OUTPUT_FILE.flush()
+    return real_doCleanups(self, *args, **kwargs)
+
+TestCase.doCleanups = patched_doCleanups
```
> PERF: Remove or defer calls to get_loc on large indices.

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
With the addition of the truncate function, there are cases where we'll want to construct a `BcolzMinuteBarWriter` to call truncate, without gathering all the metadata. This commit adds a write_metadata arg to its init, which is True by default. If False is specified, no metadata is written.
> MAINT: Adds option for minute bar writer to not write metadata

- zipline/data/us_equity_pricing.py
We can make a single vectorized call outside of the loop, instead of repeatedly calling `get_loc` inside it.
> PERF: Replace get_loc calls in calc_dividend_ratios with get_indexer

- zipline/data/loader.py
`data.loader.ensure_benchmark_data()` was trying to use data after an exception was raised loading it.  The code was logging and swallowing exceptions; this re-raises.
> Propagate exceptions in loader to prevent variable reference before use

- Dockerfile
First time user, I spent some time setting it up and I ran into a few issues, the purpose of this pull request is to bring it to your attention, maybe it will help somebody else. Please close it if it doesn't apply.
- First time user.
- OS X El Capitan + VirtualBox
- Docker version 1.9.1,
```
Obtaining file:///zipline
Complete output from command python setup.py egg_info:
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Unable to find pgen, not compiling formal grammar.
Installed …
```
> Docker build failure - Add Tini and set version range for numpy

- zipline/data/dispatch_bar_reader.py
When dispatching to sub readers in dispatch reader, pass along the asset
object, instead of extracting the sid.
The in development reader for continuous futures values besides `sid`
are needed from the `ContinuousFuture` object.
> MAINT: Pass through asset instead of sid.

- tests/test_restrictions.py
- zipline/finance/asset_restrictions.py
Need to use toolz.groupby intead of itertools.groupby. itertools.groupby will only work if the elements to be grouped together are contiguous
> BUG: Restrictions passed into HistoricalRestrictions not sorted correctly

- tests/test_data_portal.py
- zipline/data/data_portal.py
- zipline/data/dispatch_bar_reader.py
- zipline/testing/fixtures.py
This allows optionally setting the last available dts in the DataPortal
explicitly. If these args aren't provided, we fall back to inferring
these from the underlying readers, which was the previous behavior.
> ENH: Adds last_available_{session, minute} args to DataPortal

- setup.py
- tests/test_algorithm.py
- tests/test_continuous_futures.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/assets/assets.py
- zipline/assets/continuous_futures.pyx
- zipline/assets/roll_finder.py
- zipline/data/data_portal.py
Add the ability for an algorithm to request the current contract for a
future chain via `data.current`.
e.g.:
```
data.current(ContinuousFuture('CL', offset=0, roll='calendar'),
'contract')
```
- Since `ContinuousFuture` will also be used in `history` and other places where `Asset`s are used.
The `ContinuousFuture` object provides `sid` and `is_exchange_open`.
Ideally, there would be some base interface which would harden that duck typing. But would request that is something we do post making the other `ContinuousFuture` `data` methods work.
- The `sid` calculation for the `ContinuousFuture` is intended to be consistent across simulations. However, would not recommend using that `sid` as something that would never change. If and when we add more custom sids, the struct packing format may …
> ENH: Add continuous future current contract.

- tests/pipeline/test_filter.py
- zipline/pipeline/filters/__init__.py
- zipline/pipeline/filters/filter.py
Adds a filter that matches a set of assets.  Mainly useful for testing and debugging.
> ENH: Add `SpecificAssets` filter.

- tests/pipeline/test_quarters_estimates.py
- zipline/pipeline/loaders/earnings_estimates.py
Fixes a bug in the estimates loader that causes overwrites for a quarter to overwrite any other overwrites for a quarter that started on the same day. I.e., if 2 sids have quarters that start on the same day, the second sid's quarter overwrite will replace the first sid's quarter overwrite rather than appending the second overwrite to a list.
> Fix estimates overwrites bug

- tests/test_continuous_futures.py
- zipline/_protocol.pyx
- zipline/assets/continuous_futures.pyx
- zipline/data/data_portal.py
Add `chain`field to current, as well as supporting methods in DataPortal
and OrderedContracts.
Enables the following example:
```
from zipline.api import continuous_future
def initialize(context):
context.primary_cl = continuous_future('CL', offset=0, roll='calendar')
schedule_function(print_current_chain)
def print_current_chain(context, data):
chain = data.current(context.primary_cl, 'chain')
print 'datetime={0}'.format(get_datetime())
print 'primary={0}'.format(chain[0])
print 'secondary={0}'.format(chain[1])
print 'tertiary={0}'.format(chain[2])
```
```
datetime=2015-12-23 14:31:00+00:00
primary=Future(1058201602 [CLG16])
secondary=Future(1058201603 [CLH16])
tertiary=Future(1058201604 [CLJ16])
```
Also, make return types of OrderedContracts methods compatible across
architectures. …
> ENH: Add current chain for continuous futures.

- tests/pipeline/test_events.py
- zipline/pipeline/loaders/blaze/core.py
fixes an issue in ffill_query_in_range when we didn't have checkpoints.
> fix events loader blaze query

- tests/pipeline/test_adjusted_array.py
- zipline/lib/_windowtemplate.pxi
- zipline/lib/adjusted_array.py
- Refactor `test_adjusted_array` to test a range of perspective_offsets in
all tests.
- Make perspective_offset a parameter to `AdjustedArray.traverse`
instead of `AdjustedArray`.
> MAINT: Use perspective_offset in more tests.

- tests/pipeline/test_adjusted_array.py
- zipline/data/history_loader.py
- zipline/lib/_windowtemplate.pxi
- zipline/lib/adjusted_array.py
Add a perspective offset to `AdjustedArrayWindow` and `AdjustedArray`,
so that `HistoryLoader` does not need to twiddle with offsets to support
viewing the data from the bar after end of the window, (Which is the
case when a '1d' history window is retrieved in minute mode, which is
explained in the docstring for `HistoryLoader.history`)
Presently, this simplifies the logic in
`HistoryLoader._get_adjustments_in_range`, and other incoming
AdjustmentReader's, (e.g. the roll based adjustment reader for continous
futures.) This patch should also make it easier for history and pipeline
to converge on a singular `load_adjustments` method.
> MAINT: Perspective offset for load adjustments.

- tests/test_continuous_futures.py
- zipline/assets/assets.py
- zipline/assets/continuous_futures.pyx
- zipline/data/continuous_future_reader.py
- zipline/data/data_portal.py
- zipline/data/history_loader.py
Add `.adj('mul')` and `.adj('add')` methods on ContinuousFuture, which
when used with `history`, will calculate and apply adjustments so that
the values are adjusted to account for discounts and premiums during
rolls.
Example usage in an algo:
```
from zipline.api import continuous_future
def initialize(context):
context.cl_add = continuous_future('CL', offset=0, roll='calendar').adj('add')
context.cl_mul = continuous_future('CL', offset=0, roll='calendar').adj('mul')
context.cl = continuous_future('CL', offset=0, roll='calendar')
schedule_function(print_history)
def print_history(context, data):
frame = data.history([context.cl, context.cl_add, context.cl_mul],
['price', 'sid'],
20,
'1d')
print 'unadjusted'
print frame.loc[:, :, context.cl]
print 'adjusted add'
print frame.loc[:, :, …
```
> ENH: Add adjusted history for continuous futures.

- tests/pipeline/test_quarters_estimates.py
- zipline/pipeline/loaders/earnings_estimates.py
This fixes a bug where we create adjustments for estimates based on where assets happen to fall in a set rather than using ordered assets. Not sure if this necessitates a test or what kind.
> BUG: create adjustments based on ordered assets instead of set

- setup.py
- tests/data/test_resample.py
- zipline/data/_resample.pyx
- zipline/data/resample.py
- zipline/testing/fixtures.py
The minute to session sampling reading was creating two DataFrame
objects, the first to hold the minute data, and then a second returned
by the `DataFrame.groupby` to sample down to sessions.
Instead use the arrays returned by the minute readers `load_raw_arrays`
and implement sampling logic which takes advantage that the minutes
being passed start with the first minute of the first session and end
with the last minute of the last session.
On my machine this takes the tests in `test/test_continuous_futures`
from ~4.0 to about ~0.1 seconds.
> PERF: Speedup minute to session sampling.

- zipline/data/history_loader.py
If a KeyError occurred in the adjustment logic, the exception would be
swallowed by the try block, which was intended to just check whether or
not there was an adjustment reader adjusted.
Discovered when some logic in a futures adjustment reader were failing
because of a mismatch of minute and session labels, which resulted in no
adjustments during windows when there should have been.
> MAINT: Prevent hiding of KeyError in adjustments.

- tests/data/test_resample.py
- zipline/data/resample.py
The last traded dt provided from the session bar reader which resamples
from minutes should provide a dt that is a session label, not one that
is at the minute frequency.
> BUG: Fix session from minute reader's last traded.

- tests/test_continuous_futures.py
Move dates queried near beginning of test data so that the range of data
covered does not extend beyond the beginning of the range.
i.e. the windows were covering 2016-01-25, which had no test data generated.
(Does not matter for the calendar based rolls, but is needed for volume
based rolls.)
Also, make room for having the first roll to be a day before the first auto
close by moving the first contracts auto close date back a day.
In preparation for testing volume rolls.
> TST: Make test dates aligned with test data.

- tests/data/test_us_equity_pricing.py
- zipline/data/data_portal.py
- zipline/data/us_equity_pricing.py
Match the behavior of the minute bar reader, now that the session and
minute bar readers share a common interface.
isnull is slightly slower than checking against -1; however, n cases
where we check against illiquid trades in a tight loop, volume is
checked which is not using nan. The change here should be marginal with
regards to performance.
> MAINT: Return nan from daily bcolz get_value.

- tests/test_continuous_futures.py
- zipline/assets/assets.py
- zipline/assets/continuous_futures.pyx
- zipline/assets/roll_finder.py
- zipline/data/data_portal.py
Add roll style which takes the volume of the contracts into account.
If the volume moves from the front to the back before the auto close
date, the roll is put at that session.
Also, factors out some of the common logic shared with calendar based rolls.
> ENH: Volume based rolls for futures.

- zipline/data/history_loader.py
There have been cases where the requested start or end date is not in
the history calendar.
Add the beginning and of the calendar to the KeyError to give more
detail to figure out root cause.
> MAINT: Add more info to history calendar KeyError.

- etc/rebuild-cython.sh
OSX's find supports a different syntax for `-regex`. As a result the original regex doesn't match any files and successfully does nothing.
I've confirmed that this change works with and without `brew install findutils --with-default-names`
> DEV delete old *.c and *.so files with rebuild-cython.sh for Darwin/OSX

- tests/test_continuous_futures.py
- zipline/data/history_loader.py
Instead of using the difference between the session close of the front
contract before the roll and and the open of back contract on the
beginning of the roll, use the close of both at the end of the session
before the roll.
The closes of the session prior to roll is in lieu of settlement data.
> BUG: Use proxy for settlement on future adjustments.

- tests/test_continuous_futures.py
- zipline/assets/continuous_futures.pyx
This boundary case was exposed with internal fixture data which used a
continuous future with a contract chain of size one.
> BUG: Protect against contract offset at end of range.

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
Apply offset value when writing out the rolls in a continuous future
which is offset from the primary.
> BUG: Fix continuous future history with offsets.

- zipline/utils/calendars/trading_calendar.py
This will keep `opens`, `closes`, `early_closes`, etc to the
same pattern.
> MAINT: Restore @property decorator

- tests/pipeline/test_alias.py
- tests/pipeline/test_classifier.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_factor.py
- tests/pipeline/test_filter.py
- tests/pipeline/test_term.py
- zipline/lib/labelarray.py
- zipline/pipeline/classifiers/classifier.py
- zipline/pipeline/engine.py
- zipline/pipeline/expression.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/filter.py
- zipline/pipeline/graph.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
- zipline/pipeline/visualize.py
- zipline/testing/predicates.py
- zipline/utils/sharedoc.py
Also adds an `alias` method of terms which allows people to "name" an expression which makes it repr better.
> Add optimization pass for initial workspace

- tests/pipeline/test_filter.py
- zipline/pipeline/filters/__init__.py
- zipline/pipeline/filters/filter.py
This better reflects the intended usage of accepting a fixed set of
predetermined assets.
> MAINT: Rename `SpecificAssets` to `StaticAssets`.

- zipline/data/minute_bars.py
This is significantly faster than the previous approach of writing a new
ctable with a slice of the existing table.
> PERF: Use ctable.resize to speed up BcolzMinuteBarWriter.truncate

- tests/test_continuous_futures.py
- tests/test_history.py
- zipline/assets/roll_finder.py
- zipline/data/data_portal.py
- zipline/data/history_loader.py
- zipline/testing/fixtures.py
To support using a `DataPortal` and `HistoryLoader` in a notebook, allow
the prefetch length to be configurable, so that it can be set to 0.
Unlike backtesting where the prefetch is useful for repeated history
windows viewed from datetimes which are monotonically increasing by a
small amount, the notebook usage of history windows needs only to
retrieve the exact data needed for the window specified.
This patch also fixes some boundary conditions related to rolls and
adjustments which were uncovered by querying for the adjustments with an
end date near the end of the window.
> ENH: Allow configurable history prefetch length.

- zipline/utils/calendars/exchange_calendar_bmf.py
- zipline/utils/calendars/exchange_calendar_lse.py
- zipline/utils/calendars/exchange_calendar_nyse.py
- zipline/utils/calendars/exchange_calendar_tsx.py
For compliance with newer flake8 versions.
Should be no functional change.
> STY: Add space between import and open parens.

- zipline/_protocol.pyx
- zipline/assets/assets.py
Allow `ContinuousFuture` when checking for a single "asset".
This could be further improved by:
- Defininng a tuple of the `Asset`-like types OR making
`ContinuousFuture` and `Asset` share a common type (whether that is
`ContinuousFuture` inheriting from `Asset` or making `Asset` and
`ContinuousFuture` share a common type.)
- Make a `history` test which uses `BarData` + `ContinuousFuture`,
instead of just using the history loader directly from tests.
> BUG: Fix `data.history` with a single continuous future.

- zipline/_protocol.pyx
- zipline/assets/__init__.py
- zipline/assets/assets.py
Register equities, futures, and continuous futures to an `abc` which
signifies that the type is associable with data, and thus can be used in
a history context.
May want to use this in `check_parameters` for `BarData` methods, but
work would need to be done to make sure the error message still displays
the registered types.
> MAiNT: Add a pricing data shared abc.

- tests/test_continuous_futures.py
- zipline/data/continuous_future_reader.py
- zipline/data/resample.py
Use `roll_style` not `roll`.
Also, add test case to cover using the session bar reader `get_value`,
by adding a test which uses `close`, since only `contract` was being
exercised, which does not exercise the session daily bar reader.
> BUG: Fix bad attribute lookup on session continuous future reader.

- tests/test_continuous_futures.py
- zipline/assets/assets.py
The end date of the last contract with a sufficient start date was being
used for the continuous future overall end date; however the end date of
that contract (which is the last day for which there is data for the
contract) is not necessarily the greatest end date out of all contracts.
It is possible for the furthest out contract to have some, but very
few, trades before it is more actively traded. Which would give it a
start date within in the range of the simulation, but an end date is
earlier than the other contracts which are active during the simulation.
This bug would result in `nan`s when getting the current price because
of the `end_date` check in `get_spot_value`. When the current simulation
time was greater than the `end_date` of the last contract the condition
which guards …
> BUG: Fix continuous future end dates.

- zipline/data/history_loader.py
The use of `slice_indexer` on all market minutes was taking about 110ms on my
development machine.
This change to getting the start and end indices changes the entire `_calendar`
method to take 10ms on the same machine.
Noticed while creating a `HistoryLoader` in a notebook context.
> PERF: Speed up retrieval of HistoryLoader calendar.

- zipline/utils/api_support.py
outside of a running simulation. Previously, an AttributeError was
raised.
The goal here is to make the situation clearer for developers, for example: https://github.com/quantopian/zipline/issues/1541 and https://github.com/quantopian/zipline/issues/448#issuecomment-249312347
What do folks think of the message?
> ENH: An improved error message when calling zipline api functions

- zipline/data/continuous_future_reader.py
The rolls are already calculated and assigned to `rolls_by_asset` earlier in the
`load_raw_arrays` method, so remove the duplication.
The change should not affect results.
> MAINT: Remove duplicate get_rolls in reader.

- tests/data/test_minute_bars.py
- zipline/data/_minute_bar_internal.pyx
When the following conditions occur,
- a `nan` occurred after a half day (e.g. on the Monday after
Thanksgiving, where the Friday would be a half day.)
-data was written to the span between the early close and where the market close
would have been if it were not an early close session
- a `nan` also occured on the last minute of the early market session.
the exisitng implementation would incorrectly return a `nan` when requesting a
forward filled price.
The steps that caused this error were.
1. Request for `'price'` on the market open of the day after the early close.
2. `nan` is found for that minute
3. `get_last_traded_dt` is called, and finds a volume that occurs after the
early close. e.g. `18:47` when the market close was `18:00`.
4. The minute position for `18:47` is used, when …
> BUG: Fix minute bar last traded after half day.

- zipline/finance/slippage.py
Protect a case where data is written with a non-zero volume, but a 0/nan for the
OHLC values. The slippage model was relying on a non-zero volume implying that
there was a valid trade price for the corresponding bar. When there was a mismatch,
a transaction with a nan value was created, which would in turn propagate the
nan into portfolio value, which would then cause errors when the portfolio value
was used to size orders during rebalancing.
When data is fixed, can remove.
(Also may want to add behavior to minute bar writer to ensure that 0 volumes
always have corresponding nan ohlc.)
> TMP: Add temporary fix for transactions with nan fill prices.

- zipline/data/minute_bars.py
Previously, if input to the BcolzMinuteBarWriter had the first bar on a
non-trading minute, the next trading session would be considered the
"first day" in the input. Now, we consider the previous trading session
the "first day".
The intention is to correctly associate minutes after official trading
hours on half days with session that closed early, not the following
session (a future improvement here would be to not accept minutes
outside trading hours).
> MAINT: Improve minute writer handling of non-trading minutes

- tests/pipeline/test_technical.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/technical.py
- zipline/utils/math_utils.py
These factors will be used in Quabbin and might be useful to everyone in the community.
> ENH: Add MACD, MA, and AnnVol as built in factors

- tests/test_continuous_futures.py
- zipline/assets/continuous_futures.pyx
Fix multiple errors when attempting to generate rolls for futures which do not
roll month to month, e.g. the Eurodollar.
These errors were caused by logic that always incremented from contract to
contract by delivery month, with errors when the next contract was not part of
the quarterly roll chain and thus had not yet begun trading even though the
previous contract had autoclosed. Instead, filter out these contracts and only
allow contracts that have begun trading before the previous contract's autoclose.
This is in lieu of a more explicit specification of quarterly rolls.
> BUG: Support futures which do not roll month to month.

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
Convert the end minute to the its session label before calling `_active_contract`,
otherwise the volume roll finder's attempt to use the session bar reader fails
due to a non-session label Timestamp.
> BUG: Fix 1m history for volume rolls with adjustments.

- tests/test_continuous_futures.py
- zipline/assets/assets.py
- zipline/assets/continuous_futures.pyx
- zipline/finance/trading.py
- zipline/testing/fixtures.py
To support contracts such as `PL` which should roll from F->J->N->V, add the
ability to pass a predicate function to the ordered contract chain contstrution
which returns `True` if the contract is allowed in the chain.
> ENH: Allow future chains to only use certain delivery months.

- docs/source/release-process.rst
When following the release guide, installing from testpypi using the
`-i` flag failed on my, and at least one other's, development machines.
The cause of the failure appears to be that pip would look for packages,
such as `LogBook` or `pandas` on `testpypi`. However many dependencies
do not have versions that meet our version criteria. (e.g. pandas does
not have a version between 0.16.0 and 0.18.0 on testpypi.)
Instead, use `--extra-index-url` so that other packages can use `pypi`
as a fallback server, instead of being limited to `testpypi`.
> DOC: Update testpypi install command

- zipline/assets/roll_finder.py
Instead of maintaining a separate index into the sessions index, use the `.freq`
member of the sessions index for decrementing to the current session and finding
the previous session.
> MAINT: Use session index freq for loop logic.

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
For futures that behave like GC, use the latest roll as the back contract when
walking backwards over the window, so that when the front contract is skipped
because it never has more volume between its auto close date and the previous
auto close date, the back contract which did have volume is still used when
making comparisons to construct the chain.
> BUG: Allow rolls to skip over contracts.

- zipline/pipeline/factors/technical.py
Docstring for `AnnualizedVolatility` generated incorrectly formatted html. This should fix that.
> DOCS: Minor (but build breaking) docstring fix

- tests/pipeline/test_quarters_estimates.py
- tests/test_algorithm.py
- tests/test_blotter.py
- zipline/algorithm.py
- zipline/finance/blotter.py
- zipline/finance/order.py
- zipline/test_algorithms.py
- zipline/testing/__init__.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
- zipline/utils/calendars/calendar_utils.py
Adds `order_batch` to the blotter and factors out ordering helper methods, so one can generate the orders and give them to `order_batch`.
> Order batch

- zipline/data/us_equity_pricing.py
Fixes a bug where dataframes being returned were creating US/Eastern timestamps out of the ints, potentially changing the date returned to be the date before (at 19 hours).
```python
>>> dt = datetime.datetime(2017, 1, 4, 0, 0)
>>> today_date_epoch = int((dt.date() - datetime.date(1970,1,1)).total_seconds())
>>> today_date_epoch
1483488000
>>> datetime.datetime.fromtimestamp(today_date_epoch)
datetime.datetime(2017, 1, 3, 19, 0)
```
With UTC, the timestamp is now essentially being created like the following:
```python
>>> datetime.datetime.utcfromtimestamp(today_date_epoch)
datetime.datetime(2017, 1, 4, 0, 0)
```
> BUG: Datetimes should be converted in utc.

- zipline/pipeline/factors/technical.py
Very small bug fix: creating a IchimokuKinkoHyo factor raises an exception because the default inputs  are not in line with the factor's documentation
> BUG: IchimokuKinkoHyo techinical factor has wrong default inputs

- tests/test_bar_data.py
- tests/test_restrictions.py
- tests/utils/test_pandas_utils.py
- zipline/data/data_portal.py
- zipline/lib/labelarray.py
- zipline/testing/core.py
- zipline/utils/input_validation.py
This is a step towards upgrading from flake8 `2.4.1` -> `3.2.1`.
Beyond general keeping up-to-date clean living, I am interested in upgrading to `3.2.1` because the current version of the Emacs `flycheck-mode` integration with `flake8` requires >= 3.0 because it uses on the `--stdin-display-name` option.
From pep-0008:
```
Always use a def statement instead of an assignment statement that binds a
lambda expression directly to an identifier.
Yes:
def f(x): return 2*x
No:
f = lambda x: 2*x
The first form means that the name of the resulting function object is
specifically 'f' instead of the generic '<lambda>'. This is more useful for
tracebacks and string representations in general. The use of the assignment
statement eliminates the sole benefit a lambda expression can offer over an …
```
> STY: Use def statements instead of lambda assignment.

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
Add a method to open existing minute bar directory.
Remove need for a consumer that is editing an existing minute bars directory to
reread the values which should not change from the metadata.
Add a test to the append on new day and truncate, which would be the common
usage of this method.
Also, add `sorted` to truncate method. (Which was useful when testing the change with real data.)
> Easier open minute bars for append and truncate

- tests/pipeline/test_events.py
- zipline/pipeline/loaders/events.py
@mtydykov your change looks good.  I had two suggestions which I figured were easier to just implement in the form of a PR.
1. We can simplify the assertion for the empty data frame to not have do a bunch of fancy unstacking.
2. Added a few comments in the logic for unpacking events to explain why we're special-casing empty input.
> Events loader handle empty raw data pr review

- tests/test_algorithm.py
- tests/test_bar_data.py
- zipline/_protocol.pyx
- zipline/algorithm.py
Futures contracts can currently be entered into after their `auto_close_date`. This change prevents that as well as makes `can_trade` return `False` after the `auto_close_date`.
> Don't allow ordering assets after their auto close date

- tests/data/test_minute_bars.py
- zipline/data/minute_bars.py
When opening with a new `end_session`, i.e. opening for append, write the new
end session to the metadata.
Fixes an issue where the calendar on minute bar readers did not include the
recently appended day, causing reads on the last values to fail.
According, update append test to read a value, instead of checking table length.
> BUG: Fix end session metadata for minute bar writer.

- tests/test_perf_tracking.py
- zipline/finance/performance/position_tracker.py
Due to relying on the order of the multipliers dicts, algorithms which mixed futures and equities were hitting the wrong multipliers after closing a position because the closing asset was not being removed from the multipliers dicts.
> Multipliers were not removed when closing a position

- zipline/assets/assets.py
These methods became unused during the course of reworking futures to support
continuous futures.
> MAINT: Remove unused futures related methods from asset finder.

- tests/pipeline/test_adjusted_array.py
- tests/pipeline/test_adjustment.py
- tests/pipeline/test_blaze.py
- zipline/lib/adjustment.pyx
- zipline/pipeline/loaders/blaze/core.py
This PR fixes a bug in the blaze core loader where any type of column was acceptable in the baseline table but overwrites for deltas adjustments were assumed to be of type float64. Addresses https://github.com/quantopian/qexec/issues/12024. 
Major changes are:
- Adds `ObjectOverwrite` to the dispatching done in `choose_adjustment_type`, replacing the case where getting a non-float64/datetime64 would raise a `ValueError`. Updates `test_adjustment` tests accordingly.
- Uses `make_adjustment_from_indices` to create overwrites for deltas adjustments in the blaze core loader, allowing overwrites for any column type.
> Determine overwrite type dynamically

- tests/calendars/test_trading_calendar.py
- zipline/data/history_loader.py
- zipline/testing/fixtures.py
- zipline/utils/calendars/trading_calendar.py
- zipline/utils/pandas_utils.py
Three semi-related changes here:
1. Add `session_open` and `session_close` methods to `TradingCalendar`.  These produce the same data as `open_and_close_for_session`, but are more ergonomic when you only need one of the two dates.
2. Fixes a bug (introduced by me during the pandas 18 upgrade) where we were failing to raise an error when a history window is misaligned with the dates of the history loader's calendar.
3. Makes EQUITY_DAILY_BAR_LOOKBACK_DAYS default to EQUITY_MINUTE_BAR_LOOKBACK_DAYS when EQUITY_DAILY_BAR_SOURCE_FROM_MINUTE is set.
> Pricing fixture cleanups

- zipline/testing/predicates.py
makes comparing larger nested structures easier
> TST: assert_equal dispatch for tuples

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/utils/calendars/trading_calendar.py
- zipline/utils/calendars/us_futures_calendar.py
- zipline/utils/events.py
Change algorithms that use the futures calendar to run from 6:30am to 5:00pm instead of 24 hours. Minutely history calls will still return 24-hour data however.
> Change to a 10.5 hour futures calendar

- zipline/testing/core.py
If we have a test that's being called more than once (i.e. two
test cases, both subclasses of the same base test case, with
different setup but calling the same test), allow the subsequent
calls to re-consume the same params
> TEST: Allow parameter_space to work on repeated calls of test

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/finance/trading.py
- zipline/utils/run_algo.py
Capital base is included in the sim params, so we should define the
value there, or use the default.
This change also unifies the default capital base as 1e5, as was
previously defined in algorithm.py.
> MAINT: Removes unnecessary capital_base arg to TradingAlgorithm

- .travis.yml
- appveyor.yml
- ci/appveyor/install.ps1
(And print conda info on travis.)
Miniconda latest for python 3 now installs python 3.6 in the root environment, but win-64 anaconda-client 1.5.1 doesn't exist for python 3.6. So using python 2 in the conda root environment, even when building/running python3 in the test environment.
Fixes the appveyor py3 build error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
- anaconda-client 1.5.1* -> python 2.7*
- python 3.6*
```
> BLD: Pin python version of conda root env to python 2

- zipline/testing/fixtures.py
It is sometimes necessary to test invalid test data, for example in the case that there is missing pricing data. Instead of warning by default, make invalid data behavior configurable by the test if needed.
> ENH: Make invalid data behavior optional

- tests/pipeline/test_factor.py
- zipline/errors.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/filter.py
This factor is useful when the effects of spurious outliers to be mimized.
> ENH: Add winsorize factor

- zipline/pipeline/factors/factor.py
`ceil()` returns a float. `VisibleDeprecationWarning` is raised when using result to index into array.
> BUG: ceil returns float, int needed for array indexing

- zipline/lib/adjustment.pyx
Remove unused variables.
Add type for values used to access arrays.
> MAINT: Apply linter recommendations to adjustments module.

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/utils.py
Addresses an issue where values for 2 subsequent dates, d1 and d2, came in for the first time on d3 and had the same timestamp; because d1 happened to be in a later row than d2, `last_in_date_group` selected d1 to be the "latest" value for the next date in the index, which was d5. The fix for this issue is to sort the data on asof_date before we drop the asof_date column.
> Sort pipeline data on asofdate

- zipline/data/minute_bars.py
otherwise, the index could come out as a float because of the division ahead of it
> bugfix: convert index to int so that the pandas indexing doesnt fail

- tests/pipeline/test_filter.py
- zipline/pipeline/filters/__init__.py
- zipline/pipeline/filters/filter.py
Useful for avoiding the need to create `Asset` objects when sids are easier to use.
This is based off the existing implementation of `StaticAssets`, and `StaticAssets` is now implemented as a wrapper around `StaticSids`.
> ENH: Adds StaticSids pipeline filter

- docs/deploy.py
Should fix #1237.
I traced the call to `path()` down to this section of [path.py](https://github.com/jaraco/path.py/blob/master/path.py)
```
def __enter__(self):
self._old_dir = self.getcwd()
os.chdir(self)
return self
```
And changed our `deploy.py` to just do the same thing
> ENH: Remove path.py as its not a dependency

- zipline/data/_resample.pyx
- Instead of maintaining a separate `j` value, set the bounds of the range so
that `i` is the values emitted by the range.
- Change `close_loc` to `prev_close_loc` since the market close location is used
to ensure that the data index stops at the market open if the entire day is nans.
- Change the setting of `loc` to be done before the loop which check for nans,
instead of setting to the previous close loc at the end of the loop.
This prepares for a separate fix to prevent out of bounds access when the first
session has nans for all minutes.
This does not fix https://github.com/quantopian/zipline/pull/1721
The following is a potential fix:
```
--- a/zipline/data/_resample.pyx
+++ b/zipline/data/_resample.pyx
@@ -82,11 +82,13 @@ cpdef void _minute_to_session_close(intp_t[:] close_locs, …
```
> MAINT: Clear up naming and logic in resample close.

- tests/data/test_resample.py
- zipline/data/_resample.pyx
When calling `history` for `price` or `close`, it was possible that we would index into an array with a `-1`, and with `@wraparound(False)` this caused undefined behavior.
> Negative indexing in cython without wraparound

- tests/test_assets.py
- tests/test_continuous_futures.py
- zipline/algorithm.py
- zipline/api.pyi
- zipline/assets/assets.py
- zipline/assets/continuous_futures.pyx
Allow specifying an adjustment style as a parameter, e.g. `continuous_future('CL', offset=0, roll='volume', adjustment='add')` is equivalent to `continuous_future('CL', offset=0, roll='volume').adj('add')`
> Make continuous future adjustment style an argument

- tests/test_continuous_futures.py
- zipline/data/continuous_future_reader.py
- zipline/data/data_portal.py
Make sure the current contract of a continuous future is not `None` before calling `retrieve_asset` on it.
> Add safeguard if current contract of continuous future is None

- zipline/_protocol.pyx
Should be no functional change.
By making the raise on `if not isinstance` instead of doing a continue on `if
isinstance` (with a raise at the end of the loop if no 'good' conditions were
met'), the function should be more amenable to adding an additional validity
check, after the type check passes.
This is on the path to adding an additional validity checks parameter to
`check_parameters`, e.g. adding an 'is positive' check.
> MAINT: Prepare parameter check for adding an additional check.

- zipline/assets/asset_writer.py
Should fix #1626 after merging & then deploying docs
> DOC: Show exchange as required for equities

- zipline/assets/continuous_futures.pyx
This method is no longer needed as the `adjustment` field is now [passed as a parameter](https://github.com/quantopian/zipline/pull/1726).
> Remove ContinuousFuture adjustment method

- tests/data/test_resample.py
- zipline/data/resample.py
Instead of recursively calling `DailyHistoryAggregator.closes` until we find a non-nan close, we can instead call `load_raw_arrays` once, and find the value from the returned array.
> PERF: Avoid repeated recursive calls when getting forward-filled close

- tests/test_assets.py
- tests/test_continuous_futures.py
- zipline/assets/continuous_futures.pyx
It is possible for the first contract of a `ContinuousFuture` to have a start date which is after its auto close date. In that case the continuous future terminates immediately, giving it a premature end date. To handle this, throw out the first contract if it hits this case because it is not tradable anyway.
> OrderedContracts chain could sometimes terminate on first contract

- tests/pipeline/test_events.py
- zipline/pipeline/loaders/utils.py
- zipline/testing/core.py
Fixes:
1) A pandas bug whereby if `tz_localize(None)` is called on a non-sorted DatetimeIndex, some dates are pushed back an hour. The implications of this are that all loaders that use `normalize_timestamp_to_query_time` (e.g. the blaze core loader, the events loader, etc) could result in incorrect timestamps and thus data being surfaced early.
```
In [10]: d = pd.DatetimeIndex(['2013-12-30', '2013-06-01'])
In [11]: d.tz_localize('US/Eastern').tz_localize(None)
Out[11]: DatetimeIndex(['2013-12-30 00:00:00', '2013-05-31 23:00:00'], dtype='datetime64[ns]', freq=None)
```
2) A zipline bug where datetime arrays were not being properly compared in a testing utility.
> Fix zipline and pandas bug

- zipline/algorithm.py
- zipline/api.pyi
Use a default offset of `0` and default roll style of `volume`.
> Make certain continuous future arguments optional

- etc/requirements_blaze.txt
Bump blaze to a bug fix that fixes comparison of timestamps. In this bug, the server serialized timestamps incorrectly -- it appended tz to tz naive timestamps, which resulted in matching timestamps being missed.
> BLD: bump blaze

- tests/calendars/test_trading_calendar.py
- zipline/data/resample.py
- zipline/utils/calendars/trading_calendar.py
When retrieving the open and close for a given session, we only care about the scalar values, so using `DataFrame.at` instead of `DataFrame.loc` is significantly faster.
Also improves `MinuteResampleSessionBarReader` by only retrieving session close when we need just the close, instead of the open and close.
> Improve TradingCalendar perf with scalar-optimized accesses

- tests/calendars/test_trading_calendar.py
- zipline/data/resample.py
- zipline/utils/calendars/trading_calendar.py
- Adds `session_closes_in_range` method (along with `session_opens_in_range`) to `TradingCalendar` to allow vectorized retrieval of all values in a range of sessions.
- Improves code path for resampling a single session's worth of data (as is the case when calling `get_value`), since we don't actually need to look up the close minute.
> PERF: Optimize session close lookups in MinuteResampleSessionBarReader

- tests/test_continuous_futures.py
- zipline/assets/continuous_futures.pyx
If ever in the middle of a futures chain a contract auto closes before the start date of the next contract, the chain would end prematurely. Instead, set the current contract during that gap to be the next upcoming contract, essentially as a placeholder.
> Allow gaps between auto close and start date

- tests/finance/test_blotter.py
- tests/finance/test_commissions.py
- tests/finance/test_slippage.py
- tests/test_algorithm.py
- tests/test_data_portal.py
- tests/test_finance.py
- tests/test_perf_tracking.py
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/errors.py
- zipline/finance/blotter.py
- zipline/finance/order.py
- zipline/finance/performance/period.py
- zipline/finance/performance/position.py
- zipline/finance/performance/position_tracker.py
- zipline/finance/performance/tracker.py
- zipline/finance/transaction.py
- zipline/protocol.py
- zipline/testing/core.py
- zipline/utils/factory.py
The original point of this branch was to fix a bug in how we calculate a position's cost basis for futures (it wasn't taking into account contract size).
This led me into a refactoring that I had been meaning to do for a while, in which all mentions of `sid` were removed in favor of `asset` (the `sid` properties were almost always `Asset` objects already).
> Assets everywhere ... and a futures fix.

- zipline/assets/continuous_futures.pyx
The March, June, September, and December contracts for these futures
contain most of the trading activity, so we exclude the other more
sparsely traded contracts from the chain.
> MAINT: Use a quarterly cycle for JY, CD, AD, and BP continuous futures

- tests/finance/test_blotter.py
- tests/finance/test_commissions.py
- tests/finance/test_slippage.py
- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/errors.py
- zipline/finance/blotter.py
- zipline/finance/commission.py
- zipline/finance/constants.py
- zipline/finance/slippage.py
- zipline/testing/slippage.py
- zipline/utils/dummy.py
This PR adds the actual slippage and commissions models for futures, taking advantage of the infrastructure built [here](https://github.com/quantopian/zipline/pull/1738).
In terms of the API, the `set_slippage` and `set_commission` functions now accept an `equities` argument and a `futures` argument for setting two different models according to the type of asset being traded. Furthermore, the `SlippageModel` and `CommissionModel` classes have been broken out into Equity and Future subclasses. This is to help enforce that the models passed to these new parameters are of the correct type. For example, the `equities` parameter for `set_slippage` must inherit from `EquitySlippageModel`, while the `futures` parameter must inherit from `FutureSlippageModel`.
For futures commissions, we use …
> Add slippage and commission models for futures

- tests/finance/test_slippage.py
- zipline/finance/slippage.py
If the computed transaction volume is less than 1 just bail.
> Futures slippage model could have zero transaction volume

- tests/data/test_us_equity_pricing.py
- tests/test_algorithm.py
- zipline/data/us_equity_pricing.py
Previously, a dataframe pass into BcolzDailyBarWriter.write that was
missing an expected session between its first and last sessions would be
written incorrectly. Upon converting the dataframe to a ctable, the
values for all days following the gap would be shifted backwards, and
nans would be shifted in at the end.
This commit handles the issue by reindexing the input dataframe against
the expected sessions, which will fill any gaps with nans at the
expected index. Also adds BcolzDailyBarWriterMissingDataTestCase to
catch any regressions.
> MAINT: Handle gaps in input to daily bars writer

- tests/finance/test_slippage.py
- zipline/finance/slippage.py
- zipline/testing/slippage.py
- `process_order` is a method. Call super's `__init__` to set up base state
- Fixed abstractness of `MarketImpactBase`
> Slippage cleanup

- tests/finance/test_transaction.py
- zipline/finance/transaction.py
The `repr` for a Transaction object now looks like:
`Transaction(order_id=20, sid=Asset(0), dt=2015-01-01 00:00:00, amount=10, price=50)`
> MAINT: Add better repr for transactions

- tests/data/test_resample.py
- tests/test_api_shim.py
- tests/test_benchmark.py
- tests/test_continuous_futures.py
- tests/test_history.py
- zipline/_protocol.pyx
- zipline/algorithm.py
- zipline/data/data_portal.py
- zipline/data/resample.py
- zipline/sources/benchmark_source.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
- Makes `ReindexBarReader.get_value` handle missing data, so errors won't be raised on valid futures minutes where the equities calendar is closed.
- `get_history_window` with '1d' now handles midnight on the futures calendar correctly, instead of interpreting it as a request for daily frequency data, by now  taking a `data_frequency` arg.
- Small fix for `_handle_minute_history_out_of_bounds`, which should be using `minute_to_session_label` instead of normalizing the date.
- Adds test coverage by creating subclasses of `DailyEquityHistoryTestCase` and `MinuteEquityHistoryTestCase` which use the 'us_futures' calendar.
> Fixes equity history calls on the futures calendar

- .gitattributes
- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/api.pyi
- zipline/test_algorithms.py
Replace `batch_order_target_percent` with `batch_market_order`.
The only downstream context that was using batch_order_target_percent
already had all necessary prices, so calling batch_order_target_percent
was wasteful.
> MAINT: batch_order_target_percent -> batch_market_order.

- tests/finance/test_commissions.py
- zipline/finance/commission.py
- zipline/finance/shared.py
- zipline/finance/slippage.py
This PR adds a feature for subclassing EquityCommissionModel and FutureCommissionModel together and getting the expected behavior that it supports both equities and futures. See https://github.com/quantopian/zipline/pull/1767 for reference on how this was done for slippage.
This PR also makes `PerTrade` support futures.
> Refactor commission model class hierarchies

- tests/pipeline/test_pipeline_algo.py
- tests/test_algorithm.py
- tests/test_examples.py
- tests/test_finance.py
- tests/test_perf_tracking.py
- tests/test_security_list.py
- tests/test_tradesimulation.py
- zipline/data/loader.py
- zipline/finance/trading.py
- zipline/testing/__init__.py
- zipline/testing/core.py
- zipline/utils/run_algo.py
to avoid a new trading env needing to download data unnecessarily
> TST: Don't require downloading of data for tests

- tests/calendars/test_nyse_calendar.py
- zipline/utils/calendars/trading_calendar.py
A TypeError exception was raised with message "Cannot join tz-naive with
tz-aware DatetimeIndex". Removing old unnecessary workaround in
`holidays_at_time` function (Pandas already fixed that before 0.18)
fixes this issue.
Should fix #1801.
> Fix bug in TradingCalendar initialization

- tests/finance/test_slippage.py
- zipline/finance/slippage.py
There is no way to safely evaluate equality between slippage objects as per https://github.com/quantopian/zipline/pull/1777#discussion_r114665366
> MAINT: Remove __eq__ implementation from slippage

- tests/test_data_portal.py
- tests/utils/test_math_utils.py
- zipline/data/history_loader.py
- zipline/lib/_windowtemplate.pxi
- zipline/lib/adjusted_array.py
- zipline/testing/fixtures.py
- zipline/utils/math_utils.py
Previously, all asset prices were being rounded to 3 decimal places because this is the most precision we ever needed for equities. Some futures however have tick sizes with precision less than 0.001, so we don't want to cut off those price values.
Since we already cutoff the decimal places for equities to three places by default (https://github.com/quantopian/zipline/blob/master/zipline/data/minute_bars.py#L55) the explicit rounding when reading is unnecessary anywhere. And futures prices should be already cutoff to the appropriate precision according to their `ohlc_ratios_per_sid` value.
> Do not explicitly round asset prices

- ci/make_conda_packages.py
Making this change because the build failed when we started building Python 3.5 packages for the first time; we were checking the Quantopian channel `main` label first to see if there is an existing built package for packages like `sortedcontainers` or `setuptools_scm`.
Order matters when passing `-c` flags to `conda build`. 
We've also been unnecessarily building packages in our CI builds because the URL we specified in `make_conda_packages.py` needed to be updated to just be the name of the channel and label.
> BLD: Swap conda build args to check CI label/channel first

- .travis.yml
We've been unnecessarily building packages in our CI builds because the URL we specified in `make_conda_packages.py` needed to be updated to just be the name of the channel and label.
When we pass in the specified channel via the `-c` flag, we can just say `channel_name/label/label_name`, in this case it's `quantopian/label/ci`, so we skip building existing packages.
> BLD: Modify conda label for Travis CI

- tests/test_benchmark.py
- zipline/algorithm.py
- zipline/sources/benchmark_source.py
To allow the BenchmarkSource class to be more easily used in contexts other than
a TradingAlgorithm, remove the TradingEnvironment as an argument to the
benchmark source.
Instead:
- Pass a benchmark Asset, instead of a bencmark sid; so that the asset_finder
does not need to be passed to the benchmark source.
- Pass the pre-calculated benchmark_returns instead of an env,
which contains the benchmark_returns; a consumer can let the benchmark_returns
stay as the default of `None` when using an asset.
We may want to further refactor and make two different classes, instead of
relying on a combination of existence/non-existence of benchmark_asset and
benchmark_returns. That refactoring should be easier to do with this change.
> MAINT: Remove environment as an argument to benchmark source.

- zipline/data/treasuries.py
After moving around on the Federal Reserve site, the link that we're using for `get_treasury_data()` isn't valid (x-ref https://github.com/quantopian/zipline/issues/1817), and so I removed `label=omit` from the URL params to make a working link.
You can see that the same URL is generated when going to `https://www.federalreserve.gov/datadownload/`, clicking on "Selected Interest Rates (H.15)", clicking "Treasury Constant Maturities" and then clicking "Go to Download", lastly click "Download file".
Full URL `https://www.federalreserve.gov/datadownload/Download.aspx?rel=H15&series=bf17364827e38702b42a58cf8eaa3f78&lastobs=&from=&to=&filetype=csv&label=include&layout=seriescolumn&type=package`
> MAINT: Modify broken treasury data link

- etc/conda_build_matrix.py
- setup.py
Add this version to the Conda build matrix and to the setup.py file.
> Add missing Python 3.5 references (now supported)

- docs/source/appendix.rst
- docs/source/bundles.rst
- docs/source/whatsnew/1.0.2.txt
- tests/pipeline/test_filter.py
- tests/pipeline/test_term.py
- zipline/data/data_portal.py
- zipline/data/minute_bars.py
- zipline/lib/normalize.py
- zipline/pipeline/api_utils.py
- zipline/pipeline/engine.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/factors/statistical.py
- zipline/pipeline/factors/technical.py
- zipline/pipeline/graph.py
- zipline/pipeline/visualize.py
- zipline/testing/core.py
- zipline/utils/api_support.py
- zipline/utils/cache.py
- zipline/utils/calendars/trading_calendar.py
- zipline/utils/deprecate.py
- zipline/utils/functional.py
- zipline/utils/input_validation.py
- zipline/utils/preprocess.py
- zipline/utils/sharedoc.py
This pr fixes several typos in docstrings that specify non-existent sphinx sections. For example `Usage` and `Example` have been converted to `Examples`. `Note` has been converted to `Notes`. `Returns:` has been converted to `Returns`. Several minor fixes, for example if there are not enough formatting `~` under a title.
Create a `Pipeline` subsection for built-in factors. The factors have been organized alphabetically.
Include Factor methods such as `winsorize` in documentation. Currently only some are listed and they are all useful to users.
Include documentation and subsection for `PipelineEngine`.
Two non-existent classes have been removed `zipline.assets.AssetFinderCachedEquities` and `zipline.pipeline.data.EarningsCalendar`.
> Add engine docs

- tests/test_examples.py
- zipline/utils/paths.py
The `ensure_file` call doesn't actually update the current modified time of the file that we touch, so had to add a util function that calls `os.utime()`; this will fix broken tests as well.
> TST: Update modified time of market data in test_examples

- zipline/assets/asset_writer.py
We had previously reduced this value in https://github.com/quantopian/zipline/commit/ee9c79a6f849e4d7e9035bc58977bce125ef6f5e as a workaround, but it should no longer be an issue.
> MAINT: Define default end_date in assets.db as max int64, for clarity

- tests/test_algorithm.py
- zipline/protocol.py
- zipline/test_algorithms.py
1. Add a property to `context.portfolio` that computes the current portfolio's weights of each of its holdings. That is, for every equity/future currently held, calculate its value held divided by the portfolio's total exposure.
~~2. Add a rolling realized CVaR metric to algorithms which looks at the past 200 days of day-to-day returns and averages the bottom 5% of those values.~~ To be added in a following PR.
> Add portfolio weights method to algorithms

- README.rst
- docs/source/beginner-tutorial.rst
- docs/source/development-guidelines.rst
- docs/source/index.rst
- docs/source/release-process.rst
Builds on https://github.com/quantopian/zipline/pull/1807, fixes https://github.com/quantopian/zipline/issues/1700, and fixes #495
This change is a step to remove information from the wiki as I believe [zipline.io](zipline.io) is a better place to add something like dev guidelines (along with other things)
One thing I'd like to update/add is a `Contribution Requests` section for larger contributions; and then start using the `Beginner Friendly` label more for smaller issues or issues that are clearly mapped out for how to fix them (which would require pruning of existing issues)
We could add a lot more content to this.
**Probably worth a separate PR:**
- Add a `Contributions Request` Section for larger projects
- Add an FAQ/Frequent Dev Issues and how to fix them
> DOC: Add development guide .rst to zipline.io

- tests/pipeline/test_factor.py
- zipline/pipeline/factors/factor.py
Marking a multi-output factor as window safe does not currently result in window_safe output terms.
> ENH: Match window_safe status of multi output factor with factor

- etc/requirements_dev.txt
It's a recent (to zipline) requirement of flake8.
> DEV: Pin configparser version

- tests/test_assets.py
- zipline/assets/_assets.pyx
x-ref https://github.com/quantopian/zipline/issues/1675
This change shortens the `__repr__` method for `Asset`, and uses the same repr for different Asset classes (e.g. Futures and Equities). 
Only concern I have here is the comment from Eddie and others on the Futures repr:
> MAINT: Shorten __repr__ for different assets

- tests/pipeline/test_factor.py
- tests/pipeline/test_technical.py
Technical factors are tested in `test_technical.py`. This pr moves the RSI tests into that file.
Test that RSI is equal if the returns series is the same, though prices may differ.
Test that RSI is 100 when close prices increases for 14 days.
Test that RSI is 0 when close prices decrease for 14 days.
> TST: Test RSI edge behavior

- tests/data/test_minute_bars.py
- zipline/data/bar_reader.py
- zipline/data/minute_bars.py
Replaces the IOError raised by bcolz, which isn't very informative, with
NoDataOnDate.
> MAINT: Improve error when missing bcolz file for a sid is missing

- etc/docker_cmd.sh
Alleviates the symptoms noted in #1838.
> Add '--allow-root' to jupyter command to avoid error starting container.

- zipline/pipeline/loaders/blaze/_core.pyx
Use float64_t instead, since `isnan` is only used when the array's
dtype kind is `'f'`.
Fixes this compilation error:
```
zipline/pipeline/loaders/blaze/_core.pyx:30:16: 'floating' is not a type identifier
```
> BUG: Fix reference to floating type.

- tests/pipeline/test_downsampling.py
- zipline/pipeline/engine.py
When an asset stops existing partway through the downsample period we can get different results for rank (and demean and friends) on the same day if we start the pipeline inside the same downsample period but after the asset stopped existing.
> BUG: fix downsampled rowwise reductions

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
- zipline/testing/fixtures.py
The `VolumeRollFinder` failed get the active contract when using a daily bar reader.
> Check contract exists when using futures daily bar reader

- tests/test_algorithm.py
- tests/test_bar_data.py
- zipline/_protocol.pyx
- zipline/gens/tradesimulation.py
Now that the futures calendar does not run for 24 hours, it makes more sense for futures to auto-close at the end of the day (5pm) rather than midnight UTC. This PR moves the auto-close execution to the end of day _on_ the auto-close date, rather than the night before it. This means that you _can_ trade futures on their auto-close dates now.
> Change auto close to happen at session end

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
In the volume roll finder, we look up to a week back from the given date (called the grace period) where we look for double volume flips. It was possible that if the back contract had not started yet in the past week, an exception was thrown.
@yankees714 Mind taking a look? This is a follow up fix to https://github.com/quantopian/zipline/pull/1892. In that first fix we checked existence of the contracts before calling `get_value`, but we also call `get_value` later on that needs the same check.
> No data before date bug in volume roll finder

- tests/test_continuous_futures.py
- zipline/assets/continuous_futures.pyx
- zipline/assets/roll_finder.py
@yankees714 From what we discussed yesterday. The failing contract was 'EL', which is on a quarterly cycle.
> Still hitting NoDataBeforeDate edge cases

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
It looks like we are already handling the case of auto close dates being after end dates, both in [data.can_trade](https://github.com/quantopian/zipline/blob/master/zipline/_protocol.pyx#L500-L502) and [when ordering](https://github.com/quantopian/zipline/blob/master/zipline/algorithm.py#L1374). So this (the roll finder) is the only other spot I know of that needs this change.
> Need to handle case of auto closing after end date

- zipline/pipeline/factors/statistical.py
As far as I can tell, RollingLinearRegressionOfReturns is window safe, but is not marked as such, preventing it from being used in CustomFactor classes.  I have not tested building zipline with this one-line change, but I successfully subclassed RollingLinearRegressionOfReturns on Quantopian and verified that it functions without error.
> Set RollingLinearRegressionOfReturns factor to be window_safe.

- zipline/pipeline/loaders/blaze/_core.pyx
- zipline/pipeline/loaders/blaze/core.py
The primary use case for this is aliasing the `asof_date`, `sid`, or `timestamp` columns without copying the data at read time.
> Allow column names to be different from the underlying expression

- tests/pipeline/base.py
- zipline/__main__.py
- zipline/assets/asset_db_migrations.py
- zipline/pipeline/classifiers/classifier.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/expression.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/mixins.py
- zipline/testing/core.py
- zipline/utils/api_support.py
- zipline/utils/compat.py
- zipline/utils/deprecate.py
- zipline/utils/input_validation.py
- zipline/utils/memoize.py
- zipline/utils/preprocess.py
- zipline/utils/sentinel.py
- Add compat function for `functools.wraps`.
- Add `is_sentinel` check.
- Add docstrings to some pipeline methods.
> MAINT: Updates for better docs generation.

- zipline/data/minute_bars.py
A cache of 1550 allows us to have a tradeable universe of 1500 assets without
destroying ourselves every rebalance.
> ENH: Grow minute file cache to 1550 by default.

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
In `get_contract_center` of the `VolumeRollFinder`, we only look at a single date when trying to determine what the current contract is. This means that when deciding between the given front and back contracts we just choose the one with the higher volume. Since this method has no knowledge of any other dates, it can potentially flip flop on the current contract from day to day. This means that getting the active contract on a single date needs knowledge of the rolls of surrounding dates.
This symptom of seeing flip-flopping rolls could also be seen in history calls due to appending the current contract to the last day here: https://github.com/quantopian/zipline/blob/master/zipline/data/data_portal.py#L811
The one-off changes to the dates in the test are a result of …
> Volume roll current contracts could flip back and forth

- tests/test_continuous_futures.py
- zipline/assets/roll_finder.py
- zipline/data/continuous_future_reader.py
This fixes a bug with the edge case where:
- A contract (C_0) in the chain has an auto-close date equal to the `end` date passed to get_rolls
- The contract following C_0 (C_1), is *not* the active contract relative to the contract after it (C2), e.g. C_1 has lower volume than C_2, etc.
In this case, we need to roll from C_2 back to C_0, in which we would previously jump to the day following C_0's auto-close date. However, in this edge case, that would be outside the desired window (past `end`). Instead, in this case, we'll jump to `end` instead.
Also includes some cosmetic cleanup.
> BUG: Handle rolling to contract with auto-close date outside window

- docs/source/install.rst
I added information about how to use conda envs to install Zipline. (x-ref [#1901](https://github.com/quantopian/zipline/issues/1901))
> DOC: Add info about using a conda envs for installs

- README.rst
- docs/source/beginner-tutorial.rst
There was a wrong link and fixed the link.
The round bracket which does not have the corresponding one existed and I fixed it.
> DOC: Fix a link and typo

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/_core.pyx
- zipline/utils/pandas_utils.py
We need to keep track of the asof date stored at index 0 because once we convert date-space to index-space, we cannot disambiguate data that falls before the start of the window. This change fixes a problem where we have an adjustment for a data point from before the first data in a pipeline window which was overwriting a more recent asof date that was written at index 0.
> fix blaze core loader adjustment application for stale data

- docs/deploy.py
- docs/source/appendix.rst
For https://github.com/quantopian/zipline/issues/1941
@FreddieV4 Will you confirm that running deploy.py from this branch removes the yahoo bundle html for you? Since this is about stale files, I want to make sure I didn't pollute my test env.
> Clean docs

- tests/data/test_resample.py
- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/data/resample.py
Fixes #1356, #1629.
New function `zipline.data.resample.minute_panel_to_session_panel`.
> BUG: Fix daily history for minute panel data backtest

- tests/test_algorithm.py
- tests/test_tradesimulation.py
- zipline/algorithm.py
To fix the failing test on AppVeyor, break reference cycles from:
`TradingAlgorithm -> PerformanceTracker -> Portfolio -> TradingAlgorithm`
and
`TradingAlgorithm -> Portfolio -> TradingAlgorithm`
since these objects hold reference chains to `DataPortal -> SQLiteAdjustmentReader -> connection to adjustments db file`, and that file lives in a temp directory that we can't delete on windows.
> Clear perf tracker

- zipline/data/loader.py
The core of data/loader.py is the function load_market_data which
in turns calls functions ensure_benchmark_data and
ensure_treasury_data. These two functions are similar. Their
logger.info and logger.exception messages are slightly different
but their logger.warn messages are the same.
Having two different functions outputing the same warning can
be needlessly confusing when debugging.
This commit makes these two warnings explicitely different.
> DOC: Distinct warnings for benchmark and treasury fetchers

- tests/test_algorithm.py
- zipline/examples/buy_and_hold.py
- zipline/examples/buyapple.py
- zipline/examples/dual_ema_talib.py
- zipline/examples/dual_moving_average.py
- zipline/examples/momentum_pipeline.py
- zipline/examples/olmar.py
- zipline/finance/commission.py
Change default commission to .001 to be consistent with the contest.
> ENH: Change default commission to .001

- tests/calendars/test_trading_calendar.py
- tests/pipeline/test_events.py
Using a non-integer number instead of an integer will result in an error in the future. Should not break backwards compatibility. Should remove related `VisibleDeprecationWarning` warnings.
Also, a step forward to allow upgrading Pandas version to >=0.19. (#1975)
> DEP: Avoid float type index (expected int)

- tests/test_assets.py
- zipline/assets/asset_db_migrations.py
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
- zipline/data/us_equity_pricing.py
- zipline/utils/sqlite_utils.py
Make the AssetFinder fail with a clearer error if you construct and
AssetFinder pointing to a file path that doesnt exist.
The current implementation fails with:
```
InvalidRequestError: Could not reflect: requested table(s) not available in sqlite:///<filepath>
```
which makes it look like the error was that the db was corrupted, when
the actual error was just that the file didn't even exist. This is made
worse by the fact that sqlite3 will actually create an empty file when
you call `connect`, which further propagates the appearance of having
previously had a bad file.
> ENH: Fail better on AssetFinder(nonexistent_path).

- .travis.yml
- appveyor.yml
- ci/appveyor/install.ps1
- ci/make_conda_packages.py
- conda/0_sortedcontainers/bld.bat
- conda/0_sortedcontainers/build.sh
- conda/0_sortedcontainers/meta.yaml
- conda/1_setuptools_scm/bld.bat
- conda/1_setuptools_scm/build.sh
- conda/1_setuptools_scm/meta.yaml
- conda/alembic/bld.bat
- conda/alembic/build.sh
- conda/alembic/meta.yaml
- conda/bcolz/bld.bat
- conda/bcolz/build.sh
- conda/bcolz/meta.yaml
- conda/cyordereddict/bld.bat
- conda/cyordereddict/build.sh
- conda/cyordereddict/meta.yaml
- conda/empyrical/bld.bat
- conda/empyrical/build.sh
- conda/empyrical/meta.yaml
- conda/lru-dict/bld.bat
- conda/lru-dict/build.sh
- conda/lru-dict/meta.yaml
- conda/parameterized/meta.yaml
- conda/zipline/bld.bat
- conda/zipline/build.sh
- conda/zipline/meta.yaml
Updated versions of conda tooling
Install newer miniconda - This fixes the failing appveyor build on master.
Removed python 3.4 builds
> Conda updates

- tests/pipeline/test_statistical.py
- zipline/pipeline/factors/__init__.py
- zipline/pipeline/factors/statistical.py
- zipline/pipeline/term.py
This is a little over 1100x faster (!) than using
`RollingLinearRegressionOfReturns` on my machine.
Profiling output for a 1-month pipeline using both terms for with a
90-day lookback:
```
Tue Nov 21 02:05:48 2017    pipebench/perf/betas.stats
57724856 function calls (57689155 primitive calls) in 92.342 seconds
Ordered by: cumulative time
List reduced from 1212 to 3 due to restriction <'statistical.py'>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
21    0.612    0.029   95.461    4.546 statistical.py:194(compute)
172201    0.407    0.000   94.843    0.001 statistical.py:201(regress)
21    0.048    0.002    0.082    0.004 statistical.py:500(compute)
```
- The `compute` function that takes 95 seconds is `RollingLinearRetressionOfReturns`.
- The `compute` function …
> PERF: Add a new factor that just computes beta.

- README.rst
Fix Gitter link in README which currently takes to a 404 page on GitHub because it doesn't start with `https://`
> DOC: Fix Gitter link in README

- zipline/__main__.py
- zipline/data/data_portal.py
- zipline/utils/run_algo.py
Following the posts in #2018, should fix that issue
When we enter the `DataPortal()` setup in `zipline/zipline/data/data_portal.py(296)`, and call
```
self._first_trading_minute, _ = (
self.trading_calendar.open_and_close_for_session(
self._first_trading_day
)
```
We error at this point, if we're using a custom `TradingCalendar` because we actually only pass the `NYSE` calendar to the `DataPortal()` in `zipline/utils/run_algo.py` , so I changed the line to pass the calendar received from the CLI:
```
--- a/zipline/utils/run_algo.py
+++ b/zipline/utils/run_algo.py
@@ -134,7 +134,8 @@ def _run(handle_data,
first_trading_day =\
bundle_data.equity_minute_bar_reader.first_trading_day
data = DataPortal(
-            env.asset_finder, get_calendar("NYSE"),
+            env.asset_finder,
+ …
```
> MAINT: Pass calendars to DataPortal

- CONTRIBUTING.rst
Often times people will look for `CONTRIBUTING` files in the GitHub repos to find information for how to contribute to different projects. GitHub also encourages maintainers to have this file in their repo to raise higher community standards.
My hypothesis is that if we add this it'll also be another way for people to find their way over to the Development Guidelines and contribute.
> DOC: Add CONTRIBUTING.rst

- zipline/data/loader.py
We don't use this code anywhere that I'm aware of (grepped through Zipline in emacs)
> DEP: Remove old Yahoo code

- tests/finance/test_slippage.py
- zipline/finance/slippage.py
add `FixedBasisPointsSlippage` which models slippage as a fixed percentage of fill price
> ENH: add fixed percent slippage model

- zipline/data/bundles/quandl.py
Refactored some of the helper methods in the Quandl bundle to be more memory efficient. Memory peaks now at ~2500 MiB, with a constant memory consumption of ~2000 MiB. 
```
Filename: /Users/ernestoeperez88/zipline_master/zipline/data/bundles/quandl.py
Line #    Mem usage    Increment   Line Contents
================================================
186    167.3 MiB    167.3 MiB   @bundles.register('quandl')
187                             @profile
188                             def quandl_bundle(environ,
189                                               asset_db_writer,
190                                               minute_bar_writer,
191                                               daily_bar_writer,
192                                               adjustment_writer,
193 …
```
> PERF: Reduces memory footprint of Quandl WIKI Prices bundle

- zipline/data/loader.py
It's analytically superior to have a trading system synced to the latest market close than to lag the market waiting for treasury benchmark data.
This PR removes a hard-wired 2-day lag and combines the timeseries of the market and treasury benchmarks before filling data forwards and backwards along the timeseries.  This PR could be improved by averaging the treasury curve across points before backfilling the timeseries.
See comments to [#2031](https://github.com/quantopian/zipline/pull/2031) for more information.
> MAINT: Sync and fill benchmarks through latest trading day

- zipline/algorithm.py
- zipline/data/benchmarks.py
- zipline/data/loader.py
Got fed up with the breaking/removal of Google & Yahoo Finance APIs, and so since we've been using pandas-datareader to get data from those APIs I removed that dependency for when we want to get data for a specific benchmark (in this case `SPY`).
I changed our data source to IEX which will give us up to 5 years worth of data. It has really great documentation and seems like its a lot more reliable.
Should fix:
- https://github.com/quantopian/zipline/issues/2029
- https://github.com/quantopian/zipline/issues/2024
- https://github.com/quantopian/zipline/issues/1965
- https://github.com/quantopian/zipline/issues/2002
- https://github.com/quantopian/zipline/issues/2036
- https://github.com/quantopian/zipline/issues/2030
And should be better than PR …
> ENH: Use IEX Trading data instead of pandas-datareader

- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/api.pyi
- zipline/finance/controls.py
- zipline/test_algorithms.py
Similar to `MaxLeverage` create a `MinLeverage` control.  
`MinLeverage` takes a float as well as a deadline date.  `MinLeverage` validations will only happen after the algorithm has reached the deadline date.  This allows algorithms enough time to reach their min leverage because it may take time for them to have a non zero leverage.
> Create MinLeverage control

- tests/test_history.py
- zipline/data/data_portal.py
when we haven't seen any minute volume yet today
> BUG: Fixed daily price ffill using today's close

- zipline/data/bundles/quandl.py
Quandl's new API for the WIKI Prices dataset requires an API key.
Omitting the API key when running 'zipline ingest' caused:
HTTPError: HTTP Error 400: Bad Request
The new message asks for QUANDL_API_KEY to be set before
running the ingest process again.
> MAINT: Provides better error message when QUANDL_API_KEY isn't set

- tests/test_history.py
- zipline/data/data_portal.py
Otherwise we get back NaN.
The consumer of `history_start` is the later call to `self.get_last_traded_dt`, which returns `NaN` for non-trading days.
We were so close to catching this in the [previous PR](https://github.com/quantopian/zipline/pull/2074#discussion_r159711938)...
@ehebert @yankees714 Is `DataPortal.trading_calendar` good enough here, or do we need to look up a calendar per asset (and/or per reader)?
> BUG: get_last_traded_dt expects a trading day

- tests/events/test_events.py
- tests/test_algorithm.py
- zipline/algorithm.py
- zipline/utils/events.py
Otherwise algos crash with
```python
AttributeError: 'BeforeClose' object has no attribute 'cal' 
```
if a function is scheduled with, e.g.
```python
schedule_function(
func=my_func,
date_rule=date_rules.every_day(),
time_rule=time_rules.market_close(minutes=30) & time_rules.every_minute(),
)
```
> BUG: cal attribute of aggregate rules was not being propagated

- tests/test_labelarray.py
- zipline/lib/_factorize.pyx
- zipline/pipeline/loaders/blaze/_core.pyx
fix an issue where labelarray construction checked the size of the categories to compute the word size before injecting the missing value.
> labelarray boundary condition

- tests/test_algorithm.py
- tests/test_data_portal.py
- tests/test_history.py
- zipline/data/data_portal.py
BUG: On daily data, yesterday's adjustments were being applied
to yesterday's data from today's perspective, but no adjustment
happened between yesterday and today. They happened before yesterday's
open.
> Daily adjustments

- setup.py
than zipline supports.
For https://github.com/quantopian/zipline/issues/2102
> MAINT: Latest pandas-datareader requires a newer pandas version

- zipline/data/data_portal.py
- zipline/data/minute_bars.py
Improve performance for algorithms which consider and/or hold positions for 1000+ assets, especially liquid assets.
PERF: Optimize price for liquid assets.
When using `price`, the call to `last_traded_dt` for every value retrieved
became a noticeable bottleneck in algorithms which used over 1000 assets.
Instead of calling `last_traded_dt` before every retrieval of a `close` for the
`price` field, assume that `close` will retrieve a non-empty value, and then
forward fill if it is empty.
This change optimizes for the case of a tradeable universe which is predominately
composed of liquid assets.
EDIT: (The PR originally had a change to which column is used for the minute bar reader's `last_traded_dt`, but it was removed; to be implemented in a separate PR.)
> Improve price performance for 1000+ asset universes.

- zipline/data/minute_bars.py
Use a variable-size cache for minutely pricing data.
Increase the default cache size for close to 3000, since close prices
are used in many places in the simulation as the best-known price of
assets. This dramatically speeds up algorithms that read the prices of
many assets without ordering them.
> PERF: Variable-size minutely cache.

- tests/test_assets.py
- zipline/algorithm.py
- zipline/finance/metrics/tracker.py
This releases the benchmark source, which releases the data portal, which
releases the locks on the on disk files.
> MAINT: kill the metrics tracker at the end of the simulation

- zipline/testing/predicates.py
Adds a small helper to raise consistent looking error messages. I am not going to port the other functions in here to use this because I don't think it is worth refactoring the existing errors, I just want this to register an assertion somewhere else.
> make it easy to register new assert_equal dispatches

- tests/pipeline/test_factor.py
- zipline/pipeline/factors/factor.py
Fixes a bug where `Factor.winsorize` counted NaN values as being larger
than all other data points when calculating percentiles.
In practice, this means that most calls to `winsorize` did not clip
upper-percentile values and were more lenient than expected with
lower-percentile values.
> Fix winsorize bug

- docs/source/beginner-tutorial.rst
The DMA cross-over working example was missing an import of `matplotlib.pyplot` which led to a `NameError: global name 'plt' is not defined` when running in an iPython notebook.
> DOC: add import to beginner tutorial to fix NameError

- tests/test_history.py
- zipline/data/data_portal.py
Raise a value error on negative bar counts to prevent lookups ahead of
simulation time.
> BUG: Prevent negative lookup in history.

- zipline/algorithm.py
Are there any places where we allow orders to be filled on the same day / work in the same way that `instant_fill` used to work?
> DOC: Remove instant_fill docstring reference from TradingAlgorithm

- zipline/utils/events.py
I recently ran a backtest where I passed `date_rules.every_day` (uncalled) and got a unhelpful error message. This changes the message to be:
```
TypeError: invalid rule: <class 'zipline.utils.events.Always'> (hint: did you mean every_minute())
```
> ENH: improve error message if you don't call a rule

- zipline/pipeline/mixins.py
Support users have been looking for more detail on the NotImplementedError
__Note:__ New pull request after I accidentally killed the old by squashing the commit it referenced.
> MAINT: Adding more expressive error message on CustomTermMixin

- tests/pipeline/test_term.py
- zipline/errors.py
- zipline/pipeline/term.py
Make `ComputableTerm` check that the inputs are of type `Term`
1. Adds in a check to the `_validate` method
2. Adds in a new error `TermInputInvalid`
3. Adds a test ensuring the error is raised when an input of incorrect type is passed
> MAINT: Adding in validation for ComputableTerm input

- etc/requirements_dev.txt
- tests/test_assets.py
- zipline/assets/asset_writer.py
- zipline/assets/assets.py
- zipline/testing/predicates.py
This PR also adds two improvements to `assert_equal`:
1. On master, `assert_equal(Timestamp, Timestamp)` where the `tz` field is different raises a `TypeError` and doesn't show the `path` nor message. This now checks for this explicitly to fail with a better error.
2. `assert_equal(Asset, Asset)` is added to compare assets through `to_dict()`.
Regarding the dataframe index stuff in the asset db writer: as a consumer, I found it hard to know if I needed to set the index, and if so to what. `write_direct` supports both cases by normalizing a particular column per table to the index. If the given column is not present, it assumes it is already the index.
> AssetDBWriter.write_direct

- .travis.yml
The OSX builds are currently failing, and they appear to be failing to fetch
tags, which causes ``git describe`` to fail when invoked internally by
conda. The tentative culprit for this is that the OSX builds are using a newer
git version, which may have stopped fetching tags by default on --unshallow
clones.
> BLD: Fetch tags when unshallowing for conda.

- zipline/assets/asset_db_migrations.py
Remove records that no longer refer to equities from equity_symbol_mappings and
asset_router.
> BUG: Drop orphaned records from asset db in v6 downgrade.

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
When resolving data points to an output row index, we do not include records with a timestamp of _exactly_ the data query cutoff time:
https://github.com/quantopian/zipline/blob/5cda2ad542cb1eab02a84a6685dfb3d2adabd44e/zipline/pipeline/loaders/blaze/_core.pyx#L566-L572
however, when deciding which checkpoint to retrieve we would select anything less than **or equal to** the query start timestamp, after it had been adjusted to the data query cutoff time:
https://github.com/quantopian/zipline/blob/5cda2ad542cb1eab02a84a6685dfb3d2adabd44e/zipline/pipeline/loaders/blaze/core.py#L1043-L1047
If we had a checkpoint at exactly the data query time, we would have selected it meaning all of the data would have a timestamp of exactly the data query time. We only select base rows between the …
> checkpoint issue

- etc/requirements_dev.txt
@richafrank As per discussion earlier
These are no longer required by the version of matplotlib we're installing.
> MAINT: Removed tornado, backports.ssl-match-hostname, and certifi

- tests/data/bundles/test_core.py
- tests/data/test_daily_bars.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_us_equity_pricing_loader.py
- zipline/data/_equities.pyx
- zipline/data/bcolz_daily_bars.py
- zipline/data/hdf5_daily_bars.py
- zipline/pipeline/loaders/synthetic.py
The readers would previously error, they'll now return `nan`/`0` for these sids.
> MAINT: Make load_raw_arrays for daily bar readers handle unknown sids

- tests/test_assets.py
- zipline/assets/assets.py
- zipline/errors.py
- raise a `SameSymbolUsedAcrossCountries` if multiple assets across countries share the same symbol
- raise a `MultipleSymbolsFoundForFuzzySymbol` if multiple symbols are found when `fuzzy=True` is passed
> MAINT: update symbol lookup errors in AssetFinder

- conda/README.md
- conda/requests/meta.yaml
- etc/requirements.txt
There is a security vulnerability in the version of requests that is currently used by Zipline. It is unlikely that this vulnerability would impact any Zipline users -- it's only ranked moderate, and would require Zipline to fetch from a malicious web site or over a compromised network connection to be triggered -- but we should still upgrade for good hygiene.
> Upgrade to current version of requests package

- etc/requirements.txt
Includes a bunch of bug fixes and more support for enums.
> MAINT: Upgrade sqlalchemy to 1.1.18

- tests/events/test_events_nyse.py
- zipline/utils/events.py
The `week_start` date rule was incorrectly returning `False` for
`2018-12-31` on `NYSE` calendar.
The root cause of the bug was that the groupby used in
`TradingDayOfWeekRule.execution_period_values` was using the pairing
of `year` and `weekofyear`. This pairing grouped `2018-12-31` with
the first week of January 2018 (`2018-01-02`, `2018-01-03`, ...),
instead of with `2019-01-02`, `2019-01-03`, ...
This misgrouping occurred because the values of (year, weekofyear)
for `2018-12-31` are (2018, 1); however the other dates that are in the
same week as `2018-12-31` have a value of (2019, 1).
Since `2018-12-31` was misgrouped, the call to `nth(0)` would not select
it as the first of the week; since it appeared to be the last day of the
first week of `2018`
Instead, use the `isocalendar` method …
> BUG: Fix `week_start` when Monday precedes the New Year.

- tests/events/test_events_nyse.py
Follows up on https://github.com/quantopian/zipline/pull/2394#discussion_r244758588
> MAINT: Use a param name that is not the type builtin.

- tests/pipeline/test_domain.py
- zipline/pipeline/domain.py
The object timedelta arithmetic here fails in newer numpy. This should also be slightly more efficient for large date ranges.
> BUG: fix for newer pandas

- tests/pipeline/test_multidimensional_dataset.py
- zipline/pipeline/data/__init__.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/domain.py
- zipline/testing/predicates.py
- zipline/utils/formatting.py
Add the mechanism for defining a new `MultiDimensionalDataSet`. This is just shorthand for creating a collection of regular `DataSet`s that share the same columns.
I was going to add a test that executes a pipeline using this, but to do that I was writing a new one-off loader and dispatcher. At the end I realized that the test wasn't actually testing anything about `MultiDimensionalDataset`s, it was just testing the scaffolding I set up.
> MultiDimensionalDataSet

- zipline/testing/core.py
Fix error message when the function has parameters that are not provided by
parameter_space. I saw this when I removed a parameter from the decorator but
forgot to update the function signature.
> TST: fix parameter_space error handling

- tests/pipeline/test_blaze.py
- zipline/pipeline/loaders/blaze/core.py
When comparing exprdata, check `isidentical` on the constituent expressions instead of identity on the exprdata tuple itself. There are cases where we don't register the whole underlying table in a single call to `register_dataset` because it is difficult to group the columns this way. The equality of the exprdata object determines how we batch queries to the underlying, so we want to group them up as much as possible or we will be querying for the same `sid`, `asof_date`, and `timestamp` columns and re-aligning them for multiple columns.
> BUG: group exprdata by the expressions, not identity

- tests/pipeline/test_adjusted_array.py
- zipline/lib/adjusted_array.py
- zipline/lib/adjustment.pxd
To allow mapping the baseline and adjustment values when backed by a `LabelArray`.
This also make `value` attribute on `Adjustment` objects public, so that `map_labels()` can perform the mapping in place.
> ENH: Add AdjustedArray.map_labels

- zipline/pipeline/loaders/blaze/core.py
We use a nested dict in some places, this seems safer in the general case.
> use identity of odo_kwargs for id/eq

- zipline/pipeline/data/dataset.py
We need to add custom metadata for a new loader, so this is a new general interface to make it easier to do that without mutating the resulting dataset, which often doesn't work because of `_static_identity`.
> ENH: allow hooking dataset creation to add metadata or custom docstrings

- tests/data/test_adjustments.py
- zipline/__init__.py
- zipline/data/adjustments.py
- zipline/utils/functional.py
Fixes a bug where columns of adjustment db dataframes would come back as object
dtype when the table is empty.
> BUG: Ensure correct dtypes when unpacking empty dataframes.

- zipline/testing/predicates.py
- zipline/utils/numpy_utils.py
`numpy.testing.assert_array_equal` (`numpy==1.11.3`) doesn't handle datetime arrays correctly if either of the inputs contain `NaT`s.
To get around that, we can cast the arrays to ints using `view('int64')` and compare them. This is possible because 'NaT' maps to a reserved int.
> ENH: Update assert_equal(ndarray) to handle datetime arrays.

- setup.cfg
- tests/pipeline/test_dataset.py
- tests/pipeline/test_multidimensional_dataset.py
- zipline/pipeline/data/__init__.py
- zipline/pipeline/data/dataset.py
- zipline/testing/predicates.py
- zipline/utils/string_formatting.py
- Adds `DataSet.get_column` for looking up columns by name.
- Renames `MultiDimensionalDataSet` to `DataSetFamily`, and updates a bunch of docs and variable names to match. I think the docstring for DataSetFamily still needs work, but I want to ship the rename first before spending a long time wordsmithing.
> Get column and finalize names

- tests/pipeline/test_multidimensional_dataset.py
- zipline/pipeline/data/dataset.py
- zipline/utils/metautils.py
This change enables us to define "abstract" subclasses of DataSetFamily
which implement some set of attributes, but don't represent tangible
families of DataSets, and thus don't have meaningful values for
`extra_dims`.
Previously, all subclasses of DataSetFamily had to define non-empty
`extra_dims`. Subclasses were detected in DataSetFamilyMeta by checking
if the base classes of the class under construction were specified as
anything other than the designated sentinel value: if so, `extra_dims`
was transformed to an OrderedDict and checked for non-emptiness.
With this change, the metaclass instead checks for an `_abstract`
attribute of the class under construction: if it is found and set to a
truthy value, `extra_dims` (and `_SliceType`) is left unchecked and
unmodified. Regardless of its …
> ENH: Enable abstract DataSetFamily subclasses

- testhooks.py
- tests/pipeline/base.py
- tests/pipeline/test_hooks.py
- zipline/pipeline/engine.py
- zipline/pipeline/graph.py
- zipline/pipeline/hooks/__init__.py
- zipline/pipeline/hooks/delegate.py
- zipline/pipeline/hooks/iface.py
- zipline/pipeline/hooks/no.py
- zipline/pipeline/hooks/progress.py
- zipline/pipeline/hooks/testing.py
- zipline/testing/fixtures.py
- zipline/utils/compat.py
Adds a new `PipelineHooks` interface for instrumenting Pipeline executions.
Hooks can be passed to on a per-invocation basis to
`SimplePipelineEngine.run_pipeline`/`SimplePipelineEngine.run_pipeline`. They
can also be passed to `SimplePipelineEngine` to be applied to all pipeline
executions.
There are several implementations of the `PipelineHooks` interface, but the
only one useful to a user right now is `ProgressHooks`, which maintains a model
of the progress of the execution and hands it off to a publisher class to be
displayed to the user. The only interesting user-facing publisher is
`IPythonWidgetProgressPublisher`, which displays via an `ipywidgets` widget.
> Pipeline Engine Hooks

- zipline/testing/predicates.py
When comparing collections recursively, you may want to compare float arrays
with fuzzy equality, but not all objects (like str) work with almost equal, so
it will fail. We almost never use numeric-like object arrays, so it seems like
this should be the default behavior.
> BUG: don't use assert_almost_equal with object arrays

- tests/pipeline/base.py
- tests/pipeline/test_hooks.py
- zipline/pipeline/engine.py
- zipline/pipeline/graph.py
- zipline/pipeline/hooks/iface.py
- zipline/pipeline/hooks/no.py
- zipline/pipeline/hooks/progress.py
- zipline/pipeline/loaders/testing.py
- zipline/testing/fixtures.py
Fixes a bug where we miscomputed progress when the set of terms provided by
populate_initial_workspace changed between chunks.
The algorithm for accumulating progress is now as follows:
1. For each chunk, compute the percentage of the pipeline execution that the
chunk will account for (we already did this to determine how to weight the
contribution of each term).
2. Within each chunk, divide the total percentage to be completed by the number
of terms that will actually be loaded or computed. This required two
upstream refactors:
1. We now compute ``execution_order`` earlier and pass it to
``compute_chunk``.
2. We now filter out pre-populated terms from ``execution_order``.
3. For each term we load or compute, increment the total progress percentage by
the value computed in (2).
The end …
> BUG: Handle different counts of terms being computed between chunks.

- tests/pipeline/test_adjusted_array.py
- zipline/lib/adjusted_array.py
- zipline/pipeline/engine.py
When calling traverse, copy only if the `refcount > 1` meaning that we will re-traverse this array.
In `adjusted_array` don't copy the input data if it is already the proper dtype.
> ENH: remove some extra copies

- zipline/pipeline/data/dataset.py
The only use case we have for defining `__lt__` right now is for testing, so we can safely remove `total_ordering`. In python3:
```python
import six
from functools import total_ordering
@total_ordering
class OrderedMeta(type):
"""Metaclass that makes instances ordered by name.
"""
def __lt__(self, other):
return self.__name__ < other.__name__
class A(six.with_metaclass(OrderedMeta)):
pass
class B(six.with_metaclass(OrderedMeta)):
pass
print(A > B)
```
This raises `TypeError: expected 1 arguments, got 0`.
> Do Not Use `functools.total_ordering`

- tests/pipeline/test_column.py
- zipline/errors.py
- zipline/pipeline/data/dataset.py
Added rich comparison ordering methods to BoundColumn class to prevent users from comparing BoundColumn with anything.  Mainly to prevent the case where users accidentally write `EquityPricing.volume > 1000` instead of `EquityPricing.volume.latest > 1000`.
> ENH: BoundColumn comparisons now result in an error

- zipline/pipeline/loaders/blaze/core.py
The error raised by blaze when you do a field lookup with a nonexistent key on
an expression shows the repr of the expression, which contains the expression's
entire dshape. For exprs that are part of a very large tree, rendering the
dshape can take a significant amount of time.
Band-aid fix this for now by checking if the field exists before doing the
lookup. This saves 30-40 seconds (!) of startup time on Quantopian research.
> PERF: Avoid slow exception repr in blaze.

- zipline/pipeline/factors/events.py
- zipline/pipeline/factors/technical.py
Cleaned up the docstrings of certain built-in factors so they get displayed properly in the [Quantopian documentation](https://www.quantopian.com/docs/api-reference/pipeline-api-reference). Also added a brief example to the `BusinessDaysSincePreviousEvent` docstring.
Before:
After:
> DOC: Cleaned up docstrings on certain built-in pipeline terms.

- tests/pipeline/test_engine.py
- zipline/pipeline/engine.py
- zipline/utils/pandas_utils.py
Fixes a bug where running chunked pipelines containing string columns would
fail if some of the chunks were completely empty. We failed because the empty
chunks would have different dtypes (all `object`) than the non-empty chunks,
because pandas can't determine a dtype for an empty DataFrame.
We fix the bug by filtering out empty chunks before concatenation.
> BUG: Fix bug concatenating empty chunks with strings.

- zipline/assets/asset_writer.py
- zipline/assets/assets.py
as per https://bugs.python.org/issue32012
"Disallow ambiguous syntax f(x for x in [1],)"
> MAINT: Fix SyntaxError in python 3.7+

- conda/iso4217/meta.yaml
- conda/python-interface/meta.yaml
- etc/requirements.txt
- tests/data/test_adjustments.py
- tests/data/test_daily_bars.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_international_markets.py
- tests/pipeline/test_pipeline_algo.py
- tests/pipeline/test_us_equity_pricing_loader.py
- zipline/currency.py
- zipline/data/bcolz_daily_bars.py
- zipline/data/fx.py
- zipline/data/hdf5_daily_bars.py
- zipline/data/in_memory_daily_bars.py
- zipline/data/session_bars.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/engine.py
- zipline/pipeline/hooks/progress.py
- zipline/pipeline/loaders/base.py
- zipline/pipeline/loaders/blaze/core.py
- zipline/pipeline/loaders/equity_pricing_loader.py
- zipline/pipeline/loaders/utils.py
- zipline/testing/core.py
- zipline/testing/fixtures.py
- zipline/utils/compat.py
- zipline/utils/run_algo.py
Initial work on adding support for currency data.
This adds the basic scaffolding for supporting currency conversions in Pipeline. Currently, we only support conversions for EquityPricing, and the only source of currency data is via an `InMemoryFXRatesReader`. Subsequent updates will provide alternative interfaces to fx rates data.
> ENH: Prototype currency conversions for EquityPricing.

- README.rst
The README now notes the current supported Python versions, and refers
the reader to zipline.io for details. (The README's details had become
out of sync with zipline.io, which also needs to be redeployed to
bring in some recent changes.)
Resolves #2571.
> DOC: Improve install instructions in README.rst

- docs/source/install.rst
There is no `redhat-rep-config` package in RHEL-derived Linux
distributions like Fedora. There is a `redhat-rpm-config` package
though.
> DOC: Fix incorrect package name

- docs/source/install.rst
The install page was carrying old information about supported Python
version.
Page to be updated: [http://www.zipline.io/install.html#gnu-linux](http://www.zipline.io/install.html#gnu-linux)
I was based on the information provided at: [http://www.zipline.io/releases.html#release-1-2-0](http://www.zipline.io/releases.html#release-1-2-0) [https://www.zipline.io/releases.html#release-1-1-1](https://www.zipline.io/releases.html#release-1-1-1)
The Dockerfile also bases my assumption of outdated documentation: [https://github.com/quantopian/zipline/blob/master/Dockerfile](https://github.com/quantopian/zipline/blob/master/Dockerfile).
> DOC: Update documentation

- conda/trading-calendars/meta.yaml
- etc/requirements.txt
A whole bunch of [2020 holidays](https://github.com/quantopian/trading_calendars/pull/103) were [just added](https://github.com/quantopian/trading_calendars/releases/tag/1.11.2).
> Update Trading Calendars

- tests/data/test_daily_bars.py
- tests/data/test_fx.py
- zipline/currency.py
- zipline/data/bcolz_daily_bars.py
- zipline/data/fx/hdf5.py
- zipline/data/hdf5_daily_bars.py
- zipline/data/session_bars.py
- zipline/pipeline/loaders/equity_pricing_loader.py
- zipline/testing/fixtures.py
- Use the exploding-ness of fx rate reader to determine whether `EquityPricingLoader.currency_aware` should be True or False. This gives a more useful error message to users when they try to load currency-converted data with a loader created via `EquityPricingLoader.without_fx`.
- Switch back to using object arrays with `None` as missing representation for outputs of currency code queries. This is the representation we want for `EquityPricing.currency`, and it's also easier to work with in 2/3 compat code. Also switch to using `None` as the `code` for missing currency.
> More Currency Fixes

- zipline/data/bundles/core.py
Is this feature desired, fellow maintainers?
When cleaning old bundles, I had no idea which ones were being deleted and whether it was successful or not.
A few logging lines would be appreciated.
> DOC: Improvements on logging

- tests/data/test_fx.py
- tests/pipeline/test_international_markets.py
- zipline/data/fx/base.py
- zipline/pipeline/loaders/equity_pricing_loader.py
Fixes a bug where we would crash when trying to run a pipeline that contained
only currency-converted data.
> BUG: Fix crash in pipeline with all currency-converted data.

- tests/data/test_fx.py
- zipline/data/fx/base.py
- zipline/testing/fixtures.py
Add a new method, `get_rates_columnar` to `FXRateReader`, with a default implementation given in terms of `get_rates`.
The behavior of `get_rates_columnar` should be logically equivalent to:
```python
def get_rates_columnar(self, rate, quote, bases, dts):
out = []
for base, dt in zip(bases, dts):
out.append(self.get_rate_scalar(rate, quote, base, dt)
return np.array(out)
```
> ENH: Add get_rates_columnar method to FXRatesReader.

- tests/pipeline/test_statistical.py
- zipline/pipeline/factors/statistical.py
Use the same techniques used in `SimpleBeta` to re-implement
RollingPearson (and transitively, RollingPearsonOfReturns).
For a 1 year window length, this provides about a 60x speedup on my
machine:
```
pipebench/perf/pearson.stats% stats statistical.py
Mon Jan  1 20:00:31 2018    pipebench/perf/pearson.stats
9326197 function calls (9325541 primitive calls) in 8.407 seconds
Ordered by: cumulative time
List reduced from 766 to 3 due to restriction <'statistical.py'>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
21    0.243    0.012    7.130    0.340 statistical.py:92(compute)
21    0.000    0.000    0.253    0.012 statistical.py:105(compute)
21    0.170    0.008    0.253    0.012 statistical.py:685(vectorized_pearson_r)
```
The new `vectorized_pearson_r` also has the …
> PERF: Speedup RollingPearson

- tests/data/test_fx.py
- zipline/data/fx/base.py
- zipline/data/fx/hdf5.py
- zipline/data/fx/in_memory.py
- zipline/data/fx/utils.py
- zipline/testing/fixtures.py
- When reading before the start of data, return NaN. We do this because it's
hard to reliably apply a lower bound to the queried dates in core-loader
style pipeline loaders.
- When reading an unknown base currency, return NaN. We might get data from
third parties with unknown currencies. Doing so should not be an error.
- When reading after the end of data, emit an error rather than forward-filling
forever. We may want to revisit this in the future.
> MAINT: Clarify edge case handling for FX Rate Readers.

- tests/test_examples.py
- zipline/examples/__init__.py
- zipline/examples/dual_ema_talib.py
After installing zipline in a fresh virtualenv, when trying to run `from zipline.examples import buyapple` (the next step in the installation docs) we would get an `ImportError` from trying to import `TA-lib` (see: https://github.com/quantopian/zipline/issues/2533).  This is because in `zipline/examples/__init__.py` we were always importing all of the examples, even when just trying to import `buyapple`.  We were doing this to generate a dictionary of all of the examples to run in `test_examples.py`.
This change:
- wraps the example module generation in a function so the examples no longer get imported when `zipline.examples` is called.
- adds a more informative error message when trying to import TA-lib in `dual_ema_talib.py`, as we explicitly do not require TA-lib in the zipline …
> MAINT: Stop always importing all zipline examples

- tests/data/bundles/test_core.py
- tests/data/test_daily_bars.py
- tests/pipeline/test_downsampling.py
- tests/pipeline/test_engine.py
- tests/pipeline/test_pipeline.py
- tests/test_assets.py
- tests/test_history.py
- zipline/testing/fixtures.py
This deprecation will enable the upgrade to add support for python 3.7 and higher
https://docs.python.org/3/library/unittest.html
> DEP: Replacing the assertRaisesRegexp which is deprecated by assertRaisesRegex

- .appveyor.yml
- .travis.yml
- conda/0_sortedcontainers/meta.yaml
- etc/conda_build_matrix.py
- etc/requirements.txt
- etc/requirements_blaze.txt
- setup.py
- tests/test_examples.py
Attempting https://github.com/quantopian/zipline/pull/2512#issuecomment-576903728 by opening a branch as a Quantopian member. All credit for these changes goes to @Peque.
> Python 3.6 Support

- tests/data/test_fx.py
- zipline/data/fx/hdf5.py
- zipline/data/fx/in_memory.py
- zipline/data/fx/utils.py
- zipline/testing/fixtures.py
If an FX rate query requests a date that's greater than the last date in the fx
rate file, forward-fill from the last value in the file rather than raising an
error.
We do this for a few reasons:
1. We'd like to gracefully handle the possibility of an FX rates file that's
older than another input file.
2. Relative to other non-erroring behaviors, forward-filling is the simplest
thing to implement. Specifically, it's what the implementation prior to this
change would do naturally if there weren't an explicit check to prevent it.
3. For an FX rates file containing prices on a 24/5 calendar, some amount of
forward-filling is required to handle any market with a non-weekday date.
> MAINT: Forward-fill fx rates past file end.

- tests/test_labelarray.py
- zipline/lib/labelarray.py
Avoid making an extra copy of non-C-contiguous arrays when factorizing inputs
to LabelArray. This requires taking care to ensure that we use the same memory
order both when ravelling and unravelling the input arrays.
> PERF: Avoid unnecessary copy in LabelArray.

- tests/pipeline/test_column.py
- tests/pipeline/test_international_markets.py
- zipline/pipeline/data/dataset.py
- zipline/pipeline/data/equity_pricing.py
Add the ability to instantiate pipeline `Column`s with a `currency_aware` flag, indicating whether or not it makes sense to call `.fx`/convert the column's values to another currency. For example, OHLC data is currency-aware, but Volume is not.
> Inform Pipeline Columns of Currency Awareness

- docs/source/install.rst
Possibly related to #2474, this package was a requirement for me to install zipline on arch. I'm not sure that the package name for RHEL and ubuntu is correct, however.
> List hdf5 as a dependency

- zipline/data/minute_bars.py
If an equities or futures update file was written in python 2 but read in python 3, `pandas.read_hdf` would error trying to read the tz attr in the file.
> H5 Minute Reader Bug in Python 3

- etc/requirements.in
- etc/requirements_locked.txt
- Conda packaging is much easier if we allow newer bcolz.
- Bump pip-tools and bcolz in CI requirements lockfile
> Conda forge prep

- zipline/pipeline/filters/filter.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
Adds a new base class for for "universal" mixins, which are intended to be used
to create identical or near-identical specializations of Factor, Filter, and
Classifier. The base class serves two purposes:
1. It consolidates code that was previously duplicated among the existing
mixins.
2. Arguably more importantly, it gives a name and some documentation to the
universal mixin pattern.
> MAINT: Rework universal mixins to share more code.

- tests/pipeline/base.py
- tests/pipeline/test_computable_term.py
- tests/pipeline/test_filter.py
- tests/pipeline/test_numerical_expression.py
- tests/pipeline/test_slice.py
- tests/pipeline/test_term.py
- zipline/lib/labelarray.py
- zipline/pipeline/classifiers/classifier.py
- zipline/pipeline/factors/factor.py
- zipline/pipeline/filters/filter.py
- zipline/pipeline/mixins.py
- zipline/pipeline/term.py
- zipline/utils/numpy_utils.py
This PR implements several improvements to "universal terms", and implements several new such terms to enable conditional-based terms.
- Refines our existing machinery for implementing behaviors common to multiple `ComputableTerm` subclasses. The existing `DownsampledMixin` and `AliasedMixin` classes no longer require separate boilerplate in each of `Factor`, `Filter`, and `Classifier`. Instead, the boilerplate has been moved into `ComputableTerm`, where it can appear just once. Factor, Filter, and Classifier now provide a method called `_principal_computable_term_type`, which is used to implement the necessary boilerplate. The existing `Slice` class has been refactored to use this machinery as well, which means `Factor[asset]` is now a proper `Factor` instance (same for `Filter` and …
> ENH: Add Filter.if_else and ComputableTerm.fillna.

- tests/pipeline/base.py
- tests/pipeline/test_factor.py
- zipline/pipeline/factors/factor.py
- zipline/utils/math_utils.py
Adds several methods to Factor for producing daily summary statistics. The
following methods are supported:
- mean
- median
- stddev
- max
- min
- sum
- notnull_count
Each of these methods produces a term with ndim=1, meaning that it produces a
single scalar value per day.
> ENH: Add daily summary methods to Factor.

- tests/pipeline/test_factor.py
- zipline/pipeline/factors/basic.py
- zipline/pipeline/factors/factor.py
This isn't hard to write as a custom factor, but it is much more convenient to be able to use `clip` as a method.
> ENH: add Factor.clip method

- zipline/pipeline/engine.py
- zipline/utils/numpy_utils.py
Some terms mutate their inputs, but by not copying the data before passing them
to a term, the input could be corrupted and then used in other terms that didn't
expect the mutated input.
This change uses the same reference counting mechanism to only copy when needed
that is applied to windowed terms.
> Window length 0 fails to copy input

- zipline/testing/pipeline_terms.py
- zipline/testing/predicates.py
- Assert that float pipeline outputs are equal with a tolerance
- Don't assert_almost_equal with string arrays
> Assert fixes

- README.rst
- docs/source/bundles.rst
- zipline/__main__.py
- zipline/algorithm.py
- zipline/data/bundles/quandl.py
- zipline/utils/run_algo.py
- make `quantopian-quandl` the default bundle
- update documentation to reflect new default bundle
- update documentation to make `quandl` bundle as deprecated
- improve error message when no benchmark is provided
> Bundle fixes and documentation improvements

- README.rst
This could be added to the `development-guidelines.rst` in the documentation instead (or apart from).
I think it is important to be clear in this respect to avoid frustration and to avoid wasting your time or anybody's time.
Examples of:
- Ignored PRs for years or months: https://github.com/quantopian/zipline/pull/1976, https://github.com/quantopian/zipline/pull/1804, https://github.com/quantopian/zipline/pull/2510, https://github.com/quantopian/zipline/pull/2512
- Closed PR implementing the same solution on your own: https://github.com/quantopian/zipline/pull/2511
Those are just based on my experience, but I am guessing I am not being treated differently and this may apply to anybody contributing to the project.
Also, it seems clear from the Git logs that you are not really integrating …
> DOC: Update contributing notes

- etc/requirements.in
- etc/requirements_locked.txt
- etc/requirements_py36_locked.txt
- setup.py
- zipline/algorithm.py
- zipline/assets/asset_writer.py
- zipline/data/bundles/core.py
- zipline/gens/tradesimulation.py
- zipline/pipeline/hooks/delegate.py
- zipline/testing/fixtures.py
- zipline/utils/compat.py
(Technically, I think we'd need it in python 3.3. Oh well. 🤷 )
> MAINT: Don't need contextlib2 in our py3 envs

- .github/workflows/ci.yaml
Makes a few changes to fix our usage of `actions/cache` work:
1. Installs `wheel` as part of CI so that we actually build wheels and they get cached properly
2. Fixes the environment variable passed to `hashFiles` so that we're actually hashing the right requirements file (this was failing silently before)
3. Fixes `restore-keys` to be more specific
While we are now actually caching/restoring wheels correctly, this does not speed up builds all that much. Most of our time in install is spent building/installing zipline itself.
> BLD: Fix caching in Github Actions builds

- docs/source/install.rst
Zipline installation docs currently uses `source activate` and `source deactivate` - which only work on Linux and MacOS. So I thought we might want to change that to `conda activate` and `conda deactivate` as they are supported on all OS (available on Conda 4.4 onwards https://www.anaconda.com/blog/conda-4-6-release)
> DOC: Update source activate command to conda activate

- docs/source/development-guidelines.rst
There was no description for anaconda user to install dependencies to build docs. 
So I run the pip install command below in my local Mac environment, but an error happened.
```
pip install -r ./etc/requirements_docs.in -c ./etc/requirements_locked.txt
```
<details>
<summary>This is the error I encountered</summary>
```
Requirement already satisfied: Sphinx>=1.3.2 in /Users/yoshinobu.a.nakada/opt/anaconda3/lib/python3.8/site-packages (from -r ./etc/requirements_docs.in (line 1)) (3.1.2)
Requirement already satisfied: numpydoc>=0.5.0 in /Users/yoshinobu.a.nakada/opt/anaconda3/lib/python3.8/site-packages (from -r ./etc/requirements_docs.in (line 2)) (1.1.0)
Collecting sphinx-autobuild>=0.6.0
Downloading sphinx_autobuild-2020.9.1-py3-none-any.whl (9.8 kB)
Collecting sphinx-rtd-theme …
```
> DOC: Add a description to build docs for anaconda users
