quantopian/zipline

zipline/algorithm.py

cumulative risk measures added to the datapanel produced from perf frames.

ENH: risk measures in datapanel

---

zipline/sources/data_frame_source.py

Python3 dicts have no has_key().

PYTHON3:changed has_key to if/in

---

tests/test_finance.py
tests/test_tradingcalendar.py
zipline/data/loader.py
zipline/finance/trading.py

Copy of @warren-oneill PR https://github.com/quantopian/zipline/pull/542
Rebased off master for merging and testing.
@ehebert @twiecki for awareness.

More flexible calendar implementation

---

tests/finance/test_slippage.py
zipline/finance/slippage.py

Fix for https://github.com/quantopian/qexec/issues/2206

BUG: Do not impact limit fill price

---

zipline/finance/performance/period.py

Stop the growth of members of PerformancePeriod every time that `to_dict` is called with `dt` parameter.
Found by running `objgraph.show_growth()` before and after every packet during a minute emission simulation. The show growth was reporting the following per simulation minute.
```
list           25890        +2
Timestamp      62445        +1
OrderedDict     1020        +1
```
After these changes, there is no growth shown between market minutes.

Remove leaky defaultdicts

---

tests/test_security_list.py
zipline/utils/test_utils.py

Rather than drop files temporarily into the master security lists
directory during unit tests, create temporary directories for the
tests. This avoids issues when the tests are being run at the same
time as other code that uses the real security lists data.

TST: Don't modify master security lists directory during tests

---

zipline/gens/tradesimulation.py

Make the ordering in which processing of event types both explicit and
independent of the sort ordering of the incoming sources.
The overhead of creating the list per snapshot and the iterators appears
to be marginal in the minute data case when tested locally.
This patch is intended as part of the path towards making the trade
simulation loop not depend on consuming and tracking every trade event.
The timing of where last_sale_date was needed to be changed was proving
difficult to adapt in the previous model.
Should also allow the removal of sorting of the various source streams.

MAINT: Group events by type before processing.

---

zipline/finance/performance/tracker.py

In certain cases the trading day and market open can fall on different days when the timestamp is converted to utc. What this means is the ```env.next_trading_day()``` can get stuck in a continuous loop due to the timezone change when ```market_open``` is passed.
Till now this has probably been not much of an issue since the NYSE open times remain on the same day when converted to UTC but when used in markets where the difference between local tz and UTC is bigger this can be an issue.
To rectify this I pass the trading day to  ```env.next_trading_day()``` instead of ```market_open```.

WIP BUG: env.next_trading_day() not Timezone aware when passed market_open/close

---

tests/test_assets.py
zipline/assets/_assets.pyx

These fields are required for compatibility with existing Quantopian algorithms. They are marked for deprecation in the future if possible.

ENH: Adds security_start_date and _end_date with deprecation warnings

---

zipline/finance/performance/period.py

Use explicit references to the performance tracker instead of the proxy
lookup.
Mainly a putative change, which surfaced when reasoning about places
where the position tracker and period need access to the last sale
price.

MAINT: Remove position proxy.

---

zipline/errors.py

@ssanderson Is this message satisfactory?

BUG: Completes ConsumeAssetMetaDataError message

---

zipline/data/ffc/loaders/_us_equity_pricing.pyx

For security best practices, though it is unlikely that a injectable
value would get to this point, use the Python sqlite3 module's
parameterization for providing parameters.
String formatting is still used on the template for providing the table
name and the number of parameter tokens to use for the IN statement,
since those values are not parameterizable. Those format values there
are hardcoded values, i.e. `splits`, `mergers`, `dividends` and the `?`
character.
Also, factor out the shared query logic between splits, mergers, and
dividends, since this change would have changed all three places in the
same way.

MAINT: Use sqlite parameterization instead of string formatting.

---

tests/test_assets.py

The asset finder retrieved from the test environment is empty, so the
test does not end up testing anything, since the test cases loop over
the empty list of sids in the asset finder.
Remove to possibly be added back in and re-implemented after a larger
refactoring of the module.
Discovered this broken test while working on a sqlite backed AssetFinder.
@jfkirk what do you think about removing this test for now, and then fixing it (or not adding it back in if we think the fuzzy tests suffice) after the change over?

TST: Remove asset finder test for NASDAQ collisions.

---

zipline/assets/assets.py

The previous workflow was:
- insert basic metadata for all assets
- iterate over all metadata entries. Create a sid if one does not
exist
- call insert_metadata again to update the assigned sid value.
Instead, create a sid, if missing on the initial metadata assignment and
remove the second pass of calling insert_metadata.
Also, since the sid assignment code is only done in this one context,
inline the sid assignment code so that there is less code step through
while looking for where sid assignment is done.

MAINT: Move possible side assignment to insert metadata method.

---

zipline/assets/assets.py

Replaces an " is 'None' " check with " != None "
Addresses https://github.com/quantopian/zipline/issues/636

BUG: Replaces is-check against string

---

tests/test_algorithm.py
tests/test_perf_tracking.py
zipline/finance/performance/position_tracker.py
zipline/finance/performance/tracker.py

@StewartDouglas could you give this a read-through?
@ehebert this is the feature I spoke to you about this morning.

ENH: Adds auto-closing feature and implements for Futures

---

tests/test_assets.py

Fix comment copypasta and add a check for the third sid that should be
found.

TEST: Clarify test in asset finder.

---

tests/modelling/test_modelling_algo.py
tests/test_tradesimulation.py
zipline/algorithm.py
zipline/gens/tradesimulation.py

This is mostly useful with the new Modelling API for accessing data.factors.

ENH: Make data available in before_trading_start.

---

zipline/assets/asset_writer.py

@StewartDouglas Mind checking this?

MAINT: Removes unused __init__ from AssetDBWriter

---

tests/test_algorithm.py
tests/utils/daily_bar_writer.py
tests/utils/test_utils.py
zipline/algorithm.py
zipline/data/data_portal.py
zipline/data/minute_writer.py
zipline/gens/tradesimulation.py
zipline/utils/events.py

We now pass in dataportal to TradingAlgorithm.run
Also, we have facilities to create minute or daily bcolz data from dataframes.
@ehebert there's a failing test (test_algorithm.py#TestMiscellaneousAPI.test_get_open_orders) that I think is related to the portfolio state stuff you're working on

PR for zipline test infrastructure

---

tests/test_algorithm.py
zipline/data/data_portal.py
zipline/test_algorithms.py

Dataportal now supports daily mode for spot prices.
I think all the remaining test failures (and there are a bunch of them) in TestTransformAlgorithm are legitimate order-related failures.

more progress on tests

---

zipline/transforms/batch_transform.py

@richafrank This should resolve the issue you saw

MAINT: Removes batch transform's environment dependency

---

tests/test_algorithm.py
zipline/algorithm.py

Running an algo with a df/panel of Assets was raising SidNotFound
```retrieve_asset``` returns its argument if it's an Asset.  In ```run```, we want to ensure that Asset is in the db first, so pass the asset's sid attribute to ```retrieve_asset``` to get a real answer about whether it's already in the db.

Run panel of assets

---

tests/test_algorithm.py
zipline/algorithm.py
zipline/data/data_portal.py

- ensure dt is midnight utc inside dataportal when doing daily lookup

fix some more test failures

---

tests/test_algorithm.py

'instant fill' execution may be on the path to deprecation, (the removal
is currently proposed by the branch which removes events in favor of
operating over dts.), so remove instant_fill from the close position
tests so that the input and output is the same between the proposed
branch and here.
(This was one of the few places where instant fill was used that
was not testing instant fill behavior explicitly, so may be better to
align this test with the rest of the suite.)
Also, change test methods to make it more clear on which day the values
the expected and actual results differed.

TST: Remove instant fill from close position test.

---

tests/finance/test_slippage.py
tests/test_algorithm.py
tests/test_dataportal.py
zipline/data/data_portal.py
zipline/data/minute_writer.py
zipline/finance/performance/position_tracker.py
zipline/finance/slippage.py
zipline/finance/transaction.py

more progress

---

tests/test_algorithm.py
zipline/data/data_portal.py
zipline/finance/performance/period.py
zipline/finance/performance/tracker.py

This may only work in daily mode, but it is a start in calculating the
payouts during the period performance calculaiton.
Should add a minute test case to master to ensure that we do not break
it.

Calculate futures payouts

---

zipline/assets/asset_writer.py
zipline/assets/futures.py
zipline/finance/performance/position_tracker.py

Adds Apache license where necessary.

MAINT: Add license to various files

---

zipline/data/_adjustments.pyx

For a pipeline doing simple computations on USEquityPricing data, we
were spending ~60% of `run_pipeline` loading adjustments.  Almost all of
that time was spent in calls to `DatetimeIndex.get_loc` to find the
indices of adjustment `eff_date`s.
This optimizes the eff_date lookups by pre-populating a cache of
seconds-since-epoch timestamps that we expect to see, and falling back
to `np.searchsorted` on cache misses.
In testing, this reduces the time to compute a 1-year pipeline with 30
and 90 day moving averages from 3.1 seconds to 0.9 seconds.

PERF: Speed up reading of adjustments.

---

tests/pipeline/test_factor.py
zipline/pipeline/factors/technical.py
zipline/utils/test_utils.py

BUG: RSI wasn't even close to working.

---

tests/serialization_cases.py
tests/test_security_list.py
tests/test_tradesimulation.py
tests/utils/test_utils.py
zipline/data/data_portal.py
zipline/finance/performance/tracker.py
zipline/gens/tradesimulation.py

Clean up some date management, etc in the tradesim inner loops.
Once per day, get dividends for relevant sids and apply them.
Properly call `before_trading_start` now.

call before_trading_start, apply dividends

---

tests/finance/test_slippage.py
tests/pipeline/test_pipeline_algo.py
tests/test_algorithm.py
tests/test_blotter.py
tests/test_dataportal.py
tests/test_history.py
tests/test_perf_tracking.py
tests/test_security_list.py
tests/test_tradesimulation.py
zipline/algorithm.py
zipline/data/data_portal.py
zipline/data/minute_writer.py
zipline/finance/blotter.py
zipline/finance/performance/period.py
zipline/finance/performance/position_tracker.py
zipline/finance/performance/tracker.py
zipline/gens/tradesimulation.py
zipline/sources/requests_csv.py
zipline/utils/simfactory.py
zipline/utils/test_utils.py

Rewrote how data portal handles Fetcher sources.
Cleaned up how data portal is initialized.
Cleaned up a bunch of tests.

lots of fixes

---

tests/test_history.py
tests/test_perf_tracking.py
zipline/data/data_portal.py
zipline/data/us_equity_pricing.py
zipline/finance/performance/position.py
zipline/finance/performance/position_tracker.py
zipline/finance/performance/tracker.py
zipline/protocol.py
zipline/utils/test_utils.py

Pass a SQLiteAdjustmentReader and use queries for the dividends table
to disperse payouts to stocks in which the algorithm has a position.

Use SQLiteAdjustmentReader for dividends payouts.

---

zipline/data/us_equity_pricing.py
zipline/utils/tradingcalendar.py

Fixes https://github.com/quantopian/zipline/issues/771

Change relativedelta to Timedelta as pandas 0.17.0 deprecated relativedelta.

---

tests/test_benchmark.py
tests/utils/test_events.py
zipline/data/data_portal.py
zipline/finance/performance/position_tracker.py
zipline/utils/events.py
zipline/utils/test_utils.py

Some speedups in event rules and data portal lookup.

various speedups

---

zipline/data/data_portal.py
zipline/protocol.py

This lets users get a dynamic list of assets via fetcher, based on simulation dt.

added data.fetcher_assets

---

tests/test_history.py
zipline/finance/trading.py

When working on test coverage for `history()` I wrote the following pure-zipline algorithm:
```python
from zipline.api import history
def initialize(context):
context.first_loop = True
def before_trading_start(context, data):
if not context.first_loop:
price_bts = history(bar_count=1, frequency='1m', field='price')
context.price_bts = price_bts
def handle_data(context, data):
context.first_loop = False
```
Which raised the following error:
```
IndexError: index 0 is out of bounds for axis 0 with size 0
```
I traced this issue back to the following method, which is invoked by the history container:
https://github.com/quantopian/zipline/blob/master/zipline/finance/trading.py#L340-L348
We call this method with a 'start' of midnight of this trading day, since this is when …

Update next_market_minute() & previous_market_minute(), and add history() tests

---

tests/pipeline/test_pipeline_algo.py
zipline/algorithm.py

Default first chunk is smaller for more immediate results

ENH: Makes chunk_size configurable in attach_pipeline

---

zipline/algorithm.py
zipline/gens/tradesimulation.py
zipline/sources/benchmark_source.py

(this branch's name is a misnomer)
no functional change.  move benchmark code into its own object, which is passed into tradesim.

pass benchmark source into tradesim

---

tests/pipeline/test_pipeline_algo.py
tests/test_algorithm.py
tests/test_assets.py
tests/test_perf_tracking.py
zipline/assets/asset_writer.py
zipline/errors.py
zipline/utils/test_utils.py

@jfkirk indicated to me that this field was unused by the writer, which appears to be correct.

MAINT: Remove unused 'asset_type' metadata entry.

---

zipline/utils/memoize.py

ping @richafrank who noticed this odd behavior.

ENH: Raise on attempt to set a lazyval.

---

tests/test_assets.py
zipline/assets/futures.py

@yankees714 Mind reviewing this fix?

BUG: FutureChain's as_of() now properly coerces arguments

---

.travis.yml
docs/source/whatsnew/0.8.4.txt

Was mistakenly removed, so coveralls has not been running.

BLD: Add back installation of coveralls on travis

---

zipline/assets/assets.py

Sqlite has a built-in default limit of 999 variables per query, so let's stay under that.

BUG: chunk sqlite queries

---

tests/test_dataportal.py
tests/test_history.py
zipline/data/data_portal.py

- New parameter (futures_sid_path_func) for finding futures minute bcolz files.
- Minute history support.  Because futures are 24/7 and equities are not, we
are imposing the equity clock on futures for now. If you ask for a futures
history window of 100 minutes, we'll only count minutes within the equity
clock towards that 100.
- Daily history support.  We use minute bars to calculate daily rollups.
- As much as possible, all internal DataPortal methods now pass Assets around
(instead of sids) and only convert to sid at the last possible moment.
- Tests and refactoring.

Added support for futures in DataPortal.

---

tests/test_algorithm.py

Fixes test_order_methods_for_future by creating a separate env where 0 is a Future.

TST: Fixes test_order_methods_for_future

---

zipline/utils/munge.py

https://github.com/quantopian/zipline/issues/886

MAINT: Alias methods for 0.17 compat.

---

tests/history/generate_csvs.py
zipline/_protocol.pxd
zipline/finance/transaction.py
zipline/gens/sim_engine.pyx

Adding missing copyright notices and licenses.

Missing copyright notices and licenses.

---

.travis.yml
conda/ta-lib/meta.yaml
setup.py

BLD: make the travis build closer to a normal install

---

tests/test_assets.py
zipline/assets/assets.py

Is the chain intentionality ordered by expiry? For me ordering by the min makes more sense.

BUG: orders future chain by min of notice and expiry

---

.travis.yml

Use https to download miniconda
Some .travis.yml cleanup

Secure snake

---

zipline/assets/assets.py
zipline/pipeline/loaders/blaze/core.py

fixes an issue in expired futures also

Only notnull optionals

---

zipline/data/loader.py

For years I watched the tickers print, helpless to stop them from appearing every. single. time.
One day I did something about it.

Replace print with logger.info

---

tests/pipeline/test_blaze.py
zipline/pipeline/loaders/blaze/core.py

This occurs when there is not a delta for each asset in the universe for each day there is a delta. This is the most common case. This also adds a test where this happens.

BUG: fix deltas in blaze core loader

---

tests/test_assets.py
zipline/assets/_assets.pyx

BUG: Handle OverflowError by comparing False

---

tests/data/test_minute_bars.py
zipline/data/minute_bars.py

For faster parsing and writing workflows, do not require a DataFrame.

ENH: Allow passing of numpy arrays to writer.

---

tests/test_doctests.py
zipline/assets/_assets.pyx
zipline/assets/assets.py
zipline/gens/tradesimulation.py
zipline/protocol.py
zipline/utils/data.py

Look up expired futures from in-memory Futures instead of queries to the db.

Expiration perf

---

.travis.yml
etc/requirements_dev.txt
tests/test_algorithm.py
tests/test_history.py
tests/test_history_new.py
tests/test_perf_tracking.py
zipline/assets/assets.py
zipline/data/data_portal.py
zipline/utils/test_utils.py

History tests are not complete yet (still missing split/merger/dividend tests for daily history, and futures tests) but holding off for now.

more history tests

---

zipline/data/data_portal.py
zipline/data/us_equity_pricing.py

Instead of fetching the '1d' portion which holds data for previous days
390 times a day, cache the last array retrieved for each array.
Also, call `load_raw_array` with all assets at once instead of one at a
time, since the daily bcolz file is tuned for reading many equities at
once.
A further optimization on top of this would be to prefetch data from the
daily bcolz file.

PERF: Batch and cache '1d' history calls.

---

docs/source/whatsnew/0.8.4.txt

@richafrank Could you take a look?

DOC: update whatsnew for equity auto closes

---

tests/pipeline/test_buyback_auth.py
zipline/pipeline/factors/__init__.py

Forgot to add buyback auth factors to `__init__`. Also, small formatting fixes.

MAINT: add buyback auth to factors init.

---

zipline/utils/events.py

Small cleanup, no functional/perf changes

DEV: Simplify if statement in BeforeClose

---

tests/test_algorithm.py
zipline/finance/blotter.py

Even went with 'canceled' instead of 'cancelled' :us: 
@lianga888 can you take a look?

ENH: Better warning message on partial fills

---

etc/conda_build_matrix.py

I cannot get the builds to run in parallel without locking up. We can invest more time if this becomes an annoyance

DEV: allow partial uploads in conda_build_matrix

---

zipline/data/data_portal.py
zipline/finance/performance/tracker.py
zipline/gens/tradesimulation.py

Cleaned up some code no longer needed by lazy-mainline.

Lazy but tidy

---

tests/pipeline/test_pipeline_algo.py
zipline/pipeline/engine.py

`tz_localize` was failing on a dataframe with an empty MultiIndex.

BUG: Empty pipeline failed to tz_localize

---

tests/test_api_shim.py
zipline/_protocol.pyx

- Shims `data[sid(x)]["sid"]`
- Shims `data.items()`

More shims

---

tests/test_history.py

In effort to make it easier to step through and isolate a failure on
another branch using this test, adapt the verify regular function so
that it accepts assets and fields as parameters, so that asset field
combos are run one at a time.

TST: Parameterize minute history test.

---

tests/test_bar_data.py
tests/test_history.py
zipline/_protocol.pyx
zipline/data/data_portal.py

- breaks the logic for getting adjustments into a new method `get_adjustments`, used by `get_adjusted_value` and by BarData.history when we need to handle non market minutes
- `get_adjusted_value` is now a public method used by BarData.current when we need to handle non market minutes

FIX: Make overnight adjustments for before_trading_start

---

tests/test_api_shim.py
zipline/algorithm.py

Make sure the old history API gets the window as of the last market minute, gets adjustments between the last market minute and current time, and applies the adjustments

FIX: Shim for q1 history call inside before_trading_start

---

tests/test_bar_data.py

@jbredeche I just used the format of the existing test, and parameterized for dividends and mergers. Is there anything else we'd like to test here?

TST: Parametrizes spot price test to test dividends and mergers also.

---

tests/test_algorithm.py
tests/test_perf_tracking.py
zipline/algorithm.py
zipline/finance/performance/position_tracker.py
zipline/finance/performance/tracker.py
zipline/gens/tradesimulation.py

completely copied from https://github.com/quantopian/zipline/pull/1104/
All credit goes to @lianga888

DEV: Apply adjustments for portfolio and account in BTS

---

etc/requirements.txt
etc/requirements_py2.txt
setup.py

Use environment markers instead of a separate requirements file for py2.

Env markers

---

zipline/data/data_portal.py

The "in before trading start logic" is now all handled inside of
`BarData`.

MAINT: Remove unused member.

---

docs/source/whatsnew/0.9.1.txt
zipline/errors.py
zipline/pipeline/factors/factor.py
zipline/pipeline/mixins.py

For https://github.com/quantopian/zipline/pull/1119

Cleanup and docs for multiple factor outputs

---

conda/bcolz/meta.yaml
etc/requirements.txt
setup.py
tests/test_algorithm.py
tests/test_api_shim.py
tests/test_bar_data.py
tests/test_benchmark.py
tests/test_finance.py
tests/test_history.py
tests/test_memoize.py
tests/test_perf_tracking.py
tests/utils/daily_bar_writer.py
zipline/algorithm.py
zipline/data/data_portal.py
zipline/data/minute_bars.py
zipline/finance/performance/period.py
zipline/finance/performance/position_tracker.py
zipline/finance/performance/tracker.py
zipline/gens/tradesimulation.py
zipline/protocol.py
zipline/testing/core.py
zipline/utils/compat.py
zipline/utils/memoize.py

Fixes 32-bit issues as well as tests/simulations leaking handles to adjustments dbs (via data portals).

Fix windows/conda builds

---

zipline/data/data_portal.py

The cache in data portal was added before the change to using a
CachedObject to wrap the window_blocks in the USEquityHistoryLoader.
Removing this extra layer saves some cycles.
Does not fix current memory investigaton (since only one sids/dts pair
per column was cached in `_equity_daily_reader_array_data` at a time),
but removing should make it more clear where needed references are being
held.

PERF: Remove extra daily history caching.

---

tests/test_algorithm.py
zipline/_protocol.pyx

Our type checking code was a bit too aggressive.

BUG: support passing an empty list to `data` methods.

---

tests/utils/test_events.py
zipline/utils/events.py

- previously, we calculated the new trigger period (9:30 to 16:00 EST for a given date) after the current trigger period has passed. We fast-forward 7 calendar days from the current dt and calculate the new period for that week
- however, if the trigger is the last day of the week, we recalculate on the first bar of the following week, and after fast-forwarding 7 calendar days, we end up in the week following that (effectively skipping a week)
- to fix this, we recalculate every time we trigger, because of the assumption in Q2 that we run handle_data every minute (and thus we will never miss a trigger)
- accompanying fixes to address shortened weeks:
- when finding the first or last day of the week, if it is not a trading day, adjust accordingly
- when applying the offset, if there's not …

BUG: week_end rule with offset=0 skips every other week

---

tests/utils/test_events.py
zipline/utils/events.py

If we start the simulation on a day so that we miss the trigger
(the first for the sim) for that week, recalculate the trigger
for next week

BUG: Recalculate trigger for week rule if we miss the first one

---

.travis.yml
zipline/finance/trading.py

PR for travis, now with the custom branch name in `.travis.yml`

ENH: Make arena configurable for SimulationParameters

---

zipline/finance/order.py

More long-term fix is coming later, this restores existing downstream
behavior.

BUG: Restoring 'broker_order_id' to Order's dict

---

tests/pipeline/test_consensus_estimates.py
zipline/pipeline/common.py
zipline/pipeline/data/consensus_estimates.py
zipline/pipeline/loaders/blaze/consensus_estimates.py
zipline/pipeline/loaders/consensus_estimates.py

Adds a column representing the previous "actual" value of the estimated field for the estimates dataset.

ENH: add actual value column to estimates dataset.

---

appveyor.yml
ci/appveyor/install.ps1

Hoping to fix appveyor issues activating conda env.  
Added more logging when failing to download miniconda.

Appveyor conda reunion

---

zipline/data/minute_bars.py

Instead of letting the cache of carrays grow unbounded, use an LRUCache
to cap the number of equities for any given column.
Tested with the size 1000, on an algo that was using pipeline which was
using over 3000, runtimes were similar, but the memory usage was
successfully capped to around 1.2GB.
Also, tested with an algorithm which bought and hold just one equity and
no major slow down was seen when using the LRUCache vs. a dictionary.
We may want to follow this up with an extension to `carray` which is not
as memory hungry per column; e.g. by not loading repeated/similar
metadata or releasing the last read chunk after a certain amount of
time.

PERF: Cap memory usage by minute bar carrays.

---

tests/test_panel_daily_bar_reader.py
zipline/data/us_equity_pricing.py
zipline/utils/input_validation.py

Break it into a standalone function that handles any pandas type.
Also uses `preprocess` to push the validation into a decorator, and refactors the tests to check all possible axis permutations.

TEST/MAINT: Refactor unique axis verification.

---

tests/test_blotter.py
tests/test_finance.py
zipline/finance/blotter.py
zipline/gens/tradesimulation.py

DEV: pull remove-open-orders logic into its own method

---

tests/data/test_minute_bars.py
zipline/data/minute_bars.py

Minutely data can now be appended to bcolz files even when
minutes in the same day have already been written. For example,
previously attempting to write data for the minute 2016-05-11 16:30
would raise an exception if any OHLCV data for 2016-05-11 had been
written to the same file.
Trying to overwrite existing minutes still raises a
BcolzMinuteOverlappingData exception.
Note that previously all sids' bcolz files ended at the same time.
This is no longer necessarily the case. The last record in each
sid's bcolz file now corresponds to the latest minute for which
OHLCV data is provided to the writer.

Allow BcolzMinuteBarWriter to append to most recent day

---

setup.py

Until https://github.com/quantopian/zipline/issues/1197 is fixed.

BLD: Cap the version of pandas until we fix compatibility issues

---

tests/data/test_minute_bars.py
zipline/data/minute_bars.py

Add test to cover new minute block logic

---

tests/test_history.py

Make the delineation between `DailyEquityHistoryTestCase` and
`MinuteEquityHistoryTestCase` whether or not minute dts or daily dts are
used as the query timestamp, instead of whether the frequency is `1d`
vs. `1m`.
Preparing for adding a repro case for where using `1d` with minute data
fails when there is an adjustment occuring the day before the query
minute dt.

TST: Move tests that use minute data.

---

README.rst
docs/notebooks/tutorial.ipynb
docs/source/beginner-tutorial.rst

* Removed remaining mentions of `add_history`
* Removed inaccurate downloads/day badge
There's nothing we need to replace this text with, right?

DOC: Remove add_history

---

tests/pipeline/test_events.py

Use arrays in more places, and use permutations of indexers instead of
permutations of the values.

PERF: Speed up test_events.

---

zipline/utils/cache.py

Because windows doesn't allow multiple processes on a file
@llllllllll , can you merge this onto your branch?

Added manual deletion to temp files

---

zipline/algorithm.py
zipline/testing/core.py

No tests failed, which was worrisome.  
Will file issues to take a look later.

Fix some mistakes from a previous merge.

---

tests/pipeline/test_events.py

Just take a sample of all 5000 permutations of 7 dates.

PERF: Speed up event utils test case.

---

tests/test_panel_daily_bar_reader.py
zipline/data/us_equity_loader.py
zipline/data/us_equity_pricing.py

Also, renamed it from `_sessions_` to `sessions` and defined an
abstractproperty in `DailyBarReader`.

BUG: Implement `sessions` property for `PanelDailyBarReader`

---

tests/data/test_us_equity_pricing.py
tests/pipeline/test_us_equity_pricing_loader.py
tests/test_algorithm.py
tests/test_assets.py
tests/test_benchmark.py
zipline/__main__.py
zipline/assets/__init__.py
zipline/assets/_assets.pyx
zipline/assets/asset_db_migrations.py
zipline/assets/asset_db_schema.py
zipline/assets/asset_writer.py
zipline/assets/assets.py
zipline/data/bundles/yahoo.py
zipline/errors.py
zipline/testing/predicates.py
zipline/utils/functional.py
zipline/utils/paths.py
zipline/utils/range.py

Adds the ability to model when an equity changes symbol. This uses an im memory cache for by-symbol lookups so there is no more assetfindercachedequities.

Point in time asset db

---

zipline/data/minute_bars.py

Adds a `minutes_per_day` field to `BcolzMinuteBarMetadata`, so that the `minutes_per_day` value passed to the `BcolzMinuteBarWriter` is written as a part of the minute bar metadata. This allows the reader to share this value, instead of always assuming 390.
Also rebuilds the example data to incorporate this format change.

ENH: Removes dependence of BcolzMinuteBarReader on 390 minutes per day

---

docs/source/whatsnew/1.0.2.txt
tests/pipeline/test_filter.py
zipline/pipeline/filters/__init__.py
zipline/pipeline/filters/filter.py
zipline/pipeline/filters/smoothing.py

Also, moved All() and Any() to `zipline.pipeline.filters.smoothing`.

ENH: Rename StrictlyTrue to All and add Any().

---

tests/test_assets.py
zipline/assets/asset_db_migrations.py
zipline/assets/asset_db_schema.py
zipline/assets/asset_writer.py

Bumps the asset db version to 4

ENH: Adding `exchange_full` to equity asset column

---

tests/test_algorithm.py
zipline/algorithm.py
zipline/gens/tradesimulation.py

Yield packets for capital changes so downstream processes can consume then

ENH: Yield capital change information

---

docs/source/whatsnew/1.0.2.txt
tests/pipeline/test_filter.py
zipline/pipeline/filters/__init__.py
zipline/pipeline/filters/smoothing.py

will add doc after the number issued through pr

ENH: Added AtLeastN filter

---

tests/pipeline/test_technical.py

- Don't create unnecessary extra data (requires passing fastd_period=1
to TA-Lib or else it fills the FastK with NaNs even though it must
have already computed them...
- Use random_sample instead of random_integers so that we're not
dependent on integer arithmetic.
- Pass array_decimal to assert_equal so that we do almost equal checking
on results.

BUG/TEST: Fix stochastic oscillator test.

---

.travis.yml
appveyor.yml
conda/zipline/meta.yaml

Looking at you, https://github.com/quantopian/zipline/issues/1161.

Conda updates

---

tests/test_assets.py
zipline/assets/asset_db_migrations.py
zipline/testing/predicates.py

Selects the most recent ticker for each sid.

v5 downgrade

---

zipline/data/minute_bars.py

Define the minute bar interface and make the `BcolzMinuteBarReader`
implement that interface.

MAINT: Define minute bar reader interface.

---

tests/data/bundles/test_core.py
zipline/data/bundles/core.py

For https://github.com/quantopian/zipline/issues/1402

BUG: Fixes should_clean for keep_last=0

---

zipline/data/data_portal.py
zipline/data/history_loader.py

Prepare for using history loaders with both equity and future data,

MAINT: Remove equity from history loader classname

---

zipline/data/data_portal.py

Remove members which are not referred to.

MAINT: Remove unused data portal members.

---

README.rst
docs/notebooks/tutorial.ipynb
docs/source/beginner-tutorial.rst

Per https://github.com/quantopian/zipline/issues/1395

DOC: Replace run_algo.py in docs with zipline run

---

tests/calendars/test_trading_calendar.py
zipline/utils/calendars/exchange_calendar_bmf.py
zipline/utils/calendars/exchange_calendar_lse.py

For https://github.com/quantopian/zipline/issues/1393
Also fixes the LSE calendar.

All calendars

---

zipline/testing/fixtures.py

Use the equity calendar to write equity data, even when the simulation
calendar has been set to a different calendar.
Discovered when writing a test that used a calendar for future asset
data, but also wrote equity data.

TST: Use equity calendar when writing equity data

---

zipline/data/data_portal.py

The apply adjustments behavior had been moved to the `HistoryLoader`
class.

MAINT: Remove unused data portal methods.

---

docs/source/releases.rst
docs/source/whatsnew/1.0.2.txt
zipline/api.pyi

Update release notes.
Generate api stubs.

REL: Prepare for 1.0.2 release.

---

tests/test_assets.py
zipline/assets/assets.py

Fixes the corner case shown in the new test for fuzzy symbol mapping.

More Fuzzy Symbol Fixes

---

zipline/algorithm.py

Dividends are read from AdjustmentReader.

MAINT: Remove unused method.

---

docs/source/whatsnew/1.0.2.txt
docs/source/whatsnew/1.0.3.txt

DOC: Add skeleton for 1.0.3 release notes.

---

zipline/pipeline/loaders/blaze/core.py
zipline/pipeline/loaders/earnings_estimates.py

Some small updates to address deprecation warnings.

MAINT: small updates to fix deprecation warnings

---

tests/utils/test_preprocess.py
zipline/utils/input_validation.py

Allows ``__funcname`` to be passed to preprocessors like expect_types
and expect_dtypes to override the name displayed in error messages.
This is useful for providing clearer errors for ``__init__`` and
``__new__`` methods in classes.

ENH: Name overrides in preprocessor factories.

---

zipline/data/history_loader.py

Start making the equity adjustments calculations for the history loader
conform to the same method signature as `load_adjustments` provided by
`SQLiteAdjustmentReader, so that an `AdjustmentReader` interface can
begin to take form.
This prepares for creating a `DispatchAdjustmentReader` which will route
adjustment calculations for equities to the
`HistoryCompatibleUSEquityAdjustmentReader` and continuous futures to a
not yet implemented adjustment reader. All of these readers will share
the `load_adjustments` method.

MAINT: Begin making a common adjustment interface.

---

zipline/data/history_loader.py

Was left in as an artifact of development branch.

MAINT: Remove unused parameter.

---

tests/test_continuous_futures.py

Include minutes (in addition to the days) in the price encoding for
continuous futures tests.
Need for different values minute to minute arose when working on tests
for adjusted values.

TST: Encode minutes in continuous future tests.

---

zipline/data/data_portal.py

STY: Put 0 at the end.

---

zipline/__main__.py

fixes: https://github.com/quantopian/zipline/issues/1542

BUG: load extensions in IPython magic

---

tests/test_history.py
zipline/data/history_loader.py

In preparation for using `DataPortal` in notebooks, remove restriction on
the `HistoryLoader` to dates that are monotonically increasing. Notebook
usage of the `DataPortal` is more useful when the end of the history
window can be arbitrary dates without having to restart the notebook kernel.
Due to the implementation of the prefetch and caching logic, the end
date of history calls could previously only increase. e.g. `2016-11-01`,
`2016-11-02`, `2016-11-03`. This pattern was sufficient for backtesting
and live simulations, since the current time of the algorithm only ever increases.
With this change, which resets the underlying sliding window when the
last fetched idx is greater than the
Now calls to history in the same process with end dates such
`2016-11-01`, `2016-10-31`, `2015-11-02` …

ENH: Allow arbitrary history queries.

---

tests/pipeline/test_quarters_estimates.py
zipline/pipeline/loaders/blaze/estimates.py
zipline/pipeline/loaders/earnings_estimates.py

Adds logic that split adjusts estimates. Also adds relevant tests.

Split adjust estimates

---

zipline/data/minute_bars.py

Otherwise, we either raise an exception or filter out all unsafe values.
This addresses an issue where the BcolzMinuteBarWriter would scale up
values to convert to uint32, but the resulting values were too large,
and would be mangled.
Based on the approach we take in the BcolzDailyBarWriter. See https://github.com/quantopian/zipline/blob/master/zipline/data/us_equity_pricing.py#L116.

BUG: Ensure minute OHLC values can safely be converted to uint32

---

tests/test_continuous_futures.py
zipline/assets/roll_finder.py

Fix common error condition which was triggered whenever the session at the end
of the prefetched history window was a session where the back contract was
active. When the back contract was the active contract, the next contract for
consideration was the front contract at the end of the window, which
definitionally always has an autoclose after the end of the window.
Instead, just start seeking backwards from the end of the window.
Also prevent lookahead bias in volume rolls, which was caused by the using the
volume for a session to determine whether that session had rolled. Information
that would not have been available at the beginning of the session.
This change makes the volume rolls overly conservative, and may be improved by
looking at vectors of the preceding volume and making the …

BUG: Fix bounds errors in roll finder.

---

tests/test_continuous_futures.py
zipline/assets/assets.py
zipline/assets/continuous_futures.pyx
zipline/assets/roll_finder.py

Instead of requiring the roll finder to juggle the indices into the ordered
contracts, use a doubly linked list where the nodes element is the contract
with members pointing to the previous and next contracts in the chain.
Besides improving legibility in the roll finder code, this change is on the path
to adding a predicate to exclude contracts from the chain, e.g. contracts in ED
which are not in the roll schedule.

MAINT: Use a doubly linked list for contract chain.

---

etc/requirements.txt
etc/requirements_dev.txt

which are transitive dependencies of zipline

MAINT: Pin exact versions of Mako, MarkupSafe, requests-file

---

tests/pipeline/test_events.py
zipline/pipeline/loaders/events.py

Fixes a bug where the events loader would break if the raw data it was trying to load happened to be empty.

Events loader handle empty raw data

---

tests/test_assets.py
zipline/assets/assets.py

Attempt to lookup up the symbol in the futures table, after attempting to look
up the symbol in the equities table.

ENH: Add futures support for generic asset lookup.

---

zipline/testing/fixtures.py

Pass args and kwargs to add_class_callback in fixtures.

MAINT: pass args, kwargs to add_class_callback

---

tests/pipeline/test_blaze.py
zipline/pipeline/loaders/blaze/core.py

This PR makes applying deltas adjustments optional in the blaze core loader. In cases where the caller opts out of deltas adjustments, only novel deltas will be applied. By default, applying deltas adjustments is set to `True` because we only want to avoid applying them in special cases.

Optionally apply deltas adjustments

---

zipline/utils/input_validation.py

Make a new decorator, expect_strictly_bounds, which shares logic
with the existing expect_bounded (which checks that inputs fall
INCLUSIVELY between bounds),

ENH: Decorator to check inputs fall EXCLUSIVELY between bounds

---

docs/source/whatsnew/1.0.3.txt
zipline/__main__.py

ENH: change the clean --before shortopt from -b to -e

---

tests/test_continuous_futures.py

Should be no functional change.

TST: Remove duplicate key in fixture config.

---

tests/finance/test_slippage.py
zipline/algorithm.py
zipline/data/us_equity_pricing.py

Newer versions of flake8 detect these versions, though current zipline version
of flake8 does not.

STY: Wrap/reformat lines over 80 chars.

---

tests/test_testing.py
zipline/testing/fixtures.py
zipline/testing/slippage.py

Allows specifying a constant number of shares filled per tick.

TST: Adds TestingSlippage slippage model

---

tests/pipeline/test_quarters_estimates.py
zipline/pipeline/loaders/earnings_estimates.py

Fixes a bug in the earnings estimates loader where if the only 1 day was requested in the Pipeline run, there would be no overwrites (overwrites for 1 day are impossible), and there are no split adjustments (as is the case for revenue estimates), the overwrites dictionary would be completely empty and would result in a key error. Adds tests for this.

BUG: fix loader bug for 1 day

---

tests/test_continuous_futures.py
zipline/assets/roll_finder.py

In backtests, volume roll dates are determined by looking back from each auto close date. This introduces potential look ahead bias because if there was ever a double volume flip within the last few days before an auto close, we choose the flip on the later date. Instead we should choose the earlier date because from the perspective of someone seeing the early flip in real time, and being within only a few days of the auto close date, they would likely believe it to be the actual roll date.

Eliminate Possible Bias in Volume Rolls

---

tests/finance/test_slippage.py
zipline/finance/slippage.py

like we discussed, @richafrank

Rename _attrs_to_check to asdict

---

zipline/utils/numpy_utils.py

now you can just pass the dtype name

ENH: make NaT_for_dtype coerce the input to a dtype

---

zipline/data/data_portal.py

Only infer the last trading session if the optional argument is not passed.
@yankees714 It looks like you added these arguments, can you take a look? I assume we want to infer the last available minute as well if that is not explicitly passed. cc @ehebert

Set data portal last trading session/minute if passed

---

zipline/data/benchmarks.py

Non-SSL url stopped working for me...

MAINT: Updated yahoo url for SSL

---

zipline/_protocol.pyx

This matches the behavior of history and data.current.

BUG: Return from can_trade in same order as input.

---

tests/finance/test_slippage.py
zipline/finance/slippage.py

If a backtest starts on a date which does not have enough lookback days for the `VolatilityVolumeShare` slippage model, fall back on a predefined constant.
Confirmed this behavior with @gusgordon 
This PR also adds a feature that always for subclassing `EquitySlippageModel` and `FutureSlippageModel` together and getting the expected behavior that it supports both equities and futures.

More futures slippage cleanup

---

zipline/finance/trading.py

The current docstring does not match the function parameters.

Fix docstring in TradingEnvironment class

---

zipline/testing/fixtures.py

I want to be able to test the pipeline result of a factor so I created a pipeline engine fixture with equity pricing data.

With equity pipeline engine

---

tests/test_benchmark.py
zipline/sources/benchmark_source.py

Add method to get a range of benchmark data

ENH: Add get_range to BenchmarkSource

---

tests/risk/test_risk_cumulative.py
tests/risk/test_risk_period.py
zipline/finance/risk/cumulative.py
zipline/finance/risk/period.py

which was removed from empyrical in https://github.com/quantopian/empyrical/pull/47

MAINT: Removed use of empyrical's information_ratio

---

tests/test_algorithm.py
zipline/finance/performance/tracker.py

References from PR review point here.

Var and cvar feedback

---

zipline/testing/predicates.py

Fixes a typo that made this always pass.

BUG: Fix assert_equal for datetimes

---

tests/test_continuous_futures.py
zipline/assets/roll_finder.py

Reverts quantopian/zipline#1915
Need to tweak this, just reverting for now.

Revert "Volume roll current contracts could flip back and forth"

---

tests/test_continuous_futures.py
zipline/assets/roll_finder.py

See https://github.com/quantopian/zipline/pull/1915 for description.

Volume roll current contracts could flip back and forth (Revised)

---

zipline/pipeline/loaders/blaze/_core.pyx

I made this change when debugging but it is probably worth keeping.

improve error message when timestamp before asof_date

---

tests/pipeline/test_dtypes.py
zipline/errors.py
zipline/pipeline/classifiers/classifier.py
zipline/pipeline/dtypes.py
zipline/pipeline/factors/factor.py
zipline/pipeline/filters/filter.py

Today I tried to make a CustomFactor with dtype=object and had no idea why that was failing.

ENH: Add suggestions when creating CustomTerms with incorrect dtypes

---

setup.py

For https://github.com/quantopian/zipline/issues/1995

MAINT: networkx 2 changes the behavior of out_degree

---

conda/empyrical/meta.yaml
etc/requirements.txt

MAINT: bump empyrical

---

tests/finance/test_slippage.py
zipline/finance/slippage.py

@vikram-narayan took another pass at your PR.  All my notes were small or stylistic things, so it seemed easier to just make a PR with proposed changes than to type them out in comments and have you implement them.  I tried to make each proposal a separate commit with an explanation of the change.  We should probably squash these into a single commit on merge.

Fixed bps slippage notes

---

tests/finance/test_blotter.py
tests/test_algorithm.py
tests/test_finance.py
zipline/examples/buy_and_hold.py
zipline/examples/buyapple.py
zipline/examples/dual_ema_talib.py
zipline/examples/dual_moving_average.py
zipline/examples/momentum_pipeline.py
zipline/examples/olmar.py
zipline/finance/blotter.py

set `FixedBasisPointsSlippage` as default slippage model

MAINT: set FixedBasisPointsSlippage as default

---

zipline/finance/slippage.py

Make default basis points value a float to match the docstring.

MAINT: make default bps value a float

---

conda/empyrical/meta.yaml
etc/requirements.txt

bump empyrical to 0.3.4 to fix rolling metrics and add perf attrib to empyrical

MAINT: bump empyrical to 0.3.4

---

ci/make_conda_packages.py

to find out why we stopped uploading packages to anaconda.org.

BLD: Added more logging for appveyor conda packaging

---

zipline/data/data_portal.py

When data portal code uses the start and end of an asset, the asset's
`start_date` and `end_date` members are used, instead of keeping an internal
cache in the data portal.
(At one time, the integer `sid` was passed to the data portal, necessitating the
cache; however, the current state is that the asset object is expected.)

MAINT: Remove unused start and end date methods and members.

---

zipline/algorithm.py
zipline/api.pyi

From: http://www.zipline.io/release-process.html#updating-the-python-stub-files

MAINT: Update Python stub files

---

tests/pipeline/test_column.py

Use `WithSeededRandomPipelineEngine` instead `temp_pipeline_engine`.
There will be slight changes in the expected and result indices, since a
trading calendar is used instead of a daily date range; however those changes do
not affect the intent of the test.

TST: Use ZiplineTestCase for test column.

---

etc/requirements_dev.txt

@ssanderson putting this PR up so we don't forget this change

Update responses requirement

---

conda/empyrical/meta.yaml
etc/requirements.txt

CI can starting building these packages.

MAINT: Bump requirement to empyrical 0.5.0

---

tests/pipeline/test_factor.py
tests/pipeline/test_filter.py
zipline/pipeline/data/dataset.py
zipline/pipeline/expression.py
zipline/pipeline/factors/factor.py
zipline/pipeline/filters/filter.py
zipline/pipeline/mixins.py
zipline/pipeline/term.py

Improves the representation of some nodes in the pipeline graph

ENH: Improve short reprs

---

zipline/api.pyi

DOC: Update type stubs.

---

zipline/algorithm.py

MAINT: make TradingAlgorithm._run_pipeline public

---

zipline/assets/asset_writer.py

BUG: fix support for non unique sid->exchange mappings.

---

docs/source/development-guidelines.rst

DOC: Add local installation in dev guide.

---

tests/data/test_daily_bars.py
zipline/data/hdf5_daily_bars.py
zipline/pipeline/loaders/synthetic.py
zipline/testing/predicates.py

I also highlighted a couple places where it looks like we probably need some test coverage.

BUG: Fix bug calculating end offsets for hdf5 daily bars.

---

zipline/assets/asset_db_migrations.py
zipline/assets/assets.py

Fixes a bug where _select_most_recent_symbols_chunk assumed that non-aggregated
columns in a GROUP BY expression would resolve to the first record in the
group.
Previously we rendered a select like this:
```
SELECT sid, symbol, company_symbol, share_class_symbol FROM (
SELECT sid, symbol, company_symbol, share_class_symbol
FROM equity_symbol_mappings
WHERE sid IN (<list of sids>)
ORDER_BY end_date ASCENDING
)
GROUP BY sid
```
It appears that on older versions of SQLite, this reliably gave the last symbol
for all symbol mappings associated with ``sid``, but on newer versions (or at
the very least, in whatever configuration Travis is currently using), it's no
longer the case.
As of this change we now render the following query instead:
```
SELECT sid, symbol, company_symbol, …
```

BUG: Fix _select_most_recent_symbols_chunk.

---

tests/data/test_daily_bars.py
zipline/data/hdf5_daily_bars.py

- Raise an exception on requests for assets and/or dates not available in the daily bars
- Generalize remaining US-specific tests in _DailyBarsTestCase

Small improvements for HDF5 daily bars and tests

---

tests/data/test_adjustments.py
zipline/data/adjustments.py

Lookup dates for warning message in input_dates.

BUG: don't crash on dividend warning

---

conda/trading-calendars/meta.yaml
etc/requirements.txt
tests/pipeline/test_domain.py
zipline/country.py
zipline/pipeline/domain.py

Adds Austria, Australia, Hong Kong, Italy, New Zealand, Spain

Add Another Batch of Domains

---

zipline/data/hdf5_daily_bars.py

Instead of maintaining separate read and output buffers, allocate the read
buffer with one extra row, to which we never write, and put -1s in the indexer
at the locations of invalid sids.

PERF: Avoid a copy on reads from h5.

---

etc/requirements_blaze.txt

MAINT: Upgrade to newer version of `werkzeug`

---

conda/trading-calendars/meta.yaml
etc/requirements.txt

Latest `trading-calendars` on PyPI https://pypi.org/project/trading-calendars/#history

DEP: Bump trading-calendars for George H.W. Bush Day of Mourning

---

docs/deploy.py
etc/requirements_dev.txt
setup.py
tests/history/generate_csvs.py
tests/pipeline/test_downsampling.py
tests/pipeline/test_filter.py
tests/test_labelarray.py
zipline/assets/roll_finder.py
zipline/data/bcolz_daily_bars.py
zipline/data/treasuries.py
zipline/examples/olmar.py
zipline/pipeline/data/dataset.py
zipline/pipeline/expression.py
zipline/pipeline/factors/factor.py
zipline/pipeline/filters/filter.py
zipline/pipeline/mixins.py
zipline/testing/core.py
zipline/testing/fixtures.py
zipline/utils/sharedoc.py

The new version catches some new errors, and supports nicer syntax in configuration files.

MAINT: Upgrade flake8 to 3.6.0

---

zipline/pipeline/loaders/blaze/_core.pyx

Thread the actual timestamp info down to the point where the "timestamp before asof date" error happens.

ENH: improve error message when timestamp < asof

---

tests/pipeline/test_blaze.py
zipline/pipeline/loaders/blaze/core.py

When `odo_kwargs` was None we would eagerly construct a new empty dict which would have a unique ID. This change does 2 things:
1. ExprData no longer inherits from named tuple, it was getting to be more than a simple struct.
2. ExprData now lazily constructs an empty dict for `odo_kwargs` when requested, but preserves the None value for id comparisons.

Fix exprdata comparison again

---

zipline/data/adjustments.py

Exposes `SQLiteAdjustmentReader. get_df_from_table` to selectively load tables from adjustments db.

ENH: Expose SQLiteAdjustmentReader.get_df_from_table method.

---

zipline/pipeline/factors/testing.py

Small testing utility for pipeline loaders.

DEV: add testing utility for checking term lookback windows

---

tests/data/bundles/test_core.py
tests/data/bundles/test_csvdir.py
tests/data/bundles/test_quandl.py
tests/pipeline/test_us_equity_pricing_loader.py
zipline/data/_adjustments.pyx
zipline/data/adjustments.py
zipline/data/history_loader.py
zipline/pipeline/loaders/equity_pricing_loader.py

Allows us to exclude any adjustment tables when loading `Adjustment` objects from adjustments.db.

ENH: Parametrize load_adjustments_from_sqlite to selectively load adjustments tables.

---

tests/pipeline/test_adjusted_array.py
zipline/lib/adjusted_array.py

Allows us to append new sets of adjustments to `AdjustedArray.adjustments`.

ENH: Add append_adjustments method to AdjustedArray.

---

zipline/assets/assets.py

We don't actually want these in row-major order, and the `np.array` conversion
from tuple of tuples seems to be quite slow.
master:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.004    0.004    0.498    0.498 /home/joe/quantopian/qexec/zipline_repo/zipline/assets/assets.py:1416(_compute_asset_lifetimes)
1    0.005    0.005    0.503    0.503 /home/joe/quantopian/qexec/zipline_repo/zipline/assets/assets.py:1458(lifetimes)
```
branch:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.005    0.005    0.118    0.118 /home/joe/quantopian/qexec/zipline_repo/zipline/assets/assets.py:1444(lifetimes)
1    0.001    0.001    0.112    0.112 /home/joe/quantopian/qexec/zipline_repo/zipline/assets/assets.py:1419(_compute_asset_lifetimes)
```

ENH: use zip(*it) to create 3 parallel arrays instead of a recarray

---

zipline/pipeline/hooks/progress.py

- Factor out methods for starting/stopping display.
- Clear output after closing widget.

MAINT: Tweaks to progress display.

---

zipline/pipeline/engine.py

For a 3 year US Equities pipeline, this shaves about .5 seconds off a 4 second
pipeline execution for me.
Before:
```
1    0.203    0.203    0.728    0.728 engine.py:716(_to_narrow)
```
After:
```
1    0.128    0.128    0.283    0.283 engine.py:716(_to_narrow)
```

PERF: Speed up pipeline output index construction.

---

tests/events/test_events_cme.py
tests/events/test_events_nyse.py
tests/metrics/test_metrics.py
zipline/data/data_portal.py

These directories were not being picked up by the test runner.

TST: Make events and metrics suites modules.

---

etc/requirements_blaze.txt

Reverts quantopian/zipline#2535

Revert "MAINT: Bump odo and datashape."

---

etc/requirements_blaze.txt

Reverts quantopian/zipline#2534

Revert "MAINT: Bump blaze. Adds compserver hook registration."

---

tests/finance/test_slippage.py

so they can be parallelized across boxes reliably

TST: Generate test names and order deterministically

---

Dockerfile

MAINT: Add HDF5 library

---

tests/utils/test_preprocess.py

Fix simple typo: unfortunatly -> unfortunately

---

zipline/data/bundles/core.py

MAINT: removing dead code

---

tests/finance/test_risk.py
zipline/utils/run_algo.py

Test is to ensure we're not broken as described in https://github.com/quantopian/zipline/issues/2627#issuecomment-608987852

Benchmark cleanup

---

CONTRIBUTING.rst
conda/empyrical/meta.yaml
conda/zipline/meta.yaml
docs/notebooks/tutorial.ipynb
docs/source/conf.py
docs/source/development-guidelines.rst
docs/source/release-process.rst
docs/source/trading-calendars.rst
docs/source/whatsnew/0.6.1.txt
docs/source/whatsnew/0.8.0.txt
setup.py
tests/test_labelarray.py
zipline/assets/futures.py
zipline/lib/labelarray.py
zipline/sources/requests_csv.py
zipline/utils/tradingcalendar.py

DOC: Updated http links to https

---

tests/test_examples.py
zipline/utils/run_algo.py

Fixes https://github.com/quantopian/zipline/issues/2761 and adds the docstring missing in https://github.com/quantopian/zipline/issues/2627#issuecomment-675127746.

More benchmark fixes

---

docs/source/releases.rst
docs/source/whatsnew/1.4.1.txt

Notes so far for the next release

REL: Notes for v1.4.1

---

etc/requirements.in
etc/requirements_build.in
etc/requirements_locked.txt
etc/requirements_py36_locked.txt

Found in https://github.com/conda-forge/zipline-feedstock/pull/2

MAINT: Added missing direct dependency to requirements.in
